/* Generated by Yosys 0.8+285 (git sha1 a7ac8393, clang 6.0.0-1ubuntu2 -fPIC -Os) */

(* top =  1  *)
(* src = " Generador128f_Est.v:1" *)
module  Generador128f_Est(clk_8f, reset, clk_f_Est, clk_2f_Est);
  (* src = " Generador128f_Est.v:9" *)
  wire _00_;
  (* src = " Generador128f_Est.v:9" *)
  wire _01_;
  (* src = " Generador128f_Est.v:9" *)
  wire [1:0] _02_;
  (* src = " Generador128f_Est.v:15" *)
  wire [31:0] _03_;
  wire _04_;
  wire [1:0] _05_;
  wire _06_;
  (* src = " Generador128f_Est.v:16" *)
  wire _07_;
  (* src = " Generador128f_Est.v:16" *)
  wire _08_;
  (* src = " Generador128f_Est.v:16" *)
  wire _09_;
  (* src = " Generador128f_Est.v:17" *)
  wire _10_;
  (* src = " Generador128f_Est.v:22" *)
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = " Generador128f_Est.v:5" *)
  output clk_2f_Est;
  reg clk_2f_Est;
  (* src = " Generador128f_Est.v:2" *)
  input clk_8f;
  (* src = " Generador128f_Est.v:4" *)
  output clk_f_Est;
  reg clk_f_Est;
  (* src = " Generador128f_Est.v:7" *)
  reg [1:0] contador;
  (* src = " Generador128f_Est.v:3" *)
  input reset;
  assign _06_ = contador[0] |(* src = " Generador128f_Est.v:21" *)  _05_[1];
  assign _04_ = contador[0] |(* src = " Generador128f_Est.v:16" *)  contador[1];
  assign _07_ = ~(* src = " Generador128f_Est.v:16" *) _04_;
  assign _08_ = ~(* src = " Generador128f_Est.v:21" *) _06_;
  assign _09_ = _07_ |(* src = " Generador128f_Est.v:16" *)  _08_;
  assign _12_ = _09_ ? (* src = " Generador128f_Est.v:16" *) _10_ : clk_2f_Est;
  assign _02_[0] = reset ? (* src = " Generador128f_Est.v:10" *) _03_[0] : 1'h0;
  assign _02_[1] = reset ? (* src = " Generador128f_Est.v:10" *) _03_[1] : 1'h0;
  assign _00_ = reset ? (* src = " Generador128f_Est.v:10" *) _12_ : 1'h0;
  assign _13_ = _06_ ? (* src = " Generador128f_Est.v:21" *) clk_f_Est : _11_;
  assign _01_ = reset ? (* src = " Generador128f_Est.v:10" *) _13_ : 1'h0;
  assign _10_ = ~(* src = " Generador128f_Est.v:17" *) clk_2f_Est;
  assign _11_ = ~(* src = " Generador128f_Est.v:22" *) clk_f_Est;
  (* src = " Generador128f_Est.v:9" *)
  always @(posedge clk_8f)
      contador[1] <= _02_[1];
  (* src = " Generador128f_Est.v:9" *)
  always @(posedge clk_8f)
      clk_f_Est <= _01_;
  (* src = " Generador128f_Est.v:9" *)
  always @(posedge clk_8f)
      clk_2f_Est <= _00_;
  (* src = " Generador128f_Est.v:9" *)
  always @(posedge clk_8f)
      contador[0] <= _02_[0];
  assign _03_[1] = contador[1] ^(* src = " Generador128f_Est.v:15|<techmap.v>:263" *)  contador[0];
  assign _03_[0] = contador[0] ^(* src = " Generador128f_Est.v:15|<techmap.v>:262" *)  1'h1;
  assign _05_[1] = contador[1] ^(* src = " Generador128f_Est.v:21" *)  1'h1;
endmodule
