/* Generated by Yosys 0.8+285 (git sha1 a7ac8393, clang 6.0.0-1ubuntu2 -fPIC -Os) */

(* src = "Otros_flops_synth.v:1" *)
module Otros_flops_synth(valid_in44, clk_8f, reset, valid_inF);
  (* src = "Otros_flops_synth.v:8" *)
  wire _0_;
  wire _1_;
  (* src = "Otros_flops_synth.v:3" *)
  input clk_8f;
  (* src = "Otros_flops_synth.v:4" *)
  input reset;
  (* src = "Otros_flops_synth.v:2" *)
  input valid_in44;
  (* src = "Otros_flops_synth.v:5" *)
  output valid_inF;
  NAND _2_ (
    .A(valid_in44),
    .B(reset),
    .Y(_1_)
  );
  NOT _3_ (
    .A(_1_),
    .Y(_0_)
  );
  (* src = "Otros_flops_synth.v:8" *)
  DFF _4_ (
    .C(clk_8f),
    .D(_0_),
    .Q(valid_inF)
  );
endmodule

(* src = "paralelo_serie_synth.v:1" *)
module paralelo_serie_synth(data_inP, reset, clk_8f, clk_f, valid_in, data2send, data_outS);
  (* src = "paralelo_serie_synth.v:51" *)
  wire [7:0] _000_;
  (* src = "paralelo_serie_synth.v:51" *)
  wire _001_;
  (* src = "paralelo_serie_synth.v:51" *)
  wire [2:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  (* src = "paralelo_serie_synth.v:4" *)
  input clk_8f;
  (* src = "paralelo_serie_synth.v:5" *)
  input clk_f;
  (* src = "paralelo_serie_synth.v:7" *)
  output [7:0] data2send;
  (* src = "paralelo_serie_synth.v:2" *)
  input [7:0] data_inP;
  (* src = "paralelo_serie_synth.v:8" *)
  output data_outS;
  (* src = "paralelo_serie_synth.v:10" *)
  wire [2:0] out44;
  (* src = "paralelo_serie_synth.v:3" *)
  input reset;
  (* src = "paralelo_serie_synth.v:6" *)
  input valid_in;
  NOT _046_ (
    .A(data_inP[1]),
    .Y(_003_)
  );
  NOT _047_ (
    .A(data_inP[6]),
    .Y(_004_)
  );
  NOT _048_ (
    .A(reset),
    .Y(_005_)
  );
  NOT _049_ (
    .A(data2send[4]),
    .Y(_006_)
  );
  NOT _050_ (
    .A(out44[2]),
    .Y(_007_)
  );
  NOT _051_ (
    .A(out44[1]),
    .Y(_008_)
  );
  NOT _052_ (
    .A(out44[0]),
    .Y(_009_)
  );
  NOT _053_ (
    .A(data_inP[0]),
    .Y(_010_)
  );
  NOR _054_ (
    .A(_005_),
    .B(_009_),
    .Y(_011_)
  );
  NAND _055_ (
    .A(out44[2]),
    .B(data2send[7]),
    .Y(_012_)
  );
  NAND _056_ (
    .A(_007_),
    .B(data2send[3]),
    .Y(_013_)
  );
  NAND _057_ (
    .A(_012_),
    .B(_013_),
    .Y(_014_)
  );
  NAND _058_ (
    .A(out44[1]),
    .B(_014_),
    .Y(_015_)
  );
  NAND _059_ (
    .A(out44[2]),
    .B(data2send[5]),
    .Y(_016_)
  );
  NAND _060_ (
    .A(_007_),
    .B(data2send[1]),
    .Y(_017_)
  );
  NAND _061_ (
    .A(_016_),
    .B(_017_),
    .Y(_018_)
  );
  NAND _062_ (
    .A(_008_),
    .B(_018_),
    .Y(_019_)
  );
  NAND _063_ (
    .A(_015_),
    .B(_019_),
    .Y(_020_)
  );
  NAND _064_ (
    .A(_011_),
    .B(_020_),
    .Y(_021_)
  );
  NOR _065_ (
    .A(out44[2]),
    .B(data2send[2]),
    .Y(_022_)
  );
  NOR _066_ (
    .A(_007_),
    .B(data2send[6]),
    .Y(_023_)
  );
  NOR _067_ (
    .A(_022_),
    .B(_023_),
    .Y(_024_)
  );
  NOR _068_ (
    .A(_005_),
    .B(out44[0]),
    .Y(_002_[0])
  );
  NAND _069_ (
    .A(_024_),
    .B(_002_[0]),
    .Y(_025_)
  );
  NOR _070_ (
    .A(_008_),
    .B(_025_),
    .Y(_026_)
  );
  NOR _071_ (
    .A(out44[1]),
    .B(out44[0]),
    .Y(_027_)
  );
  NAND _072_ (
    .A(_008_),
    .B(_009_),
    .Y(_028_)
  );
  NAND _073_ (
    .A(reset),
    .B(_027_),
    .Y(_029_)
  );
  NAND _074_ (
    .A(_006_),
    .B(out44[2]),
    .Y(_030_)
  );
  NOR _075_ (
    .A(data2send[0]),
    .B(out44[2]),
    .Y(_031_)
  );
  NOT _076_ (
    .A(_031_),
    .Y(_032_)
  );
  NAND _077_ (
    .A(_030_),
    .B(_032_),
    .Y(_033_)
  );
  NOR _078_ (
    .A(_029_),
    .B(_033_),
    .Y(_034_)
  );
  NOR _079_ (
    .A(_026_),
    .B(_034_),
    .Y(_035_)
  );
  NAND _080_ (
    .A(_021_),
    .B(_035_),
    .Y(_001_)
  );
  NAND _081_ (
    .A(out44[1]),
    .B(_011_),
    .Y(_036_)
  );
  NAND _082_ (
    .A(_029_),
    .B(_036_),
    .Y(_002_[1])
  );
  NOR _083_ (
    .A(_007_),
    .B(_027_),
    .Y(_037_)
  );
  NOR _084_ (
    .A(out44[2]),
    .B(_028_),
    .Y(_038_)
  );
  NOR _085_ (
    .A(_037_),
    .B(_038_),
    .Y(_039_)
  );
  NOR _086_ (
    .A(_005_),
    .B(_039_),
    .Y(_002_[2])
  );
  NAND _087_ (
    .A(valid_in),
    .B(reset),
    .Y(_040_)
  );
  NOR _088_ (
    .A(_010_),
    .B(_040_),
    .Y(_000_[0])
  );
  NOR _089_ (
    .A(_003_),
    .B(_040_),
    .Y(_000_[1])
  );
  NOR _090_ (
    .A(data_inP[2]),
    .B(_040_),
    .Y(_041_)
  );
  NOT _091_ (
    .A(_041_),
    .Y(_000_[2])
  );
  NOR _092_ (
    .A(data_inP[3]),
    .B(_040_),
    .Y(_042_)
  );
  NOT _093_ (
    .A(_042_),
    .Y(_000_[3])
  );
  NOR _094_ (
    .A(data_inP[4]),
    .B(_040_),
    .Y(_043_)
  );
  NOT _095_ (
    .A(_043_),
    .Y(_000_[4])
  );
  NOR _096_ (
    .A(data_inP[5]),
    .B(_040_),
    .Y(_044_)
  );
  NOT _097_ (
    .A(_044_),
    .Y(_000_[5])
  );
  NOR _098_ (
    .A(_004_),
    .B(_040_),
    .Y(_000_[6])
  );
  NOR _099_ (
    .A(data_inP[7]),
    .B(_040_),
    .Y(_045_)
  );
  NOT _100_ (
    .A(_045_),
    .Y(_000_[7])
  );
  (* src = "paralelo_serie_synth.v:51" *)
  DFF _101_ (
    .C(clk_8f),
    .D(_002_[0]),
    .Q(out44[0])
  );
  (* src = "paralelo_serie_synth.v:51" *)
  DFF _102_ (
    .C(clk_8f),
    .D(_002_[1]),
    .Q(out44[1])
  );
  (* src = "paralelo_serie_synth.v:51" *)
  DFF _103_ (
    .C(clk_8f),
    .D(_002_[2]),
    .Q(out44[2])
  );
  (* src = "paralelo_serie_synth.v:51" *)
  DFF _104_ (
    .C(clk_8f),
    .D(_000_[0]),
    .Q(data2send[0])
  );
  (* src = "paralelo_serie_synth.v:51" *)
  DFF _105_ (
    .C(clk_8f),
    .D(_000_[1]),
    .Q(data2send[1])
  );
  (* src = "paralelo_serie_synth.v:51" *)
  DFF _106_ (
    .C(clk_8f),
    .D(_000_[2]),
    .Q(data2send[2])
  );
  (* src = "paralelo_serie_synth.v:51" *)
  DFF _107_ (
    .C(clk_8f),
    .D(_000_[3]),
    .Q(data2send[3])
  );
  (* src = "paralelo_serie_synth.v:51" *)
  DFF _108_ (
    .C(clk_8f),
    .D(_000_[4]),
    .Q(data2send[4])
  );
  (* src = "paralelo_serie_synth.v:51" *)
  DFF _109_ (
    .C(clk_8f),
    .D(_000_[5]),
    .Q(data2send[5])
  );
  (* src = "paralelo_serie_synth.v:51" *)
  DFF _110_ (
    .C(clk_8f),
    .D(_000_[6]),
    .Q(data2send[6])
  );
  (* src = "paralelo_serie_synth.v:51" *)
  DFF _111_ (
    .C(clk_8f),
    .D(_000_[7]),
    .Q(data2send[7])
  );
  (* src = "paralelo_serie_synth.v:51" *)
  DFF _112_ (
    .C(clk_8f),
    .D(_001_),
    .Q(data_outS)
  );
endmodule

(* src = "byte_striping_synth.v:1" *)
module byte_striping_synth(clk_2f, clk_f, valid_in, data_in, reset, lane_0, lane_1, valid_0, valid_1);
  (* src = "byte_striping_synth.v:53" *)
  wire _000_;
  (* src = "byte_striping_synth.v:53" *)
  wire _001_;
  (* src = "byte_striping_synth.v:14" *)
  wire [7:0] _002_;
  (* src = "byte_striping_synth.v:53" *)
  wire [7:0] _003_;
  (* src = "byte_striping_synth.v:53" *)
  wire [7:0] _004_;
  (* src = "byte_striping_synth.v:14" *)
  wire _005_;
  (* src = "byte_striping_synth.v:39" *)
  wire _006_;
  (* src = "byte_striping_synth.v:23" *)
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  (* src = "byte_striping_synth.v:2" *)
  input clk_2f;
  (* src = "byte_striping_synth.v:3" *)
  input clk_f;
  (* src = "byte_striping_synth.v:12" *)
  wire contador0;
  (* src = "byte_striping_synth.v:12" *)
  wire contador1;
  (* src = "byte_striping_synth.v:5" *)
  input [7:0] data_in;
  (* src = "byte_striping_synth.v:13" *)
  wire [7:0] in;
  (* src = "byte_striping_synth.v:7" *)
  output [7:0] lane_0;
  (* src = "byte_striping_synth.v:8" *)
  output [7:0] lane_1;
  (* src = "byte_striping_synth.v:6" *)
  input reset;
  (* src = "byte_striping_synth.v:12" *)
  wire v_in;
  (* src = "byte_striping_synth.v:9" *)
  output valid_0;
  (* src = "byte_striping_synth.v:10" *)
  output valid_1;
  (* src = "byte_striping_synth.v:4" *)
  input valid_in;
  NOT _097_ (
    .A(v_in),
    .Y(_069_)
  );
  NOT _098_ (
    .A(in[0]),
    .Y(_070_)
  );
  NOT _099_ (
    .A(in[1]),
    .Y(_071_)
  );
  NOT _100_ (
    .A(in[2]),
    .Y(_072_)
  );
  NOT _101_ (
    .A(in[3]),
    .Y(_073_)
  );
  NOT _102_ (
    .A(in[4]),
    .Y(_074_)
  );
  NOT _103_ (
    .A(in[5]),
    .Y(_075_)
  );
  NOT _104_ (
    .A(in[6]),
    .Y(_076_)
  );
  NOT _105_ (
    .A(in[7]),
    .Y(_077_)
  );
  NOT _106_ (
    .A(lane_0[0]),
    .Y(_078_)
  );
  NOT _107_ (
    .A(lane_0[1]),
    .Y(_079_)
  );
  NOT _108_ (
    .A(lane_0[2]),
    .Y(_080_)
  );
  NOT _109_ (
    .A(lane_0[3]),
    .Y(_081_)
  );
  NOT _110_ (
    .A(lane_0[4]),
    .Y(_082_)
  );
  NOT _111_ (
    .A(lane_0[5]),
    .Y(_083_)
  );
  NOT _112_ (
    .A(lane_0[6]),
    .Y(_084_)
  );
  NOT _113_ (
    .A(lane_0[7]),
    .Y(_085_)
  );
  NOT _114_ (
    .A(contador0),
    .Y(_086_)
  );
  NOT _115_ (
    .A(contador1),
    .Y(_087_)
  );
  NOT _116_ (
    .A(clk_f),
    .Y(_008_)
  );
  NAND _117_ (
    .A(contador0),
    .B(_087_),
    .Y(_088_)
  );
  NAND _118_ (
    .A(v_in),
    .B(contador1),
    .Y(_089_)
  );
  NAND _119_ (
    .A(v_in),
    .B(_088_),
    .Y(_090_)
  );
  NOR _120_ (
    .A(in[0]),
    .B(_090_),
    .Y(_091_)
  );
  NAND _121_ (
    .A(_078_),
    .B(_090_),
    .Y(_092_)
  );
  NAND _122_ (
    .A(reset),
    .B(_092_),
    .Y(_093_)
  );
  NOR _123_ (
    .A(_091_),
    .B(_093_),
    .Y(_003_[0])
  );
  NOR _124_ (
    .A(in[1]),
    .B(_090_),
    .Y(_094_)
  );
  NAND _125_ (
    .A(_079_),
    .B(_090_),
    .Y(_095_)
  );
  NAND _126_ (
    .A(reset),
    .B(_095_),
    .Y(_096_)
  );
  NOR _127_ (
    .A(_094_),
    .B(_096_),
    .Y(_003_[1])
  );
  NOR _128_ (
    .A(in[2]),
    .B(_090_),
    .Y(_009_)
  );
  NAND _129_ (
    .A(_080_),
    .B(_090_),
    .Y(_010_)
  );
  NAND _130_ (
    .A(reset),
    .B(_010_),
    .Y(_011_)
  );
  NOR _131_ (
    .A(_009_),
    .B(_011_),
    .Y(_003_[2])
  );
  NOR _132_ (
    .A(in[3]),
    .B(_090_),
    .Y(_012_)
  );
  NAND _133_ (
    .A(_081_),
    .B(_090_),
    .Y(_013_)
  );
  NAND _134_ (
    .A(reset),
    .B(_013_),
    .Y(_014_)
  );
  NOR _135_ (
    .A(_012_),
    .B(_014_),
    .Y(_003_[3])
  );
  NOR _136_ (
    .A(in[4]),
    .B(_090_),
    .Y(_015_)
  );
  NAND _137_ (
    .A(_082_),
    .B(_090_),
    .Y(_016_)
  );
  NAND _138_ (
    .A(reset),
    .B(_016_),
    .Y(_017_)
  );
  NOR _139_ (
    .A(_015_),
    .B(_017_),
    .Y(_003_[4])
  );
  NOR _140_ (
    .A(in[5]),
    .B(_090_),
    .Y(_018_)
  );
  NAND _141_ (
    .A(_083_),
    .B(_090_),
    .Y(_019_)
  );
  NAND _142_ (
    .A(reset),
    .B(_019_),
    .Y(_020_)
  );
  NOR _143_ (
    .A(_018_),
    .B(_020_),
    .Y(_003_[5])
  );
  NOR _144_ (
    .A(in[6]),
    .B(_090_),
    .Y(_021_)
  );
  NAND _145_ (
    .A(_084_),
    .B(_090_),
    .Y(_022_)
  );
  NAND _146_ (
    .A(reset),
    .B(_022_),
    .Y(_023_)
  );
  NOR _147_ (
    .A(_021_),
    .B(_023_),
    .Y(_003_[6])
  );
  NOR _148_ (
    .A(in[7]),
    .B(_090_),
    .Y(_024_)
  );
  NAND _149_ (
    .A(_085_),
    .B(_090_),
    .Y(_025_)
  );
  NAND _150_ (
    .A(reset),
    .B(_025_),
    .Y(_026_)
  );
  NOR _151_ (
    .A(_024_),
    .B(_026_),
    .Y(_003_[7])
  );
  NAND _152_ (
    .A(v_in),
    .B(reset),
    .Y(_027_)
  );
  NOR _153_ (
    .A(contador0),
    .B(_027_),
    .Y(_006_)
  );
  NOT _154_ (
    .A(_006_),
    .Y(_028_)
  );
  NOR _155_ (
    .A(v_in),
    .B(_086_),
    .Y(_029_)
  );
  NAND _156_ (
    .A(reset),
    .B(_029_),
    .Y(_030_)
  );
  NAND _157_ (
    .A(_028_),
    .B(_030_),
    .Y(_000_)
  );
  NOR _158_ (
    .A(v_in),
    .B(contador1),
    .Y(_031_)
  );
  NOT _159_ (
    .A(_031_),
    .Y(_032_)
  );
  NAND _160_ (
    .A(_089_),
    .B(_032_),
    .Y(_033_)
  );
  NAND _161_ (
    .A(reset),
    .B(_033_),
    .Y(_001_)
  );
  NOR _162_ (
    .A(contador0),
    .B(_087_),
    .Y(_034_)
  );
  NOR _163_ (
    .A(_069_),
    .B(_034_),
    .Y(_035_)
  );
  NOR _164_ (
    .A(lane_1[0]),
    .B(_035_),
    .Y(_036_)
  );
  NAND _165_ (
    .A(_070_),
    .B(_035_),
    .Y(_037_)
  );
  NAND _166_ (
    .A(reset),
    .B(_037_),
    .Y(_038_)
  );
  NOR _167_ (
    .A(_036_),
    .B(_038_),
    .Y(_004_[0])
  );
  NOR _168_ (
    .A(lane_1[1]),
    .B(_035_),
    .Y(_039_)
  );
  NAND _169_ (
    .A(_071_),
    .B(_035_),
    .Y(_040_)
  );
  NAND _170_ (
    .A(reset),
    .B(_040_),
    .Y(_041_)
  );
  NOR _171_ (
    .A(_039_),
    .B(_041_),
    .Y(_004_[1])
  );
  NOR _172_ (
    .A(lane_1[2]),
    .B(_035_),
    .Y(_042_)
  );
  NAND _173_ (
    .A(_072_),
    .B(_035_),
    .Y(_043_)
  );
  NAND _174_ (
    .A(reset),
    .B(_043_),
    .Y(_044_)
  );
  NOR _175_ (
    .A(_042_),
    .B(_044_),
    .Y(_004_[2])
  );
  NOR _176_ (
    .A(lane_1[3]),
    .B(_035_),
    .Y(_045_)
  );
  NAND _177_ (
    .A(_073_),
    .B(_035_),
    .Y(_046_)
  );
  NAND _178_ (
    .A(reset),
    .B(_046_),
    .Y(_047_)
  );
  NOR _179_ (
    .A(_045_),
    .B(_047_),
    .Y(_004_[3])
  );
  NOR _180_ (
    .A(lane_1[4]),
    .B(_035_),
    .Y(_048_)
  );
  NAND _181_ (
    .A(_074_),
    .B(_035_),
    .Y(_049_)
  );
  NAND _182_ (
    .A(reset),
    .B(_049_),
    .Y(_050_)
  );
  NOR _183_ (
    .A(_048_),
    .B(_050_),
    .Y(_004_[4])
  );
  NOR _184_ (
    .A(lane_1[5]),
    .B(_035_),
    .Y(_051_)
  );
  NAND _185_ (
    .A(_075_),
    .B(_035_),
    .Y(_052_)
  );
  NAND _186_ (
    .A(reset),
    .B(_052_),
    .Y(_053_)
  );
  NOR _187_ (
    .A(_051_),
    .B(_053_),
    .Y(_004_[5])
  );
  NOR _188_ (
    .A(lane_1[6]),
    .B(_035_),
    .Y(_054_)
  );
  NAND _189_ (
    .A(_076_),
    .B(_035_),
    .Y(_055_)
  );
  NAND _190_ (
    .A(reset),
    .B(_055_),
    .Y(_056_)
  );
  NOR _191_ (
    .A(_054_),
    .B(_056_),
    .Y(_004_[6])
  );
  NOR _192_ (
    .A(lane_1[7]),
    .B(_035_),
    .Y(_057_)
  );
  NAND _193_ (
    .A(_077_),
    .B(_035_),
    .Y(_058_)
  );
  NAND _194_ (
    .A(reset),
    .B(_058_),
    .Y(_059_)
  );
  NOR _195_ (
    .A(_057_),
    .B(_059_),
    .Y(_004_[7])
  );
  NOR _196_ (
    .A(contador1),
    .B(_027_),
    .Y(_007_)
  );
  NAND _197_ (
    .A(reset),
    .B(data_in[0]),
    .Y(_060_)
  );
  NOT _198_ (
    .A(_060_),
    .Y(_002_[0])
  );
  NAND _199_ (
    .A(reset),
    .B(data_in[1]),
    .Y(_061_)
  );
  NOT _200_ (
    .A(_061_),
    .Y(_002_[1])
  );
  NAND _201_ (
    .A(reset),
    .B(data_in[2]),
    .Y(_062_)
  );
  NOT _202_ (
    .A(_062_),
    .Y(_002_[2])
  );
  NAND _203_ (
    .A(reset),
    .B(data_in[3]),
    .Y(_063_)
  );
  NOT _204_ (
    .A(_063_),
    .Y(_002_[3])
  );
  NAND _205_ (
    .A(reset),
    .B(data_in[4]),
    .Y(_064_)
  );
  NOT _206_ (
    .A(_064_),
    .Y(_002_[4])
  );
  NAND _207_ (
    .A(reset),
    .B(data_in[5]),
    .Y(_065_)
  );
  NOT _208_ (
    .A(_065_),
    .Y(_002_[5])
  );
  NAND _209_ (
    .A(reset),
    .B(data_in[6]),
    .Y(_066_)
  );
  NOT _210_ (
    .A(_066_),
    .Y(_002_[6])
  );
  NAND _211_ (
    .A(reset),
    .B(data_in[7]),
    .Y(_067_)
  );
  NOT _212_ (
    .A(_067_),
    .Y(_002_[7])
  );
  NAND _213_ (
    .A(reset),
    .B(valid_in),
    .Y(_068_)
  );
  NOT _214_ (
    .A(_068_),
    .Y(_005_)
  );
  (* src = "byte_striping_synth.v:53" *)
  DFF _215_ (
    .C(clk_2f),
    .D(_004_[0]),
    .Q(lane_1[0])
  );
  (* src = "byte_striping_synth.v:53" *)
  DFF _216_ (
    .C(clk_2f),
    .D(_004_[1]),
    .Q(lane_1[1])
  );
  (* src = "byte_striping_synth.v:53" *)
  DFF _217_ (
    .C(clk_2f),
    .D(_004_[2]),
    .Q(lane_1[2])
  );
  (* src = "byte_striping_synth.v:53" *)
  DFF _218_ (
    .C(clk_2f),
    .D(_004_[3]),
    .Q(lane_1[3])
  );
  (* src = "byte_striping_synth.v:53" *)
  DFF _219_ (
    .C(clk_2f),
    .D(_004_[4]),
    .Q(lane_1[4])
  );
  (* src = "byte_striping_synth.v:53" *)
  DFF _220_ (
    .C(clk_2f),
    .D(_004_[5]),
    .Q(lane_1[5])
  );
  (* src = "byte_striping_synth.v:53" *)
  DFF _221_ (
    .C(clk_2f),
    .D(_004_[6]),
    .Q(lane_1[6])
  );
  (* src = "byte_striping_synth.v:53" *)
  DFF _222_ (
    .C(clk_2f),
    .D(_004_[7]),
    .Q(lane_1[7])
  );
  (* src = "byte_striping_synth.v:53" *)
  DFF _223_ (
    .C(clk_2f),
    .D(_001_),
    .Q(contador1)
  );
  (* src = "byte_striping_synth.v:53" *)
  DFF _224_ (
    .C(clk_2f),
    .D(_000_),
    .Q(contador0)
  );
  (* src = "byte_striping_synth.v:53" *)
  DFF _225_ (
    .C(clk_2f),
    .D(_003_[0]),
    .Q(lane_0[0])
  );
  (* src = "byte_striping_synth.v:53" *)
  DFF _226_ (
    .C(clk_2f),
    .D(_003_[1]),
    .Q(lane_0[1])
  );
  (* src = "byte_striping_synth.v:53" *)
  DFF _227_ (
    .C(clk_2f),
    .D(_003_[2]),
    .Q(lane_0[2])
  );
  (* src = "byte_striping_synth.v:53" *)
  DFF _228_ (
    .C(clk_2f),
    .D(_003_[3]),
    .Q(lane_0[3])
  );
  (* src = "byte_striping_synth.v:53" *)
  DFF _229_ (
    .C(clk_2f),
    .D(_003_[4]),
    .Q(lane_0[4])
  );
  (* src = "byte_striping_synth.v:53" *)
  DFF _230_ (
    .C(clk_2f),
    .D(_003_[5]),
    .Q(lane_0[5])
  );
  (* src = "byte_striping_synth.v:53" *)
  DFF _231_ (
    .C(clk_2f),
    .D(_003_[6]),
    .Q(lane_0[6])
  );
  (* src = "byte_striping_synth.v:53" *)
  DFF _232_ (
    .C(clk_2f),
    .D(_003_[7]),
    .Q(lane_0[7])
  );
  (* src = "byte_striping_synth.v:39" *)
  DFF _233_ (
    .C(clk_f),
    .D(_006_),
    .Q(valid_0)
  );
  (* src = "byte_striping_synth.v:23" *)
  DFF _234_ (
    .C(_008_),
    .D(_007_),
    .Q(valid_1)
  );
  (* src = "byte_striping_synth.v:14" *)
  DFF _235_ (
    .C(clk_2f),
    .D(_005_),
    .Q(v_in)
  );
  (* src = "byte_striping_synth.v:14" *)
  DFF _236_ (
    .C(clk_2f),
    .D(_002_[0]),
    .Q(in[0])
  );
  (* src = "byte_striping_synth.v:14" *)
  DFF _237_ (
    .C(clk_2f),
    .D(_002_[1]),
    .Q(in[1])
  );
  (* src = "byte_striping_synth.v:14" *)
  DFF _238_ (
    .C(clk_2f),
    .D(_002_[2]),
    .Q(in[2])
  );
  (* src = "byte_striping_synth.v:14" *)
  DFF _239_ (
    .C(clk_2f),
    .D(_002_[3]),
    .Q(in[3])
  );
  (* src = "byte_striping_synth.v:14" *)
  DFF _240_ (
    .C(clk_2f),
    .D(_002_[4]),
    .Q(in[4])
  );
  (* src = "byte_striping_synth.v:14" *)
  DFF _241_ (
    .C(clk_2f),
    .D(_002_[5]),
    .Q(in[5])
  );
  (* src = "byte_striping_synth.v:14" *)
  DFF _242_ (
    .C(clk_2f),
    .D(_002_[6]),
    .Q(in[6])
  );
  (* src = "byte_striping_synth.v:14" *)
  DFF _243_ (
    .C(clk_2f),
    .D(_002_[7]),
    .Q(in[7])
  );
endmodule

(* src = "etapa2_flops_synth.v:1" *)
module etapa2_flops_synth(data_in0, valid_in0, data_out0, valid_out0, clk_8f, reset);
  (* src = "etapa2_flops_synth.v:10" *)
  wire [7:0] _00_;
  (* src = "etapa2_flops_synth.v:10" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  (* src = "etapa2_flops_synth.v:6" *)
  input clk_8f;
  (* src = "etapa2_flops_synth.v:2" *)
  input [7:0] data_in0;
  (* src = "etapa2_flops_synth.v:4" *)
  output [7:0] data_out0;
  (* src = "etapa2_flops_synth.v:7" *)
  input reset;
  (* src = "etapa2_flops_synth.v:3" *)
  input valid_in0;
  (* src = "etapa2_flops_synth.v:5" *)
  output valid_out0;
  NAND _11_ (
    .A(data_in0[1]),
    .B(reset),
    .Y(_02_)
  );
  NOT _12_ (
    .A(_02_),
    .Y(_00_[1])
  );
  NAND _13_ (
    .A(reset),
    .B(data_in0[2]),
    .Y(_03_)
  );
  NOT _14_ (
    .A(_03_),
    .Y(_00_[2])
  );
  NAND _15_ (
    .A(reset),
    .B(data_in0[3]),
    .Y(_04_)
  );
  NOT _16_ (
    .A(_04_),
    .Y(_00_[3])
  );
  NAND _17_ (
    .A(reset),
    .B(data_in0[4]),
    .Y(_05_)
  );
  NOT _18_ (
    .A(_05_),
    .Y(_00_[4])
  );
  NAND _19_ (
    .A(reset),
    .B(data_in0[5]),
    .Y(_06_)
  );
  NOT _20_ (
    .A(_06_),
    .Y(_00_[5])
  );
  NAND _21_ (
    .A(reset),
    .B(data_in0[6]),
    .Y(_07_)
  );
  NOT _22_ (
    .A(_07_),
    .Y(_00_[6])
  );
  NAND _23_ (
    .A(reset),
    .B(data_in0[7]),
    .Y(_08_)
  );
  NOT _24_ (
    .A(_08_),
    .Y(_00_[7])
  );
  NAND _25_ (
    .A(reset),
    .B(valid_in0),
    .Y(_09_)
  );
  NOT _26_ (
    .A(_09_),
    .Y(_01_)
  );
  NAND _27_ (
    .A(reset),
    .B(data_in0[0]),
    .Y(_10_)
  );
  NOT _28_ (
    .A(_10_),
    .Y(_00_[0])
  );
  (* src = "etapa2_flops_synth.v:10" *)
  DFF _29_ (
    .C(clk_8f),
    .D(_00_[0]),
    .Q(data_out0[0])
  );
  (* src = "etapa2_flops_synth.v:10" *)
  DFF _30_ (
    .C(clk_8f),
    .D(_00_[1]),
    .Q(data_out0[1])
  );
  (* src = "etapa2_flops_synth.v:10" *)
  DFF _31_ (
    .C(clk_8f),
    .D(_00_[2]),
    .Q(data_out0[2])
  );
  (* src = "etapa2_flops_synth.v:10" *)
  DFF _32_ (
    .C(clk_8f),
    .D(_00_[3]),
    .Q(data_out0[3])
  );
  (* src = "etapa2_flops_synth.v:10" *)
  DFF _33_ (
    .C(clk_8f),
    .D(_00_[4]),
    .Q(data_out0[4])
  );
  (* src = "etapa2_flops_synth.v:10" *)
  DFF _34_ (
    .C(clk_8f),
    .D(_00_[5]),
    .Q(data_out0[5])
  );
  (* src = "etapa2_flops_synth.v:10" *)
  DFF _35_ (
    .C(clk_8f),
    .D(_00_[6]),
    .Q(data_out0[6])
  );
  (* src = "etapa2_flops_synth.v:10" *)
  DFF _36_ (
    .C(clk_8f),
    .D(_00_[7]),
    .Q(data_out0[7])
  );
  (* src = "etapa2_flops_synth.v:10" *)
  DFF _37_ (
    .C(clk_8f),
    .D(_01_),
    .Q(valid_out0)
  );
endmodule

(* src = "etapa_flops_synth.v:1" *)
module etapa_flops_synth(data_in0, data_in1, valid_in0, valid_in1, data_out0, data_out1, valid_out0, valid_out1, clk_2f, reset);
  (* src = "etapa_flops_synth.v:14" *)
  wire [7:0] _00_;
  (* src = "etapa_flops_synth.v:14" *)
  wire [7:0] _01_;
  (* src = "etapa_flops_synth.v:14" *)
  wire _02_;
  (* src = "etapa_flops_synth.v:14" *)
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  (* src = "etapa_flops_synth.v:10" *)
  input clk_2f;
  (* src = "etapa_flops_synth.v:2" *)
  input [7:0] data_in0;
  (* src = "etapa_flops_synth.v:3" *)
  input [7:0] data_in1;
  (* src = "etapa_flops_synth.v:6" *)
  output [7:0] data_out0;
  (* src = "etapa_flops_synth.v:7" *)
  output [7:0] data_out1;
  (* src = "etapa_flops_synth.v:11" *)
  input reset;
  (* src = "etapa_flops_synth.v:4" *)
  input valid_in0;
  (* src = "etapa_flops_synth.v:5" *)
  input valid_in1;
  (* src = "etapa_flops_synth.v:8" *)
  output valid_out0;
  (* src = "etapa_flops_synth.v:9" *)
  output valid_out1;
  NAND _22_ (
    .A(data_in1[1]),
    .B(reset),
    .Y(_04_)
  );
  NOT _23_ (
    .A(_04_),
    .Y(_01_[1])
  );
  NAND _24_ (
    .A(reset),
    .B(data_in1[2]),
    .Y(_05_)
  );
  NOT _25_ (
    .A(_05_),
    .Y(_01_[2])
  );
  NAND _26_ (
    .A(reset),
    .B(data_in1[3]),
    .Y(_06_)
  );
  NOT _27_ (
    .A(_06_),
    .Y(_01_[3])
  );
  NAND _28_ (
    .A(reset),
    .B(data_in1[4]),
    .Y(_07_)
  );
  NOT _29_ (
    .A(_07_),
    .Y(_01_[4])
  );
  NAND _30_ (
    .A(reset),
    .B(data_in1[5]),
    .Y(_08_)
  );
  NOT _31_ (
    .A(_08_),
    .Y(_01_[5])
  );
  NAND _32_ (
    .A(reset),
    .B(data_in1[6]),
    .Y(_09_)
  );
  NOT _33_ (
    .A(_09_),
    .Y(_01_[6])
  );
  NAND _34_ (
    .A(reset),
    .B(data_in1[7]),
    .Y(_10_)
  );
  NOT _35_ (
    .A(_10_),
    .Y(_01_[7])
  );
  NAND _36_ (
    .A(reset),
    .B(valid_in1),
    .Y(_11_)
  );
  NOT _37_ (
    .A(_11_),
    .Y(_03_)
  );
  NAND _38_ (
    .A(reset),
    .B(valid_in0),
    .Y(_12_)
  );
  NOT _39_ (
    .A(_12_),
    .Y(_02_)
  );
  NAND _40_ (
    .A(reset),
    .B(data_in0[0]),
    .Y(_13_)
  );
  NOT _41_ (
    .A(_13_),
    .Y(_00_[0])
  );
  NAND _42_ (
    .A(reset),
    .B(data_in0[1]),
    .Y(_14_)
  );
  NOT _43_ (
    .A(_14_),
    .Y(_00_[1])
  );
  NAND _44_ (
    .A(reset),
    .B(data_in0[2]),
    .Y(_15_)
  );
  NOT _45_ (
    .A(_15_),
    .Y(_00_[2])
  );
  NAND _46_ (
    .A(reset),
    .B(data_in0[3]),
    .Y(_16_)
  );
  NOT _47_ (
    .A(_16_),
    .Y(_00_[3])
  );
  NAND _48_ (
    .A(reset),
    .B(data_in0[4]),
    .Y(_17_)
  );
  NOT _49_ (
    .A(_17_),
    .Y(_00_[4])
  );
  NAND _50_ (
    .A(reset),
    .B(data_in0[5]),
    .Y(_18_)
  );
  NOT _51_ (
    .A(_18_),
    .Y(_00_[5])
  );
  NAND _52_ (
    .A(reset),
    .B(data_in0[6]),
    .Y(_19_)
  );
  NOT _53_ (
    .A(_19_),
    .Y(_00_[6])
  );
  NAND _54_ (
    .A(reset),
    .B(data_in0[7]),
    .Y(_20_)
  );
  NOT _55_ (
    .A(_20_),
    .Y(_00_[7])
  );
  NAND _56_ (
    .A(reset),
    .B(data_in1[0]),
    .Y(_21_)
  );
  NOT _57_ (
    .A(_21_),
    .Y(_01_[0])
  );
  (* src = "etapa_flops_synth.v:14" *)
  DFF _58_ (
    .C(clk_2f),
    .D(_00_[0]),
    .Q(data_out0[0])
  );
  (* src = "etapa_flops_synth.v:14" *)
  DFF _59_ (
    .C(clk_2f),
    .D(_00_[1]),
    .Q(data_out0[1])
  );
  (* src = "etapa_flops_synth.v:14" *)
  DFF _60_ (
    .C(clk_2f),
    .D(_00_[2]),
    .Q(data_out0[2])
  );
  (* src = "etapa_flops_synth.v:14" *)
  DFF _61_ (
    .C(clk_2f),
    .D(_00_[3]),
    .Q(data_out0[3])
  );
  (* src = "etapa_flops_synth.v:14" *)
  DFF _62_ (
    .C(clk_2f),
    .D(_00_[4]),
    .Q(data_out0[4])
  );
  (* src = "etapa_flops_synth.v:14" *)
  DFF _63_ (
    .C(clk_2f),
    .D(_00_[5]),
    .Q(data_out0[5])
  );
  (* src = "etapa_flops_synth.v:14" *)
  DFF _64_ (
    .C(clk_2f),
    .D(_00_[6]),
    .Q(data_out0[6])
  );
  (* src = "etapa_flops_synth.v:14" *)
  DFF _65_ (
    .C(clk_2f),
    .D(_00_[7]),
    .Q(data_out0[7])
  );
  (* src = "etapa_flops_synth.v:14" *)
  DFF _66_ (
    .C(clk_2f),
    .D(_01_[0]),
    .Q(data_out1[0])
  );
  (* src = "etapa_flops_synth.v:14" *)
  DFF _67_ (
    .C(clk_2f),
    .D(_01_[1]),
    .Q(data_out1[1])
  );
  (* src = "etapa_flops_synth.v:14" *)
  DFF _68_ (
    .C(clk_2f),
    .D(_01_[2]),
    .Q(data_out1[2])
  );
  (* src = "etapa_flops_synth.v:14" *)
  DFF _69_ (
    .C(clk_2f),
    .D(_01_[3]),
    .Q(data_out1[3])
  );
  (* src = "etapa_flops_synth.v:14" *)
  DFF _70_ (
    .C(clk_2f),
    .D(_01_[4]),
    .Q(data_out1[4])
  );
  (* src = "etapa_flops_synth.v:14" *)
  DFF _71_ (
    .C(clk_2f),
    .D(_01_[5]),
    .Q(data_out1[5])
  );
  (* src = "etapa_flops_synth.v:14" *)
  DFF _72_ (
    .C(clk_2f),
    .D(_01_[6]),
    .Q(data_out1[6])
  );
  (* src = "etapa_flops_synth.v:14" *)
  DFF _73_ (
    .C(clk_2f),
    .D(_01_[7]),
    .Q(data_out1[7])
  );
  (* src = "etapa_flops_synth.v:14" *)
  DFF _74_ (
    .C(clk_2f),
    .D(_02_),
    .Q(valid_out0)
  );
  (* src = "etapa_flops_synth.v:14" *)
  DFF _75_ (
    .C(clk_2f),
    .D(_03_),
    .Q(valid_out1)
  );
endmodule

(* src = "mux_synth.v:1" *)
module mux_synth(clk_2f, reset, data_out, data_in0, data_in1, valid_in0, valid_in1, valid_out);
  (* src = "mux_synth.v:13" *)
  wire [7:0] _000_;
  (* src = "mux_synth.v:13" *)
  wire _001_;
  (* src = "mux_synth.v:13" *)
  wire _002_;
  (* src = "mux_synth.v:13" *)
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  (* src = "mux_synth.v:2" *)
  input clk_2f;
  (* src = "mux_synth.v:5" *)
  input [7:0] data_in0;
  (* src = "mux_synth.v:6" *)
  input [7:0] data_in1;
  (* src = "mux_synth.v:4" *)
  output [7:0] data_out;
  (* src = "mux_synth.v:3" *)
  input reset;
  (* src = "mux_synth.v:11" *)
  wire selector;
  (* src = "mux_synth.v:11" *)
  wire selector2;
  (* src = "mux_synth.v:7" *)
  input valid_in0;
  (* src = "mux_synth.v:8" *)
  input valid_in1;
  (* src = "mux_synth.v:9" *)
  output valid_out;
  NOT _143_ (
    .A(valid_in1),
    .Y(_087_)
  );
  NOT _144_ (
    .A(valid_in0),
    .Y(_088_)
  );
  NOT _145_ (
    .A(data_in0[0]),
    .Y(_089_)
  );
  NOT _146_ (
    .A(data_in1[0]),
    .Y(_090_)
  );
  NOT _147_ (
    .A(data_in0[1]),
    .Y(_091_)
  );
  NOT _148_ (
    .A(data_in1[1]),
    .Y(_092_)
  );
  NOT _149_ (
    .A(data_in0[2]),
    .Y(_093_)
  );
  NOT _150_ (
    .A(data_in1[2]),
    .Y(_094_)
  );
  NOT _151_ (
    .A(data_in0[3]),
    .Y(_095_)
  );
  NOT _152_ (
    .A(data_in1[3]),
    .Y(_096_)
  );
  NOT _153_ (
    .A(data_in0[4]),
    .Y(_097_)
  );
  NOT _154_ (
    .A(data_in1[4]),
    .Y(_098_)
  );
  NOT _155_ (
    .A(data_in0[5]),
    .Y(_099_)
  );
  NOT _156_ (
    .A(data_in1[5]),
    .Y(_100_)
  );
  NOT _157_ (
    .A(data_in0[6]),
    .Y(_101_)
  );
  NOT _158_ (
    .A(data_in1[6]),
    .Y(_102_)
  );
  NOT _159_ (
    .A(data_in0[7]),
    .Y(_103_)
  );
  NOT _160_ (
    .A(data_in1[7]),
    .Y(_104_)
  );
  NOT _161_ (
    .A(reset),
    .Y(_105_)
  );
  NOR _162_ (
    .A(valid_in1),
    .B(valid_in0),
    .Y(_106_)
  );
  NOR _163_ (
    .A(_105_),
    .B(_106_),
    .Y(_003_)
  );
  NOT _164_ (
    .A(_003_),
    .Y(_107_)
  );
  NOR _165_ (
    .A(_087_),
    .B(_088_),
    .Y(_108_)
  );
  NAND _166_ (
    .A(valid_in1),
    .B(valid_in0),
    .Y(_109_)
  );
  NAND _167_ (
    .A(valid_in0),
    .B(data_in0[0]),
    .Y(_110_)
  );
  NOR _168_ (
    .A(_087_),
    .B(valid_in0),
    .Y(_111_)
  );
  NOR _169_ (
    .A(data_out[0]),
    .B(_111_),
    .Y(_112_)
  );
  NAND _170_ (
    .A(_090_),
    .B(_111_),
    .Y(_113_)
  );
  NAND _171_ (
    .A(_087_),
    .B(valid_in0),
    .Y(_114_)
  );
  NAND _172_ (
    .A(reset),
    .B(_114_),
    .Y(_115_)
  );
  NAND _173_ (
    .A(_113_),
    .B(_114_),
    .Y(_116_)
  );
  NOR _174_ (
    .A(_112_),
    .B(_116_),
    .Y(_117_)
  );
  NOR _175_ (
    .A(_108_),
    .B(_117_),
    .Y(_118_)
  );
  NAND _176_ (
    .A(_110_),
    .B(_118_),
    .Y(_119_)
  );
  NAND _177_ (
    .A(reset),
    .B(_119_),
    .Y(_120_)
  );
  NOR _178_ (
    .A(valid_out),
    .B(_109_),
    .Y(_121_)
  );
  NOT _179_ (
    .A(_121_),
    .Y(_122_)
  );
  NOR _180_ (
    .A(_107_),
    .B(_121_),
    .Y(_123_)
  );
  NAND _181_ (
    .A(_003_),
    .B(_122_),
    .Y(_124_)
  );
  NOR _182_ (
    .A(selector),
    .B(_111_),
    .Y(_125_)
  );
  NOR _183_ (
    .A(_115_),
    .B(_125_),
    .Y(_126_)
  );
  NAND _184_ (
    .A(_123_),
    .B(_126_),
    .Y(_127_)
  );
  NAND _185_ (
    .A(selector2),
    .B(_124_),
    .Y(_128_)
  );
  NAND _186_ (
    .A(_127_),
    .B(_128_),
    .Y(_129_)
  );
  NOR _187_ (
    .A(_089_),
    .B(_129_),
    .Y(_130_)
  );
  NAND _188_ (
    .A(data_in1[0]),
    .B(_129_),
    .Y(_131_)
  );
  NAND _189_ (
    .A(_108_),
    .B(_131_),
    .Y(_132_)
  );
  NOR _190_ (
    .A(_130_),
    .B(_132_),
    .Y(_133_)
  );
  NOR _191_ (
    .A(_120_),
    .B(_133_),
    .Y(_000_[0])
  );
  NOR _192_ (
    .A(_091_),
    .B(_129_),
    .Y(_134_)
  );
  NAND _193_ (
    .A(data_in1[1]),
    .B(_129_),
    .Y(_135_)
  );
  NAND _194_ (
    .A(_108_),
    .B(_135_),
    .Y(_136_)
  );
  NOR _195_ (
    .A(_134_),
    .B(_136_),
    .Y(_137_)
  );
  NOR _196_ (
    .A(data_out[1]),
    .B(_111_),
    .Y(_138_)
  );
  NAND _197_ (
    .A(_092_),
    .B(_111_),
    .Y(_139_)
  );
  NAND _198_ (
    .A(_114_),
    .B(_139_),
    .Y(_140_)
  );
  NOR _199_ (
    .A(_138_),
    .B(_140_),
    .Y(_141_)
  );
  NAND _200_ (
    .A(valid_in0),
    .B(data_in0[1]),
    .Y(_142_)
  );
  NOR _201_ (
    .A(_108_),
    .B(_141_),
    .Y(_004_)
  );
  NAND _202_ (
    .A(_142_),
    .B(_004_),
    .Y(_005_)
  );
  NAND _203_ (
    .A(reset),
    .B(_005_),
    .Y(_006_)
  );
  NOR _204_ (
    .A(_137_),
    .B(_006_),
    .Y(_000_[1])
  );
  NOR _205_ (
    .A(_093_),
    .B(_129_),
    .Y(_007_)
  );
  NAND _206_ (
    .A(data_in1[2]),
    .B(_129_),
    .Y(_008_)
  );
  NAND _207_ (
    .A(_108_),
    .B(_008_),
    .Y(_009_)
  );
  NOR _208_ (
    .A(_007_),
    .B(_009_),
    .Y(_010_)
  );
  NOR _209_ (
    .A(data_out[2]),
    .B(_111_),
    .Y(_011_)
  );
  NAND _210_ (
    .A(_094_),
    .B(_111_),
    .Y(_012_)
  );
  NAND _211_ (
    .A(_114_),
    .B(_012_),
    .Y(_013_)
  );
  NOR _212_ (
    .A(_011_),
    .B(_013_),
    .Y(_014_)
  );
  NAND _213_ (
    .A(valid_in0),
    .B(data_in0[2]),
    .Y(_015_)
  );
  NOR _214_ (
    .A(_108_),
    .B(_014_),
    .Y(_016_)
  );
  NAND _215_ (
    .A(_015_),
    .B(_016_),
    .Y(_017_)
  );
  NAND _216_ (
    .A(reset),
    .B(_017_),
    .Y(_018_)
  );
  NOR _217_ (
    .A(_010_),
    .B(_018_),
    .Y(_000_[2])
  );
  NAND _218_ (
    .A(valid_in0),
    .B(data_in0[3]),
    .Y(_019_)
  );
  NOR _219_ (
    .A(data_out[3]),
    .B(_111_),
    .Y(_020_)
  );
  NAND _220_ (
    .A(_096_),
    .B(_111_),
    .Y(_021_)
  );
  NAND _221_ (
    .A(_114_),
    .B(_021_),
    .Y(_022_)
  );
  NOR _222_ (
    .A(_020_),
    .B(_022_),
    .Y(_023_)
  );
  NOR _223_ (
    .A(_108_),
    .B(_023_),
    .Y(_024_)
  );
  NAND _224_ (
    .A(_019_),
    .B(_024_),
    .Y(_025_)
  );
  NAND _225_ (
    .A(reset),
    .B(_025_),
    .Y(_026_)
  );
  NOR _226_ (
    .A(_095_),
    .B(_129_),
    .Y(_027_)
  );
  NAND _227_ (
    .A(data_in1[3]),
    .B(_129_),
    .Y(_028_)
  );
  NAND _228_ (
    .A(_108_),
    .B(_028_),
    .Y(_029_)
  );
  NOR _229_ (
    .A(_027_),
    .B(_029_),
    .Y(_030_)
  );
  NOR _230_ (
    .A(_026_),
    .B(_030_),
    .Y(_000_[3])
  );
  NOR _231_ (
    .A(_097_),
    .B(_129_),
    .Y(_031_)
  );
  NAND _232_ (
    .A(data_in1[4]),
    .B(_129_),
    .Y(_032_)
  );
  NAND _233_ (
    .A(_108_),
    .B(_032_),
    .Y(_033_)
  );
  NOR _234_ (
    .A(_031_),
    .B(_033_),
    .Y(_034_)
  );
  NOR _235_ (
    .A(data_out[4]),
    .B(_111_),
    .Y(_035_)
  );
  NAND _236_ (
    .A(_098_),
    .B(_111_),
    .Y(_036_)
  );
  NAND _237_ (
    .A(_114_),
    .B(_036_),
    .Y(_037_)
  );
  NOR _238_ (
    .A(_035_),
    .B(_037_),
    .Y(_038_)
  );
  NAND _239_ (
    .A(valid_in0),
    .B(data_in0[4]),
    .Y(_039_)
  );
  NOR _240_ (
    .A(_108_),
    .B(_038_),
    .Y(_040_)
  );
  NAND _241_ (
    .A(_039_),
    .B(_040_),
    .Y(_041_)
  );
  NAND _242_ (
    .A(reset),
    .B(_041_),
    .Y(_042_)
  );
  NOR _243_ (
    .A(_034_),
    .B(_042_),
    .Y(_000_[4])
  );
  NAND _244_ (
    .A(valid_in0),
    .B(data_in0[5]),
    .Y(_043_)
  );
  NOR _245_ (
    .A(data_out[5]),
    .B(_111_),
    .Y(_044_)
  );
  NAND _246_ (
    .A(_100_),
    .B(_111_),
    .Y(_045_)
  );
  NAND _247_ (
    .A(_114_),
    .B(_045_),
    .Y(_046_)
  );
  NOR _248_ (
    .A(_044_),
    .B(_046_),
    .Y(_047_)
  );
  NOR _249_ (
    .A(_108_),
    .B(_047_),
    .Y(_048_)
  );
  NAND _250_ (
    .A(_043_),
    .B(_048_),
    .Y(_049_)
  );
  NAND _251_ (
    .A(reset),
    .B(_049_),
    .Y(_050_)
  );
  NOR _252_ (
    .A(_099_),
    .B(_129_),
    .Y(_051_)
  );
  NAND _253_ (
    .A(data_in1[5]),
    .B(_129_),
    .Y(_052_)
  );
  NAND _254_ (
    .A(_108_),
    .B(_052_),
    .Y(_053_)
  );
  NOR _255_ (
    .A(_051_),
    .B(_053_),
    .Y(_054_)
  );
  NOR _256_ (
    .A(_050_),
    .B(_054_),
    .Y(_000_[5])
  );
  NOR _257_ (
    .A(_101_),
    .B(_129_),
    .Y(_055_)
  );
  NAND _258_ (
    .A(data_in1[6]),
    .B(_129_),
    .Y(_056_)
  );
  NAND _259_ (
    .A(_108_),
    .B(_056_),
    .Y(_057_)
  );
  NOR _260_ (
    .A(_055_),
    .B(_057_),
    .Y(_058_)
  );
  NOR _261_ (
    .A(data_out[6]),
    .B(_111_),
    .Y(_059_)
  );
  NAND _262_ (
    .A(_102_),
    .B(_111_),
    .Y(_060_)
  );
  NAND _263_ (
    .A(_114_),
    .B(_060_),
    .Y(_061_)
  );
  NOR _264_ (
    .A(_059_),
    .B(_061_),
    .Y(_062_)
  );
  NAND _265_ (
    .A(valid_in0),
    .B(data_in0[6]),
    .Y(_063_)
  );
  NOR _266_ (
    .A(_108_),
    .B(_062_),
    .Y(_064_)
  );
  NAND _267_ (
    .A(_063_),
    .B(_064_),
    .Y(_065_)
  );
  NAND _268_ (
    .A(reset),
    .B(_065_),
    .Y(_066_)
  );
  NOR _269_ (
    .A(_058_),
    .B(_066_),
    .Y(_000_[6])
  );
  NOR _270_ (
    .A(_103_),
    .B(_129_),
    .Y(_067_)
  );
  NAND _271_ (
    .A(data_in1[7]),
    .B(_129_),
    .Y(_068_)
  );
  NAND _272_ (
    .A(_108_),
    .B(_068_),
    .Y(_069_)
  );
  NOR _273_ (
    .A(_067_),
    .B(_069_),
    .Y(_070_)
  );
  NOR _274_ (
    .A(data_out[7]),
    .B(_111_),
    .Y(_071_)
  );
  NAND _275_ (
    .A(_104_),
    .B(_111_),
    .Y(_072_)
  );
  NAND _276_ (
    .A(_114_),
    .B(_072_),
    .Y(_073_)
  );
  NOR _277_ (
    .A(_071_),
    .B(_073_),
    .Y(_074_)
  );
  NAND _278_ (
    .A(valid_in0),
    .B(data_in0[7]),
    .Y(_075_)
  );
  NOR _279_ (
    .A(_108_),
    .B(_074_),
    .Y(_076_)
  );
  NAND _280_ (
    .A(_075_),
    .B(_076_),
    .Y(_077_)
  );
  NAND _281_ (
    .A(reset),
    .B(_077_),
    .Y(_078_)
  );
  NOR _282_ (
    .A(_070_),
    .B(_078_),
    .Y(_000_[7])
  );
  NOR _283_ (
    .A(_109_),
    .B(_123_),
    .Y(_079_)
  );
  NOT _284_ (
    .A(_079_),
    .Y(_080_)
  );
  NAND _285_ (
    .A(selector2),
    .B(_079_),
    .Y(_081_)
  );
  NAND _286_ (
    .A(_126_),
    .B(_080_),
    .Y(_082_)
  );
  NAND _287_ (
    .A(_081_),
    .B(_082_),
    .Y(_083_)
  );
  NAND _288_ (
    .A(reset),
    .B(_083_),
    .Y(_084_)
  );
  NOT _289_ (
    .A(_084_),
    .Y(_002_)
  );
  NOR _290_ (
    .A(selector2),
    .B(_079_),
    .Y(_085_)
  );
  NAND _291_ (
    .A(reset),
    .B(_081_),
    .Y(_086_)
  );
  NOR _292_ (
    .A(_085_),
    .B(_086_),
    .Y(_001_)
  );
  (* src = "mux_synth.v:13" *)
  DFF _293_ (
    .C(clk_2f),
    .D(_000_[0]),
    .Q(data_out[0])
  );
  (* src = "mux_synth.v:13" *)
  DFF _294_ (
    .C(clk_2f),
    .D(_000_[1]),
    .Q(data_out[1])
  );
  (* src = "mux_synth.v:13" *)
  DFF _295_ (
    .C(clk_2f),
    .D(_000_[2]),
    .Q(data_out[2])
  );
  (* src = "mux_synth.v:13" *)
  DFF _296_ (
    .C(clk_2f),
    .D(_000_[3]),
    .Q(data_out[3])
  );
  (* src = "mux_synth.v:13" *)
  DFF _297_ (
    .C(clk_2f),
    .D(_000_[4]),
    .Q(data_out[4])
  );
  (* src = "mux_synth.v:13" *)
  DFF _298_ (
    .C(clk_2f),
    .D(_000_[5]),
    .Q(data_out[5])
  );
  (* src = "mux_synth.v:13" *)
  DFF _299_ (
    .C(clk_2f),
    .D(_000_[6]),
    .Q(data_out[6])
  );
  (* src = "mux_synth.v:13" *)
  DFF _300_ (
    .C(clk_2f),
    .D(_000_[7]),
    .Q(data_out[7])
  );
  (* src = "mux_synth.v:13" *)
  DFF _301_ (
    .C(clk_2f),
    .D(_003_),
    .Q(valid_out)
  );
  (* src = "mux_synth.v:13" *)
  DFF _302_ (
    .C(clk_2f),
    .D(_002_),
    .Q(selector)
  );
  (* src = "mux_synth.v:13" *)
  DFF _303_ (
    .C(clk_2f),
    .D(_001_),
    .Q(selector2)
  );
endmodule

(* top =  1  *)
(* src = "synth.v:7" *)
module synth(clk_2f, clk_8f, clk_f, reset, data_in0, data_in1, valid_in0, valid_in1, data2send0_synth, data2send1_synth, data_outS0_synth, data_outS1_synth);
  (* src = "synth.v:37" *)
  wire FPS;
  (* src = "synth.v:8" *)
  input clk_2f;
  (* src = "synth.v:9" *)
  input clk_8f;
  (* src = "synth.v:10" *)
  input clk_f;
  (* src = "synth.v:27" *)
  wire [7:0] d_out;
  (* src = "synth.v:32" *)
  wire [7:0] d_out2;
  (* src = "synth.v:16" *)
  output [7:0] data2send0_synth;
  (* src = "synth.v:17" *)
  output [7:0] data2send1_synth;
  (* src = "synth.v:12" *)
  input [7:0] data_in0;
  (* src = "synth.v:13" *)
  input [7:0] data_in1;
  (* src = "synth.v:18" *)
  output data_outS0_synth;
  (* src = "synth.v:19" *)
  output data_outS1_synth;
  (* src = "synth.v:36" *)
  wire [7:0] dataoutFPS;
  (* src = "synth.v:28" *)
  wire [7:0] in0;
  (* src = "synth.v:29" *)
  wire [7:0] in1;
  (* src = "synth.v:30" *)
  wire [7:0] lane0;
  (* src = "synth.v:31" *)
  wire [7:0] lane1;
  (* src = "synth.v:11" *)
  input reset;
  (* src = "synth.v:43" *)
  wire v_out;
  (* src = "synth.v:43" *)
  wire v_out2;
  (* src = "synth.v:43" *)
  wire valid0;
  (* src = "synth.v:43" *)
  wire valid0bs;
  (* src = "synth.v:43" *)
  wire valid1;
  (* src = "synth.v:43" *)
  wire valid1bs;
  (* src = "synth.v:14" *)
  input valid_in0;
  (* src = "synth.v:15" *)
  input valid_in1;
  (* module_not_derived = 32'd1 *)
  (* src = "synth.v:74" *)
  byte_striping_synth byte_striping_synth1 (
    .clk_2f(clk_2f),
    .clk_f(clk_f),
    .data_in(d_out2),
    .lane_0(lane0),
    .lane_1(lane1),
    .reset(reset),
    .valid_0(valid0bs),
    .valid_1(valid1bs),
    .valid_in(v_out2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "synth.v:127" *)
  etapa2_flops_synth etapa2_flops_synth_ (
    .clk_8f(clk_2f),
    .data_in0(lane1),
    .data_out0(dataoutFPS),
    .reset(reset),
    .valid_in0(valid1bs),
    .valid_out0(FPS)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "synth.v:47" *)
  etapa_flops_synth flops (
    .clk_2f(clk_2f),
    .data_in0(data_in0),
    .data_in1(data_in1),
    .data_out0(in0),
    .data_out1(in1),
    .reset(reset),
    .valid_in0(valid_in0),
    .valid_in1(valid_in1),
    .valid_out0(valid0),
    .valid_out1(valid1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "synth.v:67" *)
  etapa2_flops_synth flops2 (
    .clk_8f(clk_8f),
    .data_in0(d_out),
    .data_out0(d_out2),
    .reset(reset),
    .valid_in0(v_out),
    .valid_out0(v_out2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "synth.v:58" *)
  mux_synth mux_synth1 (
    .clk_2f(clk_2f),
    .data_in0(in0),
    .data_in1(in1),
    .data_out(d_out),
    .reset(reset),
    .valid_in0(valid0),
    .valid_in1(valid1),
    .valid_out(v_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "synth.v:100" *)
  paralelo_serie_synth p2s0 (
    .clk_8f(clk_8f),
    .clk_f(clk_f),
    .data2send(data2send0_synth),
    .data_inP(lane0),
    .data_outS(data_outS0_synth),
    .reset(reset),
    .valid_in(valid0bs)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "synth.v:119" *)
  paralelo_serie_synth p2s1 (
    .clk_8f(clk_8f),
    .clk_f(clk_f),
    .data2send(data2send1_synth),
    .data_inP(dataoutFPS),
    .data_outS(data_outS1_synth),
    .reset(reset),
    .valid_in(FPS)
  );
endmodule
