/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 4.8.4-2ubuntu1~14.04.3 -O2 -fstack-protector -fPIC -Os) */

(* top =  1  *)
(* src = "synth.v:1" *)
module synth(clk_2f, reset, out_synth0, out_synth1, data_in, valid_in, valid_out0_synth, valid_out1_synth);
  (* src = "synth.v:12" *)
  wire [7:0] _000_;
  (* src = "synth.v:12" *)
  wire [7:0] _001_;
  (* src = "synth.v:12" *)
  wire _002_;
  (* src = "synth.v:12" *)
  wire _003_;
  (* src = "synth.v:12" *)
  wire _004_;
  (* src = "synth.v:12" *)
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  (* src = "synth.v:2" *)
  input clk_2f;
  (* src = "synth.v:6" *)
  input [7:0] data_in;
  (* src = "synth.v:4" *)
  output [7:0] out_synth0;
  (* src = "synth.v:5" *)
  output [7:0] out_synth1;
  (* src = "synth.v:11" *)
  wire flag;
  (* src = "synth.v:3" *)
  input reset;
  (* src = "synth.v:11" *)
  wire selector;
  (* src = "synth.v:7" *)
  input valid_in;
  (* src = "synth.v:8" *)
  output valid_out0_synth;
  (* src = "synth.v:9" *)
  output valid_out1_synth;
  NOT _093_ (
    .A(valid_in),
    .Y(_052_)
  );
  NOT _094_ (
    .A(reset),
    .Y(_053_)
  );
  NOR _095_ (
    .A(_053_),
    .B(_052_),
    .Y(_002_)
  );
  NOT _096_ (
    .A(selector),
    .Y(_054_)
  );
  NAND _097_ (
    .A(_054_),
    .B(valid_in),
    .Y(_055_)
  );
  NOR _098_ (
    .A(_055_),
    .B(flag),
    .Y(_056_)
  );
  NOR _099_ (
    .A(flag),
    .B(_052_),
    .Y(_057_)
  );
  NOR _100_ (
    .A(_057_),
    .B(_054_),
    .Y(_058_)
  );
  NOR _101_ (
    .A(_058_),
    .B(_056_),
    .Y(_059_)
  );
  NOR _102_ (
    .A(_059_),
    .B(_053_),
    .Y(_003_)
  );
  NOR _103_ (
    .A(selector),
    .B(_052_),
    .Y(_060_)
  );
  NAND _104_ (
    .A(_060_),
    .B(flag),
    .Y(_061_)
  );
  NOT _105_ (
    .A(_061_),
    .Y(_062_)
  );
  NAND _106_ (
    .A(selector),
    .B(valid_in),
    .Y(_063_)
  );
  NOT _107_ (
    .A(flag),
    .Y(_064_)
  );
  NOR _108_ (
    .A(valid_out1_synth),
    .B(_064_),
    .Y(_065_)
  );
  NOR _109_ (
    .A(_065_),
    .B(_063_),
    .Y(_066_)
  );
  NOR _110_ (
    .A(_066_),
    .B(_062_),
    .Y(_067_)
  );
  NOR _111_ (
    .A(_067_),
    .B(_053_),
    .Y(_005_)
  );
  NOR _112_ (
    .A(_063_),
    .B(_064_),
    .Y(_068_)
  );
  NOR _113_ (
    .A(valid_out0_synth),
    .B(_064_),
    .Y(_069_)
  );
  NOR _114_ (
    .A(_069_),
    .B(_055_),
    .Y(_070_)
  );
  NOR _115_ (
    .A(_070_),
    .B(_068_),
    .Y(_071_)
  );
  NOR _116_ (
    .A(_071_),
    .B(_053_),
    .Y(_004_)
  );
  NAND _117_ (
    .A(_057_),
    .B(selector),
    .Y(_072_)
  );
  NAND _118_ (
    .A(_061_),
    .B(_072_),
    .Y(_073_)
  );
  NOR _119_ (
    .A(_073_),
    .B(out_synth1[0]),
    .Y(_074_)
  );
  NOT _120_ (
    .A(data_in[0]),
    .Y(_075_)
  );
  NAND _121_ (
    .A(_073_),
    .B(_075_),
    .Y(_076_)
  );
  NAND _122_ (
    .A(_076_),
    .B(reset),
    .Y(_077_)
  );
  NOR _123_ (
    .A(_077_),
    .B(_074_),
    .Y(_001_[0])
  );
  NOR _124_ (
    .A(_073_),
    .B(out_synth1[1]),
    .Y(_078_)
  );
  NOT _125_ (
    .A(data_in[1]),
    .Y(_079_)
  );
  NAND _126_ (
    .A(_073_),
    .B(_079_),
    .Y(_080_)
  );
  NAND _127_ (
    .A(_080_),
    .B(reset),
    .Y(_081_)
  );
  NOR _128_ (
    .A(_081_),
    .B(_078_),
    .Y(_001_[1])
  );
  NOR _129_ (
    .A(_073_),
    .B(out_synth1[2]),
    .Y(_082_)
  );
  NOT _130_ (
    .A(data_in[2]),
    .Y(_083_)
  );
  NAND _131_ (
    .A(_073_),
    .B(_083_),
    .Y(_084_)
  );
  NAND _132_ (
    .A(_084_),
    .B(reset),
    .Y(_085_)
  );
  NOR _133_ (
    .A(_085_),
    .B(_082_),
    .Y(_001_[2])
  );
  NOR _134_ (
    .A(_073_),
    .B(out_synth1[3]),
    .Y(_086_)
  );
  NOT _135_ (
    .A(data_in[3]),
    .Y(_087_)
  );
  NAND _136_ (
    .A(_073_),
    .B(_087_),
    .Y(_088_)
  );
  NAND _137_ (
    .A(_088_),
    .B(reset),
    .Y(_089_)
  );
  NOR _138_ (
    .A(_089_),
    .B(_086_),
    .Y(_001_[3])
  );
  NOR _139_ (
    .A(_073_),
    .B(out_synth1[4]),
    .Y(_090_)
  );
  NOT _140_ (
    .A(data_in[4]),
    .Y(_091_)
  );
  NAND _141_ (
    .A(_073_),
    .B(_091_),
    .Y(_092_)
  );
  NAND _142_ (
    .A(_092_),
    .B(reset),
    .Y(_006_)
  );
  NOR _143_ (
    .A(_006_),
    .B(_090_),
    .Y(_001_[4])
  );
  NOR _144_ (
    .A(_073_),
    .B(out_synth1[5]),
    .Y(_007_)
  );
  NOT _145_ (
    .A(data_in[5]),
    .Y(_008_)
  );
  NAND _146_ (
    .A(_073_),
    .B(_008_),
    .Y(_009_)
  );
  NAND _147_ (
    .A(_009_),
    .B(reset),
    .Y(_010_)
  );
  NOR _148_ (
    .A(_010_),
    .B(_007_),
    .Y(_001_[5])
  );
  NOR _149_ (
    .A(_073_),
    .B(out_synth1[6]),
    .Y(_011_)
  );
  NOT _150_ (
    .A(data_in[6]),
    .Y(_012_)
  );
  NAND _151_ (
    .A(_073_),
    .B(_012_),
    .Y(_013_)
  );
  NAND _152_ (
    .A(_013_),
    .B(reset),
    .Y(_014_)
  );
  NOR _153_ (
    .A(_014_),
    .B(_011_),
    .Y(_001_[6])
  );
  NOR _154_ (
    .A(_073_),
    .B(out_synth1[7]),
    .Y(_015_)
  );
  NOT _155_ (
    .A(data_in[7]),
    .Y(_016_)
  );
  NAND _156_ (
    .A(_073_),
    .B(_016_),
    .Y(_017_)
  );
  NAND _157_ (
    .A(_017_),
    .B(reset),
    .Y(_018_)
  );
  NOR _158_ (
    .A(_018_),
    .B(_015_),
    .Y(_001_[7])
  );
  NOR _159_ (
    .A(_068_),
    .B(_056_),
    .Y(_019_)
  );
  NOR _160_ (
    .A(_019_),
    .B(data_in[0]),
    .Y(_020_)
  );
  NOT _161_ (
    .A(out_synth0[0]),
    .Y(_021_)
  );
  NAND _162_ (
    .A(_019_),
    .B(_021_),
    .Y(_022_)
  );
  NAND _163_ (
    .A(_022_),
    .B(reset),
    .Y(_023_)
  );
  NOR _164_ (
    .A(_023_),
    .B(_020_),
    .Y(_000_[0])
  );
  NOR _165_ (
    .A(_019_),
    .B(data_in[1]),
    .Y(_024_)
  );
  NOT _166_ (
    .A(out_synth0[1]),
    .Y(_025_)
  );
  NAND _167_ (
    .A(_019_),
    .B(_025_),
    .Y(_026_)
  );
  NAND _168_ (
    .A(_026_),
    .B(reset),
    .Y(_027_)
  );
  NOR _169_ (
    .A(_027_),
    .B(_024_),
    .Y(_000_[1])
  );
  NOR _170_ (
    .A(_019_),
    .B(data_in[2]),
    .Y(_028_)
  );
  NOT _171_ (
    .A(out_synth0[2]),
    .Y(_029_)
  );
  NAND _172_ (
    .A(_019_),
    .B(_029_),
    .Y(_030_)
  );
  NAND _173_ (
    .A(_030_),
    .B(reset),
    .Y(_031_)
  );
  NOR _174_ (
    .A(_031_),
    .B(_028_),
    .Y(_000_[2])
  );
  NOR _175_ (
    .A(_019_),
    .B(data_in[3]),
    .Y(_032_)
  );
  NOT _176_ (
    .A(out_synth0[3]),
    .Y(_033_)
  );
  NAND _177_ (
    .A(_019_),
    .B(_033_),
    .Y(_034_)
  );
  NAND _178_ (
    .A(_034_),
    .B(reset),
    .Y(_035_)
  );
  NOR _179_ (
    .A(_035_),
    .B(_032_),
    .Y(_000_[3])
  );
  NOR _180_ (
    .A(_019_),
    .B(data_in[4]),
    .Y(_036_)
  );
  NOT _181_ (
    .A(out_synth0[4]),
    .Y(_037_)
  );
  NAND _182_ (
    .A(_019_),
    .B(_037_),
    .Y(_038_)
  );
  NAND _183_ (
    .A(_038_),
    .B(reset),
    .Y(_039_)
  );
  NOR _184_ (
    .A(_039_),
    .B(_036_),
    .Y(_000_[4])
  );
  NOR _185_ (
    .A(_019_),
    .B(data_in[5]),
    .Y(_040_)
  );
  NOT _186_ (
    .A(out_synth0[5]),
    .Y(_041_)
  );
  NAND _187_ (
    .A(_019_),
    .B(_041_),
    .Y(_042_)
  );
  NAND _188_ (
    .A(_042_),
    .B(reset),
    .Y(_043_)
  );
  NOR _189_ (
    .A(_043_),
    .B(_040_),
    .Y(_000_[5])
  );
  NOR _190_ (
    .A(_019_),
    .B(data_in[6]),
    .Y(_044_)
  );
  NOT _191_ (
    .A(out_synth0[6]),
    .Y(_045_)
  );
  NAND _192_ (
    .A(_019_),
    .B(_045_),
    .Y(_046_)
  );
  NAND _193_ (
    .A(_046_),
    .B(reset),
    .Y(_047_)
  );
  NOR _194_ (
    .A(_047_),
    .B(_044_),
    .Y(_000_[6])
  );
  NOR _195_ (
    .A(_019_),
    .B(data_in[7]),
    .Y(_048_)
  );
  NOT _196_ (
    .A(out_synth0[7]),
    .Y(_049_)
  );
  NAND _197_ (
    .A(_019_),
    .B(_049_),
    .Y(_050_)
  );
  NAND _198_ (
    .A(_050_),
    .B(reset),
    .Y(_051_)
  );
  NOR _199_ (
    .A(_051_),
    .B(_048_),
    .Y(_000_[7])
  );
  DFF _200_ (
    .C(clk_2f),
    .D(_000_[0]),
    .Q(out_synth0[0])
  );
  DFF _201_ (
    .C(clk_2f),
    .D(_000_[1]),
    .Q(out_synth0[1])
  );
  DFF _202_ (
    .C(clk_2f),
    .D(_000_[2]),
    .Q(out_synth0[2])
  );
  DFF _203_ (
    .C(clk_2f),
    .D(_000_[3]),
    .Q(out_synth0[3])
  );
  DFF _204_ (
    .C(clk_2f),
    .D(_000_[4]),
    .Q(out_synth0[4])
  );
  DFF _205_ (
    .C(clk_2f),
    .D(_000_[5]),
    .Q(out_synth0[5])
  );
  DFF _206_ (
    .C(clk_2f),
    .D(_000_[6]),
    .Q(out_synth0[6])
  );
  DFF _207_ (
    .C(clk_2f),
    .D(_000_[7]),
    .Q(out_synth0[7])
  );
  DFF _208_ (
    .C(clk_2f),
    .D(_001_[0]),
    .Q(out_synth1[0])
  );
  DFF _209_ (
    .C(clk_2f),
    .D(_001_[1]),
    .Q(out_synth1[1])
  );
  DFF _210_ (
    .C(clk_2f),
    .D(_001_[2]),
    .Q(out_synth1[2])
  );
  DFF _211_ (
    .C(clk_2f),
    .D(_001_[3]),
    .Q(out_synth1[3])
  );
  DFF _212_ (
    .C(clk_2f),
    .D(_001_[4]),
    .Q(out_synth1[4])
  );
  DFF _213_ (
    .C(clk_2f),
    .D(_001_[5]),
    .Q(out_synth1[5])
  );
  DFF _214_ (
    .C(clk_2f),
    .D(_001_[6]),
    .Q(out_synth1[6])
  );
  DFF _215_ (
    .C(clk_2f),
    .D(_001_[7]),
    .Q(out_synth1[7])
  );
  DFF _216_ (
    .C(clk_2f),
    .D(_004_),
    .Q(valid_out0_synth)
  );
  DFF _217_ (
    .C(clk_2f),
    .D(_005_),
    .Q(valid_out1_synth)
  );
  DFF _218_ (
    .C(clk_2f),
    .D(_003_),
    .Q(selector)
  );
  DFF _219_ (
    .C(clk_2f),
    .D(_002_),
    .Q(flag)
  );
endmodule
