/* Generated by Yosys 0.8+463 (git sha1 5772732a, clang 6.0.0-1ubuntu2 -fPIC -Os) */

(* top =  1  *)
(* src = "synth_demux.v:6" *)
module synth_demux(clk_2f, reset, valid_in, out_synth0, out_synth1, valid_out0_synth, valid_out1_synth, data_in);
  (* src = "synth_demux.v:99" *)
  wire _000_;
  (* src = "synth_demux.v:99" *)
  wire _001_;
  (* src = "synth_demux.v:10" *)
  wire _002_;
  (* src = "synth_demux.v:10" *)
  wire _003_;
  (* src = "synth_demux.v:10" *)
  wire _004_;
  (* src = "synth_demux.v:10" *)
  wire _005_;
  (* src = "synth_demux.v:10" *)
  wire _006_;
  (* src = "synth_demux.v:10" *)
  wire _007_;
  (* src = "synth_demux.v:10" *)
  wire _008_;
  (* src = "synth_demux.v:10" *)
  wire _009_;
  (* src = "synth_demux.v:11" *)
  wire _010_;
  (* src = "synth_demux.v:11" *)
  wire _011_;
  (* src = "synth_demux.v:11" *)
  wire _012_;
  (* src = "synth_demux.v:11" *)
  wire _013_;
  (* src = "synth_demux.v:11" *)
  wire _014_;
  (* src = "synth_demux.v:11" *)
  wire _015_;
  (* src = "synth_demux.v:11" *)
  wire _016_;
  (* src = "synth_demux.v:11" *)
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  (* src = "synth_demux.v:12" *)
  wire _058_;
  (* src = "synth_demux.v:13" *)
  wire _059_;
  (* src = "synth_demux.v:7" *)
  input clk_2f;
  (* src = "synth_demux.v:14" *)
  input [7:0] data_in;
  (* src = "synth_demux.v:10" *)
  output [7:0] out_synth0;
  (* src = "synth_demux.v:11" *)
  output [7:0] out_synth1;
  (* src = "synth_demux.v:17" *)
  wire [7:0] data_out_mem0;
  (* src = "synth_demux.v:18" *)
  wire [7:0] data_out_mem1;
  (* src = "synth_demux.v:8" *)
  input reset;
  (* src = "synth_demux.v:16" *)
  (* unused_bits = "0" *)
  wire selector;
  (* src = "synth_demux.v:19" *)
  wire selectorF;
  (* src = "synth_demux.v:9" *)
  input valid_in;
  (* src = "synth_demux.v:12" *)
  output valid_out0_synth;
  (* src = "synth_demux.v:13" *)
  output valid_out1_synth;
  NOT _060_ (
    .A(selectorF),
    .Y(_022_)
  );
  NOT _061_ (
    .A(valid_in),
    .Y(_023_)
  );
  NAND _062_ (
    .A(reset),
    .B(_022_),
    .Y(_024_)
  );
  NOT _063_ (
    .A(_024_),
    .Y(_000_)
  );
  NAND _064_ (
    .A(reset),
    .B(valid_in),
    .Y(_025_)
  );
  NOR _065_ (
    .A(_022_),
    .B(_025_),
    .Y(valid_out1_synth)
  );
  NOT _066_ (
    .A(valid_out1_synth),
    .Y(_026_)
  );
  NAND _067_ (
    .A(reset),
    .B(_023_),
    .Y(_027_)
  );
  NAND _068_ (
    .A(_026_),
    .B(_027_),
    .Y(_028_)
  );
  NAND _069_ (
    .A(data_out_mem0[0]),
    .B(_028_),
    .Y(_029_)
  );
  NOR _070_ (
    .A(selectorF),
    .B(_025_),
    .Y(valid_out0_synth)
  );
  NAND _071_ (
    .A(data_in[0]),
    .B(valid_out0_synth),
    .Y(_030_)
  );
  NAND _072_ (
    .A(_029_),
    .B(_030_),
    .Y(out_synth0[0])
  );
  NAND _073_ (
    .A(data_out_mem0[1]),
    .B(_028_),
    .Y(_031_)
  );
  NAND _074_ (
    .A(data_in[1]),
    .B(valid_out0_synth),
    .Y(_032_)
  );
  NAND _075_ (
    .A(_031_),
    .B(_032_),
    .Y(out_synth0[1])
  );
  NAND _076_ (
    .A(data_out_mem0[2]),
    .B(_028_),
    .Y(_033_)
  );
  NAND _077_ (
    .A(data_in[2]),
    .B(valid_out0_synth),
    .Y(_034_)
  );
  NAND _078_ (
    .A(_033_),
    .B(_034_),
    .Y(out_synth0[2])
  );
  NAND _079_ (
    .A(data_out_mem0[3]),
    .B(_028_),
    .Y(_035_)
  );
  NAND _080_ (
    .A(data_in[3]),
    .B(valid_out0_synth),
    .Y(_036_)
  );
  NAND _081_ (
    .A(_035_),
    .B(_036_),
    .Y(out_synth0[3])
  );
  NAND _082_ (
    .A(data_out_mem0[4]),
    .B(_028_),
    .Y(_037_)
  );
  NAND _083_ (
    .A(data_in[4]),
    .B(valid_out0_synth),
    .Y(_038_)
  );
  NAND _084_ (
    .A(_037_),
    .B(_038_),
    .Y(out_synth0[4])
  );
  NAND _085_ (
    .A(data_out_mem0[5]),
    .B(_028_),
    .Y(_039_)
  );
  NAND _086_ (
    .A(data_in[5]),
    .B(valid_out0_synth),
    .Y(_040_)
  );
  NAND _087_ (
    .A(_039_),
    .B(_040_),
    .Y(out_synth0[5])
  );
  NAND _088_ (
    .A(data_out_mem0[6]),
    .B(_028_),
    .Y(_041_)
  );
  NAND _089_ (
    .A(data_in[6]),
    .B(valid_out0_synth),
    .Y(_042_)
  );
  NAND _090_ (
    .A(_041_),
    .B(_042_),
    .Y(out_synth0[6])
  );
  NAND _091_ (
    .A(data_out_mem0[7]),
    .B(_028_),
    .Y(_043_)
  );
  NAND _092_ (
    .A(data_in[7]),
    .B(valid_out0_synth),
    .Y(_044_)
  );
  NAND _093_ (
    .A(_043_),
    .B(_044_),
    .Y(out_synth0[7])
  );
  NAND _094_ (
    .A(data_in[0]),
    .B(valid_out1_synth),
    .Y(_045_)
  );
  NAND _095_ (
    .A(_024_),
    .B(_027_),
    .Y(_046_)
  );
  NAND _096_ (
    .A(data_out_mem1[0]),
    .B(_046_),
    .Y(_047_)
  );
  NAND _097_ (
    .A(_045_),
    .B(_047_),
    .Y(out_synth1[0])
  );
  NAND _098_ (
    .A(data_in[1]),
    .B(valid_out1_synth),
    .Y(_048_)
  );
  NAND _099_ (
    .A(data_out_mem1[1]),
    .B(_046_),
    .Y(_049_)
  );
  NAND _100_ (
    .A(_048_),
    .B(_049_),
    .Y(out_synth1[1])
  );
  NAND _101_ (
    .A(data_in[2]),
    .B(valid_out1_synth),
    .Y(_050_)
  );
  NAND _102_ (
    .A(data_out_mem1[2]),
    .B(_046_),
    .Y(_051_)
  );
  NAND _103_ (
    .A(_050_),
    .B(_051_),
    .Y(out_synth1[2])
  );
  NAND _104_ (
    .A(data_in[3]),
    .B(valid_out1_synth),
    .Y(_052_)
  );
  NAND _105_ (
    .A(data_out_mem1[3]),
    .B(_046_),
    .Y(_053_)
  );
  NAND _106_ (
    .A(_052_),
    .B(_053_),
    .Y(out_synth1[3])
  );
  NAND _107_ (
    .A(data_in[4]),
    .B(valid_out1_synth),
    .Y(_054_)
  );
  NAND _108_ (
    .A(data_out_mem1[4]),
    .B(_046_),
    .Y(_055_)
  );
  NAND _109_ (
    .A(_054_),
    .B(_055_),
    .Y(out_synth1[4])
  );
  NAND _110_ (
    .A(data_in[5]),
    .B(valid_out1_synth),
    .Y(_056_)
  );
  NAND _111_ (
    .A(data_out_mem1[5]),
    .B(_046_),
    .Y(_057_)
  );
  NAND _112_ (
    .A(_056_),
    .B(_057_),
    .Y(out_synth1[5])
  );
  NAND _113_ (
    .A(data_in[6]),
    .B(valid_out1_synth),
    .Y(_018_)
  );
  NAND _114_ (
    .A(data_out_mem1[6]),
    .B(_046_),
    .Y(_019_)
  );
  NAND _115_ (
    .A(_018_),
    .B(_019_),
    .Y(out_synth1[6])
  );
  NAND _116_ (
    .A(data_in[7]),
    .B(valid_out1_synth),
    .Y(_020_)
  );
  NAND _117_ (
    .A(data_out_mem1[7]),
    .B(_046_),
    .Y(_021_)
  );
  NAND _118_ (
    .A(_020_),
    .B(_021_),
    .Y(out_synth1[7])
  );
  (* src = "synth_demux.v:99" *)
  DFF _119_ (
    .C(valid_in),
    .D(_000_),
    .Q(selectorF)
  );
  (* src = "synth_demux.v:94" *)
  DFF _120_ (
    .C(clk_2f),
    .D(out_synth0[0]),
    .Q(data_out_mem0[0])
  );
  (* src = "synth_demux.v:94" *)
  DFF _121_ (
    .C(clk_2f),
    .D(out_synth0[1]),
    .Q(data_out_mem0[1])
  );
  (* src = "synth_demux.v:94" *)
  DFF _122_ (
    .C(clk_2f),
    .D(out_synth0[2]),
    .Q(data_out_mem0[2])
  );
  (* src = "synth_demux.v:94" *)
  DFF _123_ (
    .C(clk_2f),
    .D(out_synth0[3]),
    .Q(data_out_mem0[3])
  );
  (* src = "synth_demux.v:94" *)
  DFF _124_ (
    .C(clk_2f),
    .D(out_synth0[4]),
    .Q(data_out_mem0[4])
  );
  (* src = "synth_demux.v:94" *)
  DFF _125_ (
    .C(clk_2f),
    .D(out_synth0[5]),
    .Q(data_out_mem0[5])
  );
  (* src = "synth_demux.v:94" *)
  DFF _126_ (
    .C(clk_2f),
    .D(out_synth0[6]),
    .Q(data_out_mem0[6])
  );
  (* src = "synth_demux.v:94" *)
  DFF _127_ (
    .C(clk_2f),
    .D(out_synth0[7]),
    .Q(data_out_mem0[7])
  );
  (* src = "synth_demux.v:94" *)
  DFF _128_ (
    .C(clk_2f),
    .D(out_synth1[0]),
    .Q(data_out_mem1[0])
  );
  (* src = "synth_demux.v:94" *)
  DFF _129_ (
    .C(clk_2f),
    .D(out_synth1[1]),
    .Q(data_out_mem1[1])
  );
  (* src = "synth_demux.v:94" *)
  DFF _130_ (
    .C(clk_2f),
    .D(out_synth1[2]),
    .Q(data_out_mem1[2])
  );
  (* src = "synth_demux.v:94" *)
  DFF _131_ (
    .C(clk_2f),
    .D(out_synth1[3]),
    .Q(data_out_mem1[3])
  );
  (* src = "synth_demux.v:94" *)
  DFF _132_ (
    .C(clk_2f),
    .D(out_synth1[4]),
    .Q(data_out_mem1[4])
  );
  (* src = "synth_demux.v:94" *)
  DFF _133_ (
    .C(clk_2f),
    .D(out_synth1[5]),
    .Q(data_out_mem1[5])
  );
  (* src = "synth_demux.v:94" *)
  DFF _134_ (
    .C(clk_2f),
    .D(out_synth1[6]),
    .Q(data_out_mem1[6])
  );
  (* src = "synth_demux.v:94" *)
  DFF _135_ (
    .C(clk_2f),
    .D(out_synth1[7]),
    .Q(data_out_mem1[7])
  );
  assign _001_ = _000_;
  assign _002_ = out_synth0[0];
  assign _003_ = out_synth0[1];
  assign _004_ = out_synth0[2];
  assign _005_ = out_synth0[3];
  assign _006_ = out_synth0[4];
  assign _007_ = out_synth0[5];
  assign _008_ = out_synth0[6];
  assign _009_ = out_synth0[7];
  assign _058_ = valid_out0_synth;
  assign _010_ = out_synth1[0];
  assign _011_ = out_synth1[1];
  assign _012_ = out_synth1[2];
  assign _013_ = out_synth1[3];
  assign _014_ = out_synth1[4];
  assign _015_ = out_synth1[5];
  assign _016_ = out_synth1[6];
  assign _017_ = out_synth1[7];
  assign _059_ = valid_out1_synth;
endmodule
