/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 4.8.4-2ubuntu1~14.04.3 -O2 -fstack-protector -fPIC -Os) */

(* top =  1  *)
(* src = "synth_demux.v:1" *)
module synth_demux(clk_2f, reset, valid_in, out_synth0, out_synth1, valid_out0_synth, valid_out1_synth, data_in);
  (* src = "synth_demux.v:94" *)
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  (* src = "synth_demux.v:2" *)
  input clk_2f;
  (* src = "synth_demux.v:9" *)
  input [7:0] data_in;
  (* src = "synth_demux.v:5" *)
  output [7:0] out_synth0;
  (* src = "synth_demux.v:6" *)
  output [7:0] out_synth1;
  (* src = "synth_demux.v:12" *)
  wire [7:0] data_out_mem0;
  (* src = "synth_demux.v:13" *)
  wire [7:0] data_out_mem1;
  (* src = "synth_demux.v:3" *)
  input reset;
  (* src = "synth_demux.v:14" *)
  wire selectorF;
  (* src = "synth_demux.v:4" *)
  input valid_in;
  (* src = "synth_demux.v:7" *)
  output valid_out0_synth;
  (* src = "synth_demux.v:8" *)
  output valid_out1_synth;
  NOT _040_ (
    .A(selectorF),
    .Y(_004_)
  );
  NAND _041_ (
    .A(_004_),
    .B(reset),
    .Y(_005_)
  );
  NOT _042_ (
    .A(_005_),
    .Y(_000_)
  );
  NOT _043_ (
    .A(valid_in),
    .Y(_006_)
  );
  NAND _044_ (
    .A(selectorF),
    .B(reset),
    .Y(_007_)
  );
  NOR _045_ (
    .A(_007_),
    .B(_006_),
    .Y(valid_out1_synth)
  );
  NOR _046_ (
    .A(_005_),
    .B(_006_),
    .Y(valid_out0_synth)
  );
  NAND _047_ (
    .A(valid_out1_synth),
    .B(data_in[0]),
    .Y(_008_)
  );
  NAND _048_ (
    .A(_006_),
    .B(reset),
    .Y(_009_)
  );
  NAND _049_ (
    .A(_009_),
    .B(_005_),
    .Y(_010_)
  );
  NAND _050_ (
    .A(_010_),
    .B(data_out_mem1[0]),
    .Y(_011_)
  );
  NAND _051_ (
    .A(_011_),
    .B(_008_),
    .Y(out_synth1[0])
  );
  NAND _052_ (
    .A(valid_out1_synth),
    .B(data_in[1]),
    .Y(_012_)
  );
  NAND _053_ (
    .A(_010_),
    .B(data_out_mem1[1]),
    .Y(_013_)
  );
  NAND _054_ (
    .A(_013_),
    .B(_012_),
    .Y(out_synth1[1])
  );
  NAND _055_ (
    .A(valid_out1_synth),
    .B(data_in[2]),
    .Y(_014_)
  );
  NAND _056_ (
    .A(_010_),
    .B(data_out_mem1[2]),
    .Y(_015_)
  );
  NAND _057_ (
    .A(_015_),
    .B(_014_),
    .Y(out_synth1[2])
  );
  NAND _058_ (
    .A(valid_out1_synth),
    .B(data_in[3]),
    .Y(_016_)
  );
  NAND _059_ (
    .A(_010_),
    .B(data_out_mem1[3]),
    .Y(_017_)
  );
  NAND _060_ (
    .A(_017_),
    .B(_016_),
    .Y(out_synth1[3])
  );
  NAND _061_ (
    .A(valid_out1_synth),
    .B(data_in[4]),
    .Y(_018_)
  );
  NAND _062_ (
    .A(_010_),
    .B(data_out_mem1[4]),
    .Y(_019_)
  );
  NAND _063_ (
    .A(_019_),
    .B(_018_),
    .Y(out_synth1[4])
  );
  NAND _064_ (
    .A(valid_out1_synth),
    .B(data_in[5]),
    .Y(_020_)
  );
  NAND _065_ (
    .A(_010_),
    .B(data_out_mem1[5]),
    .Y(_021_)
  );
  NAND _066_ (
    .A(_021_),
    .B(_020_),
    .Y(out_synth1[5])
  );
  NAND _067_ (
    .A(valid_out1_synth),
    .B(data_in[6]),
    .Y(_022_)
  );
  NAND _068_ (
    .A(_010_),
    .B(data_out_mem1[6]),
    .Y(_023_)
  );
  NAND _069_ (
    .A(_023_),
    .B(_022_),
    .Y(out_synth1[6])
  );
  NAND _070_ (
    .A(valid_out1_synth),
    .B(data_in[7]),
    .Y(_024_)
  );
  NAND _071_ (
    .A(_010_),
    .B(data_out_mem1[7]),
    .Y(_025_)
  );
  NAND _072_ (
    .A(_025_),
    .B(_024_),
    .Y(out_synth1[7])
  );
  NAND _073_ (
    .A(_009_),
    .B(_007_),
    .Y(_026_)
  );
  NAND _074_ (
    .A(_026_),
    .B(data_out_mem0[0]),
    .Y(_027_)
  );
  NAND _075_ (
    .A(valid_out0_synth),
    .B(data_in[0]),
    .Y(_028_)
  );
  NAND _076_ (
    .A(_028_),
    .B(_027_),
    .Y(out_synth0[0])
  );
  NAND _077_ (
    .A(_026_),
    .B(data_out_mem0[1]),
    .Y(_029_)
  );
  NAND _078_ (
    .A(valid_out0_synth),
    .B(data_in[1]),
    .Y(_030_)
  );
  NAND _079_ (
    .A(_030_),
    .B(_029_),
    .Y(out_synth0[1])
  );
  NAND _080_ (
    .A(_026_),
    .B(data_out_mem0[2]),
    .Y(_031_)
  );
  NAND _081_ (
    .A(valid_out0_synth),
    .B(data_in[2]),
    .Y(_032_)
  );
  NAND _082_ (
    .A(_032_),
    .B(_031_),
    .Y(out_synth0[2])
  );
  NAND _083_ (
    .A(_026_),
    .B(data_out_mem0[3]),
    .Y(_033_)
  );
  NAND _084_ (
    .A(valid_out0_synth),
    .B(data_in[3]),
    .Y(_034_)
  );
  NAND _085_ (
    .A(_034_),
    .B(_033_),
    .Y(out_synth0[3])
  );
  NAND _086_ (
    .A(_026_),
    .B(data_out_mem0[4]),
    .Y(_035_)
  );
  NAND _087_ (
    .A(valid_out0_synth),
    .B(data_in[4]),
    .Y(_036_)
  );
  NAND _088_ (
    .A(_036_),
    .B(_035_),
    .Y(out_synth0[4])
  );
  NAND _089_ (
    .A(_026_),
    .B(data_out_mem0[5]),
    .Y(_037_)
  );
  NAND _090_ (
    .A(valid_out0_synth),
    .B(data_in[5]),
    .Y(_038_)
  );
  NAND _091_ (
    .A(_038_),
    .B(_037_),
    .Y(out_synth0[5])
  );
  NAND _092_ (
    .A(_026_),
    .B(data_out_mem0[6]),
    .Y(_039_)
  );
  NAND _093_ (
    .A(valid_out0_synth),
    .B(data_in[6]),
    .Y(_001_)
  );
  NAND _094_ (
    .A(_001_),
    .B(_039_),
    .Y(out_synth0[6])
  );
  NAND _095_ (
    .A(_026_),
    .B(data_out_mem0[7]),
    .Y(_002_)
  );
  NAND _096_ (
    .A(valid_out0_synth),
    .B(data_in[7]),
    .Y(_003_)
  );
  NAND _097_ (
    .A(_003_),
    .B(_002_),
    .Y(out_synth0[7])
  );
  DFF _098_ (
    .C(valid_in),
    .D(_000_),
    .Q(selectorF)
  );
  DFF _099_ (
    .C(clk_2f),
    .D(out_synth0[0]),
    .Q(data_out_mem0[0])
  );
  DFF _100_ (
    .C(clk_2f),
    .D(out_synth0[1]),
    .Q(data_out_mem0[1])
  );
  DFF _101_ (
    .C(clk_2f),
    .D(out_synth0[2]),
    .Q(data_out_mem0[2])
  );
  DFF _102_ (
    .C(clk_2f),
    .D(out_synth0[3]),
    .Q(data_out_mem0[3])
  );
  DFF _103_ (
    .C(clk_2f),
    .D(out_synth0[4]),
    .Q(data_out_mem0[4])
  );
  DFF _104_ (
    .C(clk_2f),
    .D(out_synth0[5]),
    .Q(data_out_mem0[5])
  );
  DFF _105_ (
    .C(clk_2f),
    .D(out_synth0[6]),
    .Q(data_out_mem0[6])
  );
  DFF _106_ (
    .C(clk_2f),
    .D(out_synth0[7]),
    .Q(data_out_mem0[7])
  );
  DFF _107_ (
    .C(clk_2f),
    .D(out_synth1[0]),
    .Q(data_out_mem1[0])
  );
  DFF _108_ (
    .C(clk_2f),
    .D(out_synth1[1]),
    .Q(data_out_mem1[1])
  );
  DFF _109_ (
    .C(clk_2f),
    .D(out_synth1[2]),
    .Q(data_out_mem1[2])
  );
  DFF _110_ (
    .C(clk_2f),
    .D(out_synth1[3]),
    .Q(data_out_mem1[3])
  );
  DFF _111_ (
    .C(clk_2f),
    .D(out_synth1[4]),
    .Q(data_out_mem1[4])
  );
  DFF _112_ (
    .C(clk_2f),
    .D(out_synth1[5]),
    .Q(data_out_mem1[5])
  );
  DFF _113_ (
    .C(clk_2f),
    .D(out_synth1[6]),
    .Q(data_out_mem1[6])
  );
  DFF _114_ (
    .C(clk_2f),
    .D(out_synth1[7]),
    .Q(data_out_mem1[7])
  );
endmodule
