/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 4.8.4-2ubuntu1~14.04.3 -O2 -fstack-protector -fPIC -Os) */

(* top =  1  *)
(* src = "synth.v:1" *)
module synth(clk, rst, read_rq, write_rq, w_address, r_address, write_data, read_data_synth);
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  (* src = "synth.v:2" *)
  input clk;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_d[0] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_d[10] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_d[11] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_d[12] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_d[13] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_d[14] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_d[15] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_d[1] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_d[2] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_d[3] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_d[4] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_d[5] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_d[6] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_d[7] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_d[8] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_d[9] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_q[0] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_q[10] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_q[11] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_q[12] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_q[13] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_q[14] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_q[15] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_q[1] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_q[2] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_q[3] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_q[4] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_q[5] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_q[6] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_q[7] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_q[8] ;
  (* src = "synth.v:1" *)
  wire [4:0] \synthory_ram_q[9] ;
  (* src = "synth.v:7" *)
  input [3:0] r_address;
  (* src = "synth.v:9" *)
  output [4:0] read_data_synth;
  (* src = "synth.v:4" *)
  input read_rq;
  (* src = "synth.v:3" *)
  input rst;
  (* src = "synth.v:6" *)
  input [3:0] w_address;
  (* src = "synth.v:8" *)
  input [4:0] write_data;
  (* src = "synth.v:5" *)
  input write_rq;
  NOT _0471_ (
    .A(rst),
    .Y(_0000_)
  );
  NOR _0472_ (
    .A(r_address[1]),
    .B(r_address[0]),
    .Y(_0001_)
  );
  NOR _0473_ (
    .A(r_address[3]),
    .B(r_address[2]),
    .Y(_0002_)
  );
  NAND _0474_ (
    .A(_0002_),
    .B(_0001_),
    .Y(_0003_)
  );
  NOR _0475_ (
    .A(_0003_),
    .B(\synthory_ram_q[0] [0]),
    .Y(_0004_)
  );
  NOT _0476_ (
    .A(r_address[3]),
    .Y(_0005_)
  );
  NAND _0477_ (
    .A(_0005_),
    .B(r_address[2]),
    .Y(_0006_)
  );
  NOT _0478_ (
    .A(r_address[0]),
    .Y(_0007_)
  );
  NAND _0479_ (
    .A(r_address[1]),
    .B(_0007_),
    .Y(_0008_)
  );
  NOR _0480_ (
    .A(_0008_),
    .B(_0006_),
    .Y(_0009_)
  );
  NAND _0481_ (
    .A(_0009_),
    .B(\synthory_ram_q[6] [0]),
    .Y(_0010_)
  );
  NAND _0482_ (
    .A(_0010_),
    .B(_0003_),
    .Y(_0011_)
  );
  NOT _0483_ (
    .A(r_address[2]),
    .Y(_0012_)
  );
  NAND _0484_ (
    .A(r_address[3]),
    .B(_0012_),
    .Y(_0013_)
  );
  NOT _0485_ (
    .A(r_address[1]),
    .Y(_0014_)
  );
  NAND _0486_ (
    .A(_0014_),
    .B(r_address[0]),
    .Y(_0015_)
  );
  NOR _0487_ (
    .A(_0015_),
    .B(_0013_),
    .Y(_0016_)
  );
  NAND _0488_ (
    .A(_0016_),
    .B(\synthory_ram_q[9] [0]),
    .Y(_0017_)
  );
  NOR _0489_ (
    .A(_0015_),
    .B(_0006_),
    .Y(_0018_)
  );
  NAND _0490_ (
    .A(_0018_),
    .B(\synthory_ram_q[5] [0]),
    .Y(_0019_)
  );
  NAND _0491_ (
    .A(_0019_),
    .B(_0017_),
    .Y(_0020_)
  );
  NOR _0492_ (
    .A(_0020_),
    .B(_0011_),
    .Y(_0021_)
  );
  NAND _0493_ (
    .A(r_address[1]),
    .B(r_address[0]),
    .Y(_0022_)
  );
  NAND _0494_ (
    .A(r_address[3]),
    .B(r_address[2]),
    .Y(_0023_)
  );
  NOR _0495_ (
    .A(_0023_),
    .B(_0022_),
    .Y(_0024_)
  );
  NAND _0496_ (
    .A(_0024_),
    .B(\synthory_ram_q[15] [0]),
    .Y(_0025_)
  );
  NAND _0497_ (
    .A(_0014_),
    .B(_0007_),
    .Y(_0026_)
  );
  NOR _0498_ (
    .A(_0023_),
    .B(_0026_),
    .Y(_0027_)
  );
  NAND _0499_ (
    .A(_0027_),
    .B(\synthory_ram_q[12] [0]),
    .Y(_0028_)
  );
  NAND _0500_ (
    .A(_0028_),
    .B(_0025_),
    .Y(_0029_)
  );
  NOR _0501_ (
    .A(_0023_),
    .B(_0008_),
    .Y(_0030_)
  );
  NAND _0502_ (
    .A(_0030_),
    .B(\synthory_ram_q[14] [0]),
    .Y(_0031_)
  );
  NOR _0503_ (
    .A(_0013_),
    .B(_0026_),
    .Y(_0032_)
  );
  NAND _0504_ (
    .A(_0032_),
    .B(\synthory_ram_q[8] [0]),
    .Y(_0033_)
  );
  NAND _0505_ (
    .A(_0033_),
    .B(_0031_),
    .Y(_0034_)
  );
  NOR _0506_ (
    .A(_0034_),
    .B(_0029_),
    .Y(_0035_)
  );
  NAND _0507_ (
    .A(_0035_),
    .B(_0021_),
    .Y(_0036_)
  );
  NAND _0508_ (
    .A(_0005_),
    .B(_0012_),
    .Y(_0037_)
  );
  NOR _0509_ (
    .A(_0008_),
    .B(_0037_),
    .Y(_0038_)
  );
  NAND _0510_ (
    .A(_0038_),
    .B(\synthory_ram_q[2] [0]),
    .Y(_0039_)
  );
  NOR _0511_ (
    .A(_0013_),
    .B(_0008_),
    .Y(_0040_)
  );
  NAND _0512_ (
    .A(_0040_),
    .B(\synthory_ram_q[10] [0]),
    .Y(_0041_)
  );
  NAND _0513_ (
    .A(_0041_),
    .B(_0039_),
    .Y(_0042_)
  );
  NOR _0514_ (
    .A(_0022_),
    .B(_0006_),
    .Y(_0043_)
  );
  NAND _0515_ (
    .A(_0043_),
    .B(\synthory_ram_q[7] [0]),
    .Y(_0044_)
  );
  NOR _0516_ (
    .A(_0022_),
    .B(_0037_),
    .Y(_0045_)
  );
  NAND _0517_ (
    .A(_0045_),
    .B(\synthory_ram_q[3] [0]),
    .Y(_0046_)
  );
  NAND _0518_ (
    .A(_0046_),
    .B(_0044_),
    .Y(_0047_)
  );
  NOR _0519_ (
    .A(_0047_),
    .B(_0042_),
    .Y(_0048_)
  );
  NOR _0520_ (
    .A(_0015_),
    .B(_0037_),
    .Y(_0049_)
  );
  NAND _0521_ (
    .A(_0049_),
    .B(\synthory_ram_q[1] [0]),
    .Y(_0050_)
  );
  NOR _0522_ (
    .A(_0006_),
    .B(_0026_),
    .Y(_0051_)
  );
  NAND _0523_ (
    .A(_0051_),
    .B(\synthory_ram_q[4] [0]),
    .Y(_0052_)
  );
  NAND _0524_ (
    .A(_0052_),
    .B(_0050_),
    .Y(_0053_)
  );
  NOR _0525_ (
    .A(_0022_),
    .B(_0013_),
    .Y(_0054_)
  );
  NAND _0526_ (
    .A(_0054_),
    .B(\synthory_ram_q[11] [0]),
    .Y(_0055_)
  );
  NOR _0527_ (
    .A(_0023_),
    .B(_0015_),
    .Y(_0056_)
  );
  NAND _0528_ (
    .A(_0056_),
    .B(\synthory_ram_q[13] [0]),
    .Y(_0057_)
  );
  NAND _0529_ (
    .A(_0057_),
    .B(_0055_),
    .Y(_0058_)
  );
  NOR _0530_ (
    .A(_0058_),
    .B(_0053_),
    .Y(_0059_)
  );
  NAND _0531_ (
    .A(_0059_),
    .B(_0048_),
    .Y(_0060_)
  );
  NOR _0532_ (
    .A(_0060_),
    .B(_0036_),
    .Y(_0061_)
  );
  NOR _0533_ (
    .A(_0061_),
    .B(_0004_),
    .Y(read_data_synth[0])
  );
  NOR _0534_ (
    .A(_0003_),
    .B(\synthory_ram_q[0] [1]),
    .Y(_0062_)
  );
  NAND _0535_ (
    .A(_0030_),
    .B(\synthory_ram_q[14] [1]),
    .Y(_0063_)
  );
  NAND _0536_ (
    .A(_0051_),
    .B(\synthory_ram_q[4] [1]),
    .Y(_0064_)
  );
  NAND _0537_ (
    .A(_0064_),
    .B(_0063_),
    .Y(_0065_)
  );
  NAND _0538_ (
    .A(_0016_),
    .B(\synthory_ram_q[9] [1]),
    .Y(_0066_)
  );
  NAND _0539_ (
    .A(_0054_),
    .B(\synthory_ram_q[11] [1]),
    .Y(_0067_)
  );
  NAND _0540_ (
    .A(_0067_),
    .B(_0066_),
    .Y(_0068_)
  );
  NOR _0541_ (
    .A(_0068_),
    .B(_0065_),
    .Y(_0069_)
  );
  NAND _0542_ (
    .A(_0024_),
    .B(\synthory_ram_q[15] [1]),
    .Y(_0070_)
  );
  NAND _0543_ (
    .A(_0056_),
    .B(\synthory_ram_q[13] [1]),
    .Y(_0071_)
  );
  NAND _0544_ (
    .A(_0071_),
    .B(_0070_),
    .Y(_0072_)
  );
  NAND _0545_ (
    .A(_0040_),
    .B(\synthory_ram_q[10] [1]),
    .Y(_0073_)
  );
  NAND _0546_ (
    .A(_0073_),
    .B(_0003_),
    .Y(_0074_)
  );
  NOR _0547_ (
    .A(_0074_),
    .B(_0072_),
    .Y(_0075_)
  );
  NAND _0548_ (
    .A(_0075_),
    .B(_0069_),
    .Y(_0076_)
  );
  NAND _0549_ (
    .A(_0018_),
    .B(\synthory_ram_q[5] [1]),
    .Y(_0077_)
  );
  NAND _0550_ (
    .A(_0045_),
    .B(\synthory_ram_q[3] [1]),
    .Y(_0078_)
  );
  NAND _0551_ (
    .A(_0078_),
    .B(_0077_),
    .Y(_0079_)
  );
  NAND _0552_ (
    .A(_0009_),
    .B(\synthory_ram_q[6] [1]),
    .Y(_0080_)
  );
  NAND _0553_ (
    .A(_0043_),
    .B(\synthory_ram_q[7] [1]),
    .Y(_0081_)
  );
  NAND _0554_ (
    .A(_0081_),
    .B(_0080_),
    .Y(_0082_)
  );
  NOR _0555_ (
    .A(_0082_),
    .B(_0079_),
    .Y(_0083_)
  );
  NAND _0556_ (
    .A(_0032_),
    .B(\synthory_ram_q[8] [1]),
    .Y(_0084_)
  );
  NAND _0557_ (
    .A(_0038_),
    .B(\synthory_ram_q[2] [1]),
    .Y(_0085_)
  );
  NAND _0558_ (
    .A(_0085_),
    .B(_0084_),
    .Y(_0086_)
  );
  NAND _0559_ (
    .A(_0049_),
    .B(\synthory_ram_q[1] [1]),
    .Y(_0087_)
  );
  NAND _0560_ (
    .A(_0027_),
    .B(\synthory_ram_q[12] [1]),
    .Y(_0088_)
  );
  NAND _0561_ (
    .A(_0088_),
    .B(_0087_),
    .Y(_0089_)
  );
  NOR _0562_ (
    .A(_0089_),
    .B(_0086_),
    .Y(_0090_)
  );
  NAND _0563_ (
    .A(_0090_),
    .B(_0083_),
    .Y(_0091_)
  );
  NOR _0564_ (
    .A(_0091_),
    .B(_0076_),
    .Y(_0092_)
  );
  NOR _0565_ (
    .A(_0092_),
    .B(_0062_),
    .Y(read_data_synth[1])
  );
  NOR _0566_ (
    .A(_0003_),
    .B(\synthory_ram_q[0] [2]),
    .Y(_0093_)
  );
  NAND _0567_ (
    .A(_0030_),
    .B(\synthory_ram_q[14] [2]),
    .Y(_0094_)
  );
  NAND _0568_ (
    .A(_0056_),
    .B(\synthory_ram_q[13] [2]),
    .Y(_0095_)
  );
  NAND _0569_ (
    .A(_0095_),
    .B(_0094_),
    .Y(_0096_)
  );
  NAND _0570_ (
    .A(_0032_),
    .B(\synthory_ram_q[8] [2]),
    .Y(_0097_)
  );
  NAND _0571_ (
    .A(_0097_),
    .B(_0003_),
    .Y(_0098_)
  );
  NOR _0572_ (
    .A(_0098_),
    .B(_0096_),
    .Y(_0099_)
  );
  NAND _0573_ (
    .A(_0038_),
    .B(\synthory_ram_q[2] [2]),
    .Y(_0100_)
  );
  NAND _0574_ (
    .A(_0027_),
    .B(\synthory_ram_q[12] [2]),
    .Y(_0101_)
  );
  NAND _0575_ (
    .A(_0101_),
    .B(_0100_),
    .Y(_0102_)
  );
  NAND _0576_ (
    .A(_0040_),
    .B(\synthory_ram_q[10] [2]),
    .Y(_0103_)
  );
  NAND _0577_ (
    .A(_0024_),
    .B(\synthory_ram_q[15] [2]),
    .Y(_0104_)
  );
  NAND _0578_ (
    .A(_0104_),
    .B(_0103_),
    .Y(_0105_)
  );
  NOR _0579_ (
    .A(_0105_),
    .B(_0102_),
    .Y(_0106_)
  );
  NAND _0580_ (
    .A(_0106_),
    .B(_0099_),
    .Y(_0107_)
  );
  NAND _0581_ (
    .A(_0016_),
    .B(\synthory_ram_q[9] [2]),
    .Y(_0108_)
  );
  NAND _0582_ (
    .A(_0018_),
    .B(\synthory_ram_q[5] [2]),
    .Y(_0109_)
  );
  NAND _0583_ (
    .A(_0109_),
    .B(_0108_),
    .Y(_0110_)
  );
  NAND _0584_ (
    .A(_0049_),
    .B(\synthory_ram_q[1] [2]),
    .Y(_0111_)
  );
  NAND _0585_ (
    .A(_0051_),
    .B(\synthory_ram_q[4] [2]),
    .Y(_0112_)
  );
  NAND _0586_ (
    .A(_0112_),
    .B(_0111_),
    .Y(_0113_)
  );
  NOR _0587_ (
    .A(_0113_),
    .B(_0110_),
    .Y(_0114_)
  );
  NAND _0588_ (
    .A(_0045_),
    .B(\synthory_ram_q[3] [2]),
    .Y(_0115_)
  );
  NAND _0589_ (
    .A(_0054_),
    .B(\synthory_ram_q[11] [2]),
    .Y(_0116_)
  );
  NAND _0590_ (
    .A(_0116_),
    .B(_0115_),
    .Y(_0117_)
  );
  NAND _0591_ (
    .A(_0009_),
    .B(\synthory_ram_q[6] [2]),
    .Y(_0118_)
  );
  NAND _0592_ (
    .A(_0043_),
    .B(\synthory_ram_q[7] [2]),
    .Y(_0119_)
  );
  NAND _0593_ (
    .A(_0119_),
    .B(_0118_),
    .Y(_0120_)
  );
  NOR _0594_ (
    .A(_0120_),
    .B(_0117_),
    .Y(_0121_)
  );
  NAND _0595_ (
    .A(_0121_),
    .B(_0114_),
    .Y(_0122_)
  );
  NOR _0596_ (
    .A(_0122_),
    .B(_0107_),
    .Y(_0123_)
  );
  NOR _0597_ (
    .A(_0123_),
    .B(_0093_),
    .Y(read_data_synth[2])
  );
  NOR _0598_ (
    .A(_0003_),
    .B(\synthory_ram_q[0] [3]),
    .Y(_0124_)
  );
  NAND _0599_ (
    .A(_0030_),
    .B(\synthory_ram_q[14] [3]),
    .Y(_0125_)
  );
  NAND _0600_ (
    .A(_0056_),
    .B(\synthory_ram_q[13] [3]),
    .Y(_0126_)
  );
  NAND _0601_ (
    .A(_0126_),
    .B(_0125_),
    .Y(_0127_)
  );
  NAND _0602_ (
    .A(_0032_),
    .B(\synthory_ram_q[8] [3]),
    .Y(_0128_)
  );
  NAND _0603_ (
    .A(_0128_),
    .B(_0003_),
    .Y(_0129_)
  );
  NOR _0604_ (
    .A(_0129_),
    .B(_0127_),
    .Y(_0130_)
  );
  NAND _0605_ (
    .A(_0038_),
    .B(\synthory_ram_q[2] [3]),
    .Y(_0131_)
  );
  NAND _0606_ (
    .A(_0027_),
    .B(\synthory_ram_q[12] [3]),
    .Y(_0132_)
  );
  NAND _0607_ (
    .A(_0132_),
    .B(_0131_),
    .Y(_0133_)
  );
  NAND _0608_ (
    .A(_0040_),
    .B(\synthory_ram_q[10] [3]),
    .Y(_0134_)
  );
  NAND _0609_ (
    .A(_0024_),
    .B(\synthory_ram_q[15] [3]),
    .Y(_0135_)
  );
  NAND _0610_ (
    .A(_0135_),
    .B(_0134_),
    .Y(_0136_)
  );
  NOR _0611_ (
    .A(_0136_),
    .B(_0133_),
    .Y(_0137_)
  );
  NAND _0612_ (
    .A(_0137_),
    .B(_0130_),
    .Y(_0138_)
  );
  NAND _0613_ (
    .A(_0016_),
    .B(\synthory_ram_q[9] [3]),
    .Y(_0139_)
  );
  NAND _0614_ (
    .A(_0018_),
    .B(\synthory_ram_q[5] [3]),
    .Y(_0140_)
  );
  NAND _0615_ (
    .A(_0140_),
    .B(_0139_),
    .Y(_0141_)
  );
  NAND _0616_ (
    .A(_0049_),
    .B(\synthory_ram_q[1] [3]),
    .Y(_0142_)
  );
  NAND _0617_ (
    .A(_0051_),
    .B(\synthory_ram_q[4] [3]),
    .Y(_0143_)
  );
  NAND _0618_ (
    .A(_0143_),
    .B(_0142_),
    .Y(_0144_)
  );
  NOR _0619_ (
    .A(_0144_),
    .B(_0141_),
    .Y(_0145_)
  );
  NAND _0620_ (
    .A(_0045_),
    .B(\synthory_ram_q[3] [3]),
    .Y(_0146_)
  );
  NAND _0621_ (
    .A(_0054_),
    .B(\synthory_ram_q[11] [3]),
    .Y(_0147_)
  );
  NAND _0622_ (
    .A(_0147_),
    .B(_0146_),
    .Y(_0148_)
  );
  NAND _0623_ (
    .A(_0009_),
    .B(\synthory_ram_q[6] [3]),
    .Y(_0149_)
  );
  NAND _0624_ (
    .A(_0043_),
    .B(\synthory_ram_q[7] [3]),
    .Y(_0150_)
  );
  NAND _0625_ (
    .A(_0150_),
    .B(_0149_),
    .Y(_0151_)
  );
  NOR _0626_ (
    .A(_0151_),
    .B(_0148_),
    .Y(_0152_)
  );
  NAND _0627_ (
    .A(_0152_),
    .B(_0145_),
    .Y(_0153_)
  );
  NOR _0628_ (
    .A(_0153_),
    .B(_0138_),
    .Y(_0154_)
  );
  NOR _0629_ (
    .A(_0154_),
    .B(_0124_),
    .Y(read_data_synth[3])
  );
  NOR _0630_ (
    .A(_0003_),
    .B(\synthory_ram_q[0] [4]),
    .Y(_0155_)
  );
  NAND _0631_ (
    .A(_0018_),
    .B(\synthory_ram_q[5] [4]),
    .Y(_0156_)
  );
  NAND _0632_ (
    .A(_0027_),
    .B(\synthory_ram_q[12] [4]),
    .Y(_0157_)
  );
  NAND _0633_ (
    .A(_0157_),
    .B(_0156_),
    .Y(_0158_)
  );
  NAND _0634_ (
    .A(_0009_),
    .B(\synthory_ram_q[6] [4]),
    .Y(_0159_)
  );
  NAND _0635_ (
    .A(_0043_),
    .B(\synthory_ram_q[7] [4]),
    .Y(_0160_)
  );
  NAND _0636_ (
    .A(_0160_),
    .B(_0159_),
    .Y(_0161_)
  );
  NOR _0637_ (
    .A(_0161_),
    .B(_0158_),
    .Y(_0162_)
  );
  NAND _0638_ (
    .A(_0032_),
    .B(\synthory_ram_q[8] [4]),
    .Y(_0163_)
  );
  NAND _0639_ (
    .A(_0163_),
    .B(_0003_),
    .Y(_0164_)
  );
  NAND _0640_ (
    .A(_0054_),
    .B(\synthory_ram_q[11] [4]),
    .Y(_0165_)
  );
  NAND _0641_ (
    .A(_0040_),
    .B(\synthory_ram_q[10] [4]),
    .Y(_0166_)
  );
  NAND _0642_ (
    .A(_0166_),
    .B(_0165_),
    .Y(_0167_)
  );
  NOR _0643_ (
    .A(_0167_),
    .B(_0164_),
    .Y(_0168_)
  );
  NAND _0644_ (
    .A(_0168_),
    .B(_0162_),
    .Y(_0169_)
  );
  NAND _0645_ (
    .A(_0045_),
    .B(\synthory_ram_q[3] [4]),
    .Y(_0170_)
  );
  NAND _0646_ (
    .A(_0056_),
    .B(\synthory_ram_q[13] [4]),
    .Y(_0171_)
  );
  NAND _0647_ (
    .A(_0171_),
    .B(_0170_),
    .Y(_0172_)
  );
  NAND _0648_ (
    .A(_0030_),
    .B(\synthory_ram_q[14] [4]),
    .Y(_0173_)
  );
  NAND _0649_ (
    .A(_0049_),
    .B(\synthory_ram_q[1] [4]),
    .Y(_0174_)
  );
  NAND _0650_ (
    .A(_0174_),
    .B(_0173_),
    .Y(_0175_)
  );
  NOR _0651_ (
    .A(_0175_),
    .B(_0172_),
    .Y(_0176_)
  );
  NAND _0652_ (
    .A(_0016_),
    .B(\synthory_ram_q[9] [4]),
    .Y(_0177_)
  );
  NAND _0653_ (
    .A(_0038_),
    .B(\synthory_ram_q[2] [4]),
    .Y(_0178_)
  );
  NAND _0654_ (
    .A(_0178_),
    .B(_0177_),
    .Y(_0179_)
  );
  NAND _0655_ (
    .A(_0051_),
    .B(\synthory_ram_q[4] [4]),
    .Y(_0180_)
  );
  NAND _0656_ (
    .A(_0024_),
    .B(\synthory_ram_q[15] [4]),
    .Y(_0181_)
  );
  NAND _0657_ (
    .A(_0181_),
    .B(_0180_),
    .Y(_0182_)
  );
  NOR _0658_ (
    .A(_0182_),
    .B(_0179_),
    .Y(_0183_)
  );
  NAND _0659_ (
    .A(_0183_),
    .B(_0176_),
    .Y(_0184_)
  );
  NOR _0660_ (
    .A(_0184_),
    .B(_0169_),
    .Y(_0185_)
  );
  NOR _0661_ (
    .A(_0185_),
    .B(_0155_),
    .Y(read_data_synth[4])
  );
  NOT _0662_ (
    .A(w_address[0]),
    .Y(_0186_)
  );
  NOR _0663_ (
    .A(w_address[1]),
    .B(_0186_),
    .Y(_0187_)
  );
  NOT _0664_ (
    .A(_0187_),
    .Y(_0188_)
  );
  NOR _0665_ (
    .A(w_address[3]),
    .B(w_address[2]),
    .Y(_0189_)
  );
  NOT _0666_ (
    .A(_0189_),
    .Y(_0190_)
  );
  NOR _0667_ (
    .A(_0190_),
    .B(_0188_),
    .Y(_0191_)
  );
  NAND _0668_ (
    .A(_0191_),
    .B(write_data[0]),
    .Y(_0192_)
  );
  NOT _0669_ (
    .A(_0191_),
    .Y(_0193_)
  );
  NAND _0670_ (
    .A(_0193_),
    .B(\synthory_ram_q[1] [0]),
    .Y(_0194_)
  );
  NAND _0671_ (
    .A(_0194_),
    .B(_0192_),
    .Y(\synthory_ram_d[1] [0])
  );
  NAND _0672_ (
    .A(_0191_),
    .B(write_data[1]),
    .Y(_0195_)
  );
  NAND _0673_ (
    .A(_0193_),
    .B(\synthory_ram_q[1] [1]),
    .Y(_0196_)
  );
  NAND _0674_ (
    .A(_0196_),
    .B(_0195_),
    .Y(\synthory_ram_d[1] [1])
  );
  NAND _0675_ (
    .A(_0191_),
    .B(write_data[2]),
    .Y(_0197_)
  );
  NAND _0676_ (
    .A(_0193_),
    .B(\synthory_ram_q[1] [2]),
    .Y(_0198_)
  );
  NAND _0677_ (
    .A(_0198_),
    .B(_0197_),
    .Y(\synthory_ram_d[1] [2])
  );
  NAND _0678_ (
    .A(_0191_),
    .B(write_data[3]),
    .Y(_0199_)
  );
  NAND _0679_ (
    .A(_0193_),
    .B(\synthory_ram_q[1] [3]),
    .Y(_0200_)
  );
  NAND _0680_ (
    .A(_0200_),
    .B(_0199_),
    .Y(\synthory_ram_d[1] [3])
  );
  NAND _0681_ (
    .A(_0191_),
    .B(write_data[4]),
    .Y(_0201_)
  );
  NAND _0682_ (
    .A(_0193_),
    .B(\synthory_ram_q[1] [4]),
    .Y(_0202_)
  );
  NAND _0683_ (
    .A(_0202_),
    .B(_0201_),
    .Y(\synthory_ram_d[1] [4])
  );
  NAND _0684_ (
    .A(w_address[1]),
    .B(_0186_),
    .Y(_0203_)
  );
  NOR _0685_ (
    .A(_0203_),
    .B(_0190_),
    .Y(_0204_)
  );
  NAND _0686_ (
    .A(_0204_),
    .B(write_data[0]),
    .Y(_0205_)
  );
  NOT _0687_ (
    .A(_0204_),
    .Y(_0206_)
  );
  NAND _0688_ (
    .A(_0206_),
    .B(\synthory_ram_q[2] [0]),
    .Y(_0207_)
  );
  NAND _0689_ (
    .A(_0207_),
    .B(_0205_),
    .Y(\synthory_ram_d[2] [0])
  );
  NAND _0690_ (
    .A(_0204_),
    .B(write_data[1]),
    .Y(_0208_)
  );
  NAND _0691_ (
    .A(_0206_),
    .B(\synthory_ram_q[2] [1]),
    .Y(_0209_)
  );
  NAND _0692_ (
    .A(_0209_),
    .B(_0208_),
    .Y(\synthory_ram_d[2] [1])
  );
  NAND _0693_ (
    .A(_0204_),
    .B(write_data[2]),
    .Y(_0210_)
  );
  NAND _0694_ (
    .A(_0206_),
    .B(\synthory_ram_q[2] [2]),
    .Y(_0211_)
  );
  NAND _0695_ (
    .A(_0211_),
    .B(_0210_),
    .Y(\synthory_ram_d[2] [2])
  );
  NAND _0696_ (
    .A(_0204_),
    .B(write_data[3]),
    .Y(_0212_)
  );
  NAND _0697_ (
    .A(_0206_),
    .B(\synthory_ram_q[2] [3]),
    .Y(_0213_)
  );
  NAND _0698_ (
    .A(_0213_),
    .B(_0212_),
    .Y(\synthory_ram_d[2] [3])
  );
  NAND _0699_ (
    .A(_0204_),
    .B(write_data[4]),
    .Y(_0214_)
  );
  NAND _0700_ (
    .A(_0206_),
    .B(\synthory_ram_q[2] [4]),
    .Y(_0215_)
  );
  NAND _0701_ (
    .A(_0215_),
    .B(_0214_),
    .Y(\synthory_ram_d[2] [4])
  );
  NAND _0702_ (
    .A(w_address[1]),
    .B(w_address[0]),
    .Y(_0216_)
  );
  NOR _0703_ (
    .A(_0216_),
    .B(_0190_),
    .Y(_0217_)
  );
  NAND _0704_ (
    .A(_0217_),
    .B(write_data[0]),
    .Y(_0218_)
  );
  NOT _0705_ (
    .A(_0217_),
    .Y(_0219_)
  );
  NAND _0706_ (
    .A(_0219_),
    .B(\synthory_ram_q[3] [0]),
    .Y(_0220_)
  );
  NAND _0707_ (
    .A(_0220_),
    .B(_0218_),
    .Y(\synthory_ram_d[3] [0])
  );
  NAND _0708_ (
    .A(_0217_),
    .B(write_data[1]),
    .Y(_0221_)
  );
  NAND _0709_ (
    .A(_0219_),
    .B(\synthory_ram_q[3] [1]),
    .Y(_0222_)
  );
  NAND _0710_ (
    .A(_0222_),
    .B(_0221_),
    .Y(\synthory_ram_d[3] [1])
  );
  NAND _0711_ (
    .A(_0217_),
    .B(write_data[2]),
    .Y(_0223_)
  );
  NAND _0712_ (
    .A(_0219_),
    .B(\synthory_ram_q[3] [2]),
    .Y(_0224_)
  );
  NAND _0713_ (
    .A(_0224_),
    .B(_0223_),
    .Y(\synthory_ram_d[3] [2])
  );
  NAND _0714_ (
    .A(_0217_),
    .B(write_data[3]),
    .Y(_0225_)
  );
  NAND _0715_ (
    .A(_0219_),
    .B(\synthory_ram_q[3] [3]),
    .Y(_0226_)
  );
  NAND _0716_ (
    .A(_0226_),
    .B(_0225_),
    .Y(\synthory_ram_d[3] [3])
  );
  NAND _0717_ (
    .A(_0217_),
    .B(write_data[4]),
    .Y(_0227_)
  );
  NAND _0718_ (
    .A(_0219_),
    .B(\synthory_ram_q[3] [4]),
    .Y(_0228_)
  );
  NAND _0719_ (
    .A(_0228_),
    .B(_0227_),
    .Y(\synthory_ram_d[3] [4])
  );
  NOR _0720_ (
    .A(w_address[1]),
    .B(w_address[0]),
    .Y(_0229_)
  );
  NOT _0721_ (
    .A(_0229_),
    .Y(_0230_)
  );
  NOT _0722_ (
    .A(w_address[2]),
    .Y(_0231_)
  );
  NOR _0723_ (
    .A(w_address[3]),
    .B(_0231_),
    .Y(_0232_)
  );
  NOT _0724_ (
    .A(_0232_),
    .Y(_0233_)
  );
  NOR _0725_ (
    .A(_0233_),
    .B(_0230_),
    .Y(_0234_)
  );
  NAND _0726_ (
    .A(_0234_),
    .B(write_data[0]),
    .Y(_0235_)
  );
  NOT _0727_ (
    .A(_0234_),
    .Y(_0236_)
  );
  NAND _0728_ (
    .A(_0236_),
    .B(\synthory_ram_q[4] [0]),
    .Y(_0237_)
  );
  NAND _0729_ (
    .A(_0237_),
    .B(_0235_),
    .Y(\synthory_ram_d[4] [0])
  );
  NAND _0730_ (
    .A(_0234_),
    .B(write_data[1]),
    .Y(_0238_)
  );
  NAND _0731_ (
    .A(_0236_),
    .B(\synthory_ram_q[4] [1]),
    .Y(_0239_)
  );
  NAND _0732_ (
    .A(_0239_),
    .B(_0238_),
    .Y(\synthory_ram_d[4] [1])
  );
  NAND _0733_ (
    .A(_0234_),
    .B(write_data[2]),
    .Y(_0240_)
  );
  NAND _0734_ (
    .A(_0236_),
    .B(\synthory_ram_q[4] [2]),
    .Y(_0241_)
  );
  NAND _0735_ (
    .A(_0241_),
    .B(_0240_),
    .Y(\synthory_ram_d[4] [2])
  );
  NAND _0736_ (
    .A(_0234_),
    .B(write_data[3]),
    .Y(_0242_)
  );
  NAND _0737_ (
    .A(_0236_),
    .B(\synthory_ram_q[4] [3]),
    .Y(_0243_)
  );
  NAND _0738_ (
    .A(_0243_),
    .B(_0242_),
    .Y(\synthory_ram_d[4] [3])
  );
  NAND _0739_ (
    .A(_0234_),
    .B(write_data[4]),
    .Y(_0244_)
  );
  NAND _0740_ (
    .A(_0236_),
    .B(\synthory_ram_q[4] [4]),
    .Y(_0245_)
  );
  NAND _0741_ (
    .A(_0245_),
    .B(_0244_),
    .Y(\synthory_ram_d[4] [4])
  );
  NOR _0742_ (
    .A(_0233_),
    .B(_0188_),
    .Y(_0246_)
  );
  NAND _0743_ (
    .A(_0246_),
    .B(write_data[0]),
    .Y(_0247_)
  );
  NOT _0744_ (
    .A(_0246_),
    .Y(_0248_)
  );
  NAND _0745_ (
    .A(_0248_),
    .B(\synthory_ram_q[5] [0]),
    .Y(_0249_)
  );
  NAND _0746_ (
    .A(_0249_),
    .B(_0247_),
    .Y(\synthory_ram_d[5] [0])
  );
  NAND _0747_ (
    .A(_0246_),
    .B(write_data[1]),
    .Y(_0250_)
  );
  NAND _0748_ (
    .A(_0248_),
    .B(\synthory_ram_q[5] [1]),
    .Y(_0251_)
  );
  NAND _0749_ (
    .A(_0251_),
    .B(_0250_),
    .Y(\synthory_ram_d[5] [1])
  );
  NAND _0750_ (
    .A(_0246_),
    .B(write_data[2]),
    .Y(_0252_)
  );
  NAND _0751_ (
    .A(_0248_),
    .B(\synthory_ram_q[5] [2]),
    .Y(_0253_)
  );
  NAND _0752_ (
    .A(_0253_),
    .B(_0252_),
    .Y(\synthory_ram_d[5] [2])
  );
  NAND _0753_ (
    .A(_0246_),
    .B(write_data[3]),
    .Y(_0254_)
  );
  NAND _0754_ (
    .A(_0248_),
    .B(\synthory_ram_q[5] [3]),
    .Y(_0255_)
  );
  NAND _0755_ (
    .A(_0255_),
    .B(_0254_),
    .Y(\synthory_ram_d[5] [3])
  );
  NAND _0756_ (
    .A(_0246_),
    .B(write_data[4]),
    .Y(_0256_)
  );
  NAND _0757_ (
    .A(_0248_),
    .B(\synthory_ram_q[5] [4]),
    .Y(_0257_)
  );
  NAND _0758_ (
    .A(_0257_),
    .B(_0256_),
    .Y(\synthory_ram_d[5] [4])
  );
  NOR _0759_ (
    .A(_0233_),
    .B(_0203_),
    .Y(_0258_)
  );
  NAND _0760_ (
    .A(_0258_),
    .B(write_data[0]),
    .Y(_0259_)
  );
  NOT _0761_ (
    .A(_0258_),
    .Y(_0260_)
  );
  NAND _0762_ (
    .A(_0260_),
    .B(\synthory_ram_q[6] [0]),
    .Y(_0261_)
  );
  NAND _0763_ (
    .A(_0261_),
    .B(_0259_),
    .Y(\synthory_ram_d[6] [0])
  );
  NAND _0764_ (
    .A(_0258_),
    .B(write_data[1]),
    .Y(_0262_)
  );
  NAND _0765_ (
    .A(_0260_),
    .B(\synthory_ram_q[6] [1]),
    .Y(_0263_)
  );
  NAND _0766_ (
    .A(_0263_),
    .B(_0262_),
    .Y(\synthory_ram_d[6] [1])
  );
  NAND _0767_ (
    .A(_0258_),
    .B(write_data[2]),
    .Y(_0264_)
  );
  NAND _0768_ (
    .A(_0260_),
    .B(\synthory_ram_q[6] [2]),
    .Y(_0265_)
  );
  NAND _0769_ (
    .A(_0265_),
    .B(_0264_),
    .Y(\synthory_ram_d[6] [2])
  );
  NAND _0770_ (
    .A(_0258_),
    .B(write_data[3]),
    .Y(_0266_)
  );
  NAND _0771_ (
    .A(_0260_),
    .B(\synthory_ram_q[6] [3]),
    .Y(_0267_)
  );
  NAND _0772_ (
    .A(_0267_),
    .B(_0266_),
    .Y(\synthory_ram_d[6] [3])
  );
  NAND _0773_ (
    .A(_0258_),
    .B(write_data[4]),
    .Y(_0268_)
  );
  NAND _0774_ (
    .A(_0260_),
    .B(\synthory_ram_q[6] [4]),
    .Y(_0269_)
  );
  NAND _0775_ (
    .A(_0269_),
    .B(_0268_),
    .Y(\synthory_ram_d[6] [4])
  );
  NOR _0776_ (
    .A(_0233_),
    .B(_0216_),
    .Y(_0270_)
  );
  NAND _0777_ (
    .A(_0270_),
    .B(write_data[0]),
    .Y(_0271_)
  );
  NOT _0778_ (
    .A(_0270_),
    .Y(_0272_)
  );
  NAND _0779_ (
    .A(_0272_),
    .B(\synthory_ram_q[7] [0]),
    .Y(_0273_)
  );
  NAND _0780_ (
    .A(_0273_),
    .B(_0271_),
    .Y(\synthory_ram_d[7] [0])
  );
  NAND _0781_ (
    .A(_0270_),
    .B(write_data[1]),
    .Y(_0274_)
  );
  NAND _0782_ (
    .A(_0272_),
    .B(\synthory_ram_q[7] [1]),
    .Y(_0275_)
  );
  NAND _0783_ (
    .A(_0275_),
    .B(_0274_),
    .Y(\synthory_ram_d[7] [1])
  );
  NAND _0784_ (
    .A(_0270_),
    .B(write_data[2]),
    .Y(_0276_)
  );
  NAND _0785_ (
    .A(_0272_),
    .B(\synthory_ram_q[7] [2]),
    .Y(_0277_)
  );
  NAND _0786_ (
    .A(_0277_),
    .B(_0276_),
    .Y(\synthory_ram_d[7] [2])
  );
  NAND _0787_ (
    .A(_0270_),
    .B(write_data[3]),
    .Y(_0278_)
  );
  NAND _0788_ (
    .A(_0272_),
    .B(\synthory_ram_q[7] [3]),
    .Y(_0279_)
  );
  NAND _0789_ (
    .A(_0279_),
    .B(_0278_),
    .Y(\synthory_ram_d[7] [3])
  );
  NAND _0790_ (
    .A(_0270_),
    .B(write_data[4]),
    .Y(_0280_)
  );
  NAND _0791_ (
    .A(_0272_),
    .B(\synthory_ram_q[7] [4]),
    .Y(_0281_)
  );
  NAND _0792_ (
    .A(_0281_),
    .B(_0280_),
    .Y(\synthory_ram_d[7] [4])
  );
  NAND _0793_ (
    .A(w_address[3]),
    .B(_0231_),
    .Y(_0282_)
  );
  NOR _0794_ (
    .A(_0282_),
    .B(_0230_),
    .Y(_0283_)
  );
  NAND _0795_ (
    .A(_0283_),
    .B(write_data[0]),
    .Y(_0284_)
  );
  NOT _0796_ (
    .A(_0283_),
    .Y(_0285_)
  );
  NAND _0797_ (
    .A(_0285_),
    .B(\synthory_ram_q[8] [0]),
    .Y(_0286_)
  );
  NAND _0798_ (
    .A(_0286_),
    .B(_0284_),
    .Y(\synthory_ram_d[8] [0])
  );
  NAND _0799_ (
    .A(_0283_),
    .B(write_data[1]),
    .Y(_0287_)
  );
  NAND _0800_ (
    .A(_0285_),
    .B(\synthory_ram_q[8] [1]),
    .Y(_0288_)
  );
  NAND _0801_ (
    .A(_0288_),
    .B(_0287_),
    .Y(\synthory_ram_d[8] [1])
  );
  NAND _0802_ (
    .A(_0283_),
    .B(write_data[2]),
    .Y(_0289_)
  );
  NAND _0803_ (
    .A(_0285_),
    .B(\synthory_ram_q[8] [2]),
    .Y(_0290_)
  );
  NAND _0804_ (
    .A(_0290_),
    .B(_0289_),
    .Y(\synthory_ram_d[8] [2])
  );
  NAND _0805_ (
    .A(_0283_),
    .B(write_data[3]),
    .Y(_0291_)
  );
  NAND _0806_ (
    .A(_0285_),
    .B(\synthory_ram_q[8] [3]),
    .Y(_0292_)
  );
  NAND _0807_ (
    .A(_0292_),
    .B(_0291_),
    .Y(\synthory_ram_d[8] [3])
  );
  NAND _0808_ (
    .A(_0283_),
    .B(write_data[4]),
    .Y(_0293_)
  );
  NAND _0809_ (
    .A(_0285_),
    .B(\synthory_ram_q[8] [4]),
    .Y(_0294_)
  );
  NAND _0810_ (
    .A(_0294_),
    .B(_0293_),
    .Y(\synthory_ram_d[8] [4])
  );
  NOR _0811_ (
    .A(_0282_),
    .B(_0188_),
    .Y(_0295_)
  );
  NAND _0812_ (
    .A(_0295_),
    .B(write_data[0]),
    .Y(_0296_)
  );
  NOT _0813_ (
    .A(_0295_),
    .Y(_0297_)
  );
  NAND _0814_ (
    .A(_0297_),
    .B(\synthory_ram_q[9] [0]),
    .Y(_0298_)
  );
  NAND _0815_ (
    .A(_0298_),
    .B(_0296_),
    .Y(\synthory_ram_d[9] [0])
  );
  NAND _0816_ (
    .A(_0295_),
    .B(write_data[1]),
    .Y(_0299_)
  );
  NAND _0817_ (
    .A(_0297_),
    .B(\synthory_ram_q[9] [1]),
    .Y(_0300_)
  );
  NAND _0818_ (
    .A(_0300_),
    .B(_0299_),
    .Y(\synthory_ram_d[9] [1])
  );
  NAND _0819_ (
    .A(_0295_),
    .B(write_data[2]),
    .Y(_0301_)
  );
  NAND _0820_ (
    .A(_0297_),
    .B(\synthory_ram_q[9] [2]),
    .Y(_0302_)
  );
  NAND _0821_ (
    .A(_0302_),
    .B(_0301_),
    .Y(\synthory_ram_d[9] [2])
  );
  NAND _0822_ (
    .A(_0295_),
    .B(write_data[3]),
    .Y(_0303_)
  );
  NAND _0823_ (
    .A(_0297_),
    .B(\synthory_ram_q[9] [3]),
    .Y(_0304_)
  );
  NAND _0824_ (
    .A(_0304_),
    .B(_0303_),
    .Y(\synthory_ram_d[9] [3])
  );
  NAND _0825_ (
    .A(_0295_),
    .B(write_data[4]),
    .Y(_0305_)
  );
  NAND _0826_ (
    .A(_0297_),
    .B(\synthory_ram_q[9] [4]),
    .Y(_0306_)
  );
  NAND _0827_ (
    .A(_0306_),
    .B(_0305_),
    .Y(\synthory_ram_d[9] [4])
  );
  NOR _0828_ (
    .A(_0282_),
    .B(_0203_),
    .Y(_0307_)
  );
  NAND _0829_ (
    .A(_0307_),
    .B(write_data[0]),
    .Y(_0308_)
  );
  NOT _0830_ (
    .A(_0307_),
    .Y(_0309_)
  );
  NAND _0831_ (
    .A(_0309_),
    .B(\synthory_ram_q[10] [0]),
    .Y(_0310_)
  );
  NAND _0832_ (
    .A(_0310_),
    .B(_0308_),
    .Y(\synthory_ram_d[10] [0])
  );
  NAND _0833_ (
    .A(_0307_),
    .B(write_data[1]),
    .Y(_0311_)
  );
  NAND _0834_ (
    .A(_0309_),
    .B(\synthory_ram_q[10] [1]),
    .Y(_0312_)
  );
  NAND _0835_ (
    .A(_0312_),
    .B(_0311_),
    .Y(\synthory_ram_d[10] [1])
  );
  NAND _0836_ (
    .A(_0307_),
    .B(write_data[2]),
    .Y(_0313_)
  );
  NAND _0837_ (
    .A(_0309_),
    .B(\synthory_ram_q[10] [2]),
    .Y(_0314_)
  );
  NAND _0838_ (
    .A(_0314_),
    .B(_0313_),
    .Y(\synthory_ram_d[10] [2])
  );
  NAND _0839_ (
    .A(_0307_),
    .B(write_data[3]),
    .Y(_0315_)
  );
  NAND _0840_ (
    .A(_0309_),
    .B(\synthory_ram_q[10] [3]),
    .Y(_0316_)
  );
  NAND _0841_ (
    .A(_0316_),
    .B(_0315_),
    .Y(\synthory_ram_d[10] [3])
  );
  NAND _0842_ (
    .A(_0307_),
    .B(write_data[4]),
    .Y(_0317_)
  );
  NAND _0843_ (
    .A(_0309_),
    .B(\synthory_ram_q[10] [4]),
    .Y(_0318_)
  );
  NAND _0844_ (
    .A(_0318_),
    .B(_0317_),
    .Y(\synthory_ram_d[10] [4])
  );
  NOR _0845_ (
    .A(_0282_),
    .B(_0216_),
    .Y(_0319_)
  );
  NAND _0846_ (
    .A(_0319_),
    .B(write_data[0]),
    .Y(_0320_)
  );
  NOT _0847_ (
    .A(_0319_),
    .Y(_0321_)
  );
  NAND _0848_ (
    .A(_0321_),
    .B(\synthory_ram_q[11] [0]),
    .Y(_0322_)
  );
  NAND _0849_ (
    .A(_0322_),
    .B(_0320_),
    .Y(\synthory_ram_d[11] [0])
  );
  NAND _0850_ (
    .A(_0319_),
    .B(write_data[1]),
    .Y(_0323_)
  );
  NAND _0851_ (
    .A(_0321_),
    .B(\synthory_ram_q[11] [1]),
    .Y(_0324_)
  );
  NAND _0852_ (
    .A(_0324_),
    .B(_0323_),
    .Y(\synthory_ram_d[11] [1])
  );
  NAND _0853_ (
    .A(_0319_),
    .B(write_data[2]),
    .Y(_0325_)
  );
  NAND _0854_ (
    .A(_0321_),
    .B(\synthory_ram_q[11] [2]),
    .Y(_0326_)
  );
  NAND _0855_ (
    .A(_0326_),
    .B(_0325_),
    .Y(\synthory_ram_d[11] [2])
  );
  NAND _0856_ (
    .A(_0319_),
    .B(write_data[3]),
    .Y(_0327_)
  );
  NAND _0857_ (
    .A(_0321_),
    .B(\synthory_ram_q[11] [3]),
    .Y(_0328_)
  );
  NAND _0858_ (
    .A(_0328_),
    .B(_0327_),
    .Y(\synthory_ram_d[11] [3])
  );
  NAND _0859_ (
    .A(_0319_),
    .B(write_data[4]),
    .Y(_0329_)
  );
  NAND _0860_ (
    .A(_0321_),
    .B(\synthory_ram_q[11] [4]),
    .Y(_0330_)
  );
  NAND _0861_ (
    .A(_0330_),
    .B(_0329_),
    .Y(\synthory_ram_d[11] [4])
  );
  NAND _0862_ (
    .A(w_address[3]),
    .B(w_address[2]),
    .Y(_0331_)
  );
  NOR _0863_ (
    .A(_0331_),
    .B(_0230_),
    .Y(_0332_)
  );
  NAND _0864_ (
    .A(_0332_),
    .B(write_data[0]),
    .Y(_0333_)
  );
  NOT _0865_ (
    .A(_0332_),
    .Y(_0334_)
  );
  NAND _0866_ (
    .A(_0334_),
    .B(\synthory_ram_q[12] [0]),
    .Y(_0335_)
  );
  NAND _0867_ (
    .A(_0335_),
    .B(_0333_),
    .Y(\synthory_ram_d[12] [0])
  );
  NAND _0868_ (
    .A(_0332_),
    .B(write_data[1]),
    .Y(_0336_)
  );
  NAND _0869_ (
    .A(_0334_),
    .B(\synthory_ram_q[12] [1]),
    .Y(_0337_)
  );
  NAND _0870_ (
    .A(_0337_),
    .B(_0336_),
    .Y(\synthory_ram_d[12] [1])
  );
  NAND _0871_ (
    .A(_0332_),
    .B(write_data[2]),
    .Y(_0338_)
  );
  NAND _0872_ (
    .A(_0334_),
    .B(\synthory_ram_q[12] [2]),
    .Y(_0339_)
  );
  NAND _0873_ (
    .A(_0339_),
    .B(_0338_),
    .Y(\synthory_ram_d[12] [2])
  );
  NAND _0874_ (
    .A(_0332_),
    .B(write_data[3]),
    .Y(_0340_)
  );
  NAND _0875_ (
    .A(_0334_),
    .B(\synthory_ram_q[12] [3]),
    .Y(_0341_)
  );
  NAND _0876_ (
    .A(_0341_),
    .B(_0340_),
    .Y(\synthory_ram_d[12] [3])
  );
  NAND _0877_ (
    .A(_0332_),
    .B(write_data[4]),
    .Y(_0342_)
  );
  NAND _0878_ (
    .A(_0334_),
    .B(\synthory_ram_q[12] [4]),
    .Y(_0343_)
  );
  NAND _0879_ (
    .A(_0343_),
    .B(_0342_),
    .Y(\synthory_ram_d[12] [4])
  );
  NOR _0880_ (
    .A(_0331_),
    .B(_0188_),
    .Y(_0344_)
  );
  NAND _0881_ (
    .A(_0344_),
    .B(write_data[0]),
    .Y(_0345_)
  );
  NOT _0882_ (
    .A(_0344_),
    .Y(_0346_)
  );
  NAND _0883_ (
    .A(_0346_),
    .B(\synthory_ram_q[13] [0]),
    .Y(_0347_)
  );
  NAND _0884_ (
    .A(_0347_),
    .B(_0345_),
    .Y(\synthory_ram_d[13] [0])
  );
  NAND _0885_ (
    .A(_0344_),
    .B(write_data[1]),
    .Y(_0348_)
  );
  NAND _0886_ (
    .A(_0346_),
    .B(\synthory_ram_q[13] [1]),
    .Y(_0350_)
  );
  NAND _0887_ (
    .A(_0350_),
    .B(_0348_),
    .Y(\synthory_ram_d[13] [1])
  );
  NAND _0888_ (
    .A(_0344_),
    .B(write_data[2]),
    .Y(_0353_)
  );
  NAND _0889_ (
    .A(_0346_),
    .B(\synthory_ram_q[13] [2]),
    .Y(_0355_)
  );
  NAND _0890_ (
    .A(_0355_),
    .B(_0353_),
    .Y(\synthory_ram_d[13] [2])
  );
  NAND _0891_ (
    .A(_0344_),
    .B(write_data[3]),
    .Y(_0358_)
  );
  NAND _0892_ (
    .A(_0346_),
    .B(\synthory_ram_q[13] [3]),
    .Y(_0360_)
  );
  NAND _0893_ (
    .A(_0360_),
    .B(_0358_),
    .Y(\synthory_ram_d[13] [3])
  );
  NAND _0894_ (
    .A(_0344_),
    .B(write_data[4]),
    .Y(_0363_)
  );
  NAND _0895_ (
    .A(_0346_),
    .B(\synthory_ram_q[13] [4]),
    .Y(_0365_)
  );
  NAND _0896_ (
    .A(_0365_),
    .B(_0363_),
    .Y(\synthory_ram_d[13] [4])
  );
  NOR _0897_ (
    .A(_0331_),
    .B(_0203_),
    .Y(_0368_)
  );
  NAND _0898_ (
    .A(_0368_),
    .B(write_data[0]),
    .Y(_0370_)
  );
  NOT _0899_ (
    .A(_0368_),
    .Y(_0372_)
  );
  NAND _0900_ (
    .A(_0372_),
    .B(\synthory_ram_q[14] [0]),
    .Y(_0374_)
  );
  NAND _0901_ (
    .A(_0374_),
    .B(_0370_),
    .Y(\synthory_ram_d[14] [0])
  );
  NAND _0902_ (
    .A(_0368_),
    .B(write_data[1]),
    .Y(_0377_)
  );
  NAND _0903_ (
    .A(_0372_),
    .B(\synthory_ram_q[14] [1]),
    .Y(_0379_)
  );
  NAND _0904_ (
    .A(_0379_),
    .B(_0377_),
    .Y(\synthory_ram_d[14] [1])
  );
  NAND _0905_ (
    .A(_0368_),
    .B(write_data[2]),
    .Y(_0382_)
  );
  NAND _0906_ (
    .A(_0372_),
    .B(\synthory_ram_q[14] [2]),
    .Y(_0384_)
  );
  NAND _0907_ (
    .A(_0384_),
    .B(_0382_),
    .Y(\synthory_ram_d[14] [2])
  );
  NAND _0908_ (
    .A(_0368_),
    .B(write_data[3]),
    .Y(_0387_)
  );
  NAND _0909_ (
    .A(_0372_),
    .B(\synthory_ram_q[14] [3]),
    .Y(_0389_)
  );
  NAND _0910_ (
    .A(_0389_),
    .B(_0387_),
    .Y(\synthory_ram_d[14] [3])
  );
  NAND _0911_ (
    .A(_0368_),
    .B(write_data[4]),
    .Y(_0392_)
  );
  NAND _0912_ (
    .A(_0372_),
    .B(\synthory_ram_q[14] [4]),
    .Y(_0394_)
  );
  NAND _0913_ (
    .A(_0394_),
    .B(_0392_),
    .Y(\synthory_ram_d[14] [4])
  );
  NOR _0914_ (
    .A(_0331_),
    .B(_0216_),
    .Y(_0397_)
  );
  NAND _0915_ (
    .A(_0397_),
    .B(write_data[0]),
    .Y(_0399_)
  );
  NOT _0916_ (
    .A(_0397_),
    .Y(_0401_)
  );
  NAND _0917_ (
    .A(_0401_),
    .B(\synthory_ram_q[15] [0]),
    .Y(_0403_)
  );
  NAND _0918_ (
    .A(_0403_),
    .B(_0399_),
    .Y(\synthory_ram_d[15] [0])
  );
  NAND _0919_ (
    .A(_0397_),
    .B(write_data[1]),
    .Y(_0406_)
  );
  NAND _0920_ (
    .A(_0401_),
    .B(\synthory_ram_q[15] [1]),
    .Y(_0408_)
  );
  NAND _0921_ (
    .A(_0408_),
    .B(_0406_),
    .Y(\synthory_ram_d[15] [1])
  );
  NAND _0922_ (
    .A(_0397_),
    .B(write_data[2]),
    .Y(_0411_)
  );
  NAND _0923_ (
    .A(_0401_),
    .B(\synthory_ram_q[15] [2]),
    .Y(_0413_)
  );
  NAND _0924_ (
    .A(_0413_),
    .B(_0411_),
    .Y(\synthory_ram_d[15] [2])
  );
  NAND _0925_ (
    .A(_0397_),
    .B(write_data[3]),
    .Y(_0416_)
  );
  NAND _0926_ (
    .A(_0401_),
    .B(\synthory_ram_q[15] [3]),
    .Y(_0418_)
  );
  NAND _0927_ (
    .A(_0418_),
    .B(_0416_),
    .Y(\synthory_ram_d[15] [3])
  );
  NAND _0928_ (
    .A(_0397_),
    .B(write_data[4]),
    .Y(_0421_)
  );
  NAND _0929_ (
    .A(_0401_),
    .B(\synthory_ram_q[15] [4]),
    .Y(_0423_)
  );
  NAND _0930_ (
    .A(_0423_),
    .B(_0421_),
    .Y(\synthory_ram_d[15] [4])
  );
  NAND _0931_ (
    .A(_0229_),
    .B(_0189_),
    .Y(_0426_)
  );
  NOT _0932_ (
    .A(_0426_),
    .Y(_0428_)
  );
  NAND _0933_ (
    .A(_0428_),
    .B(write_data[0]),
    .Y(_0430_)
  );
  NAND _0934_ (
    .A(_0426_),
    .B(\synthory_ram_q[0] [0]),
    .Y(_0432_)
  );
  NAND _0935_ (
    .A(_0432_),
    .B(_0430_),
    .Y(\synthory_ram_d[0] [0])
  );
  NAND _0936_ (
    .A(_0428_),
    .B(write_data[1]),
    .Y(_0435_)
  );
  NAND _0937_ (
    .A(_0426_),
    .B(\synthory_ram_q[0] [1]),
    .Y(_0437_)
  );
  NAND _0938_ (
    .A(_0437_),
    .B(_0435_),
    .Y(\synthory_ram_d[0] [1])
  );
  NAND _0939_ (
    .A(_0428_),
    .B(write_data[2]),
    .Y(_0440_)
  );
  NAND _0940_ (
    .A(_0426_),
    .B(\synthory_ram_q[0] [2]),
    .Y(_0442_)
  );
  NAND _0941_ (
    .A(_0442_),
    .B(_0440_),
    .Y(\synthory_ram_d[0] [2])
  );
  NAND _0942_ (
    .A(_0428_),
    .B(write_data[3]),
    .Y(_0445_)
  );
  NAND _0943_ (
    .A(_0426_),
    .B(\synthory_ram_q[0] [3]),
    .Y(_0447_)
  );
  NAND _0944_ (
    .A(_0447_),
    .B(_0445_),
    .Y(\synthory_ram_d[0] [3])
  );
  NAND _0945_ (
    .A(_0428_),
    .B(write_data[4]),
    .Y(_0450_)
  );
  NAND _0946_ (
    .A(_0426_),
    .B(\synthory_ram_q[0] [4]),
    .Y(_0452_)
  );
  NAND _0947_ (
    .A(_0452_),
    .B(_0450_),
    .Y(\synthory_ram_d[0] [4])
  );
  NOT _0948_ (
    .A(rst),
    .Y(_0349_)
  );
  NOT _0949_ (
    .A(rst),
    .Y(_0351_)
  );
  NOT _0950_ (
    .A(rst),
    .Y(_0352_)
  );
  NOT _0951_ (
    .A(rst),
    .Y(_0354_)
  );
  NOT _0952_ (
    .A(rst),
    .Y(_0356_)
  );
  NOT _0953_ (
    .A(rst),
    .Y(_0357_)
  );
  NOT _0954_ (
    .A(rst),
    .Y(_0359_)
  );
  NOT _0955_ (
    .A(rst),
    .Y(_0361_)
  );
  NOT _0956_ (
    .A(rst),
    .Y(_0362_)
  );
  NOT _0957_ (
    .A(rst),
    .Y(_0364_)
  );
  NOT _0958_ (
    .A(rst),
    .Y(_0366_)
  );
  NOT _0959_ (
    .A(rst),
    .Y(_0367_)
  );
  NOT _0960_ (
    .A(rst),
    .Y(_0369_)
  );
  NOT _0961_ (
    .A(rst),
    .Y(_0371_)
  );
  NOT _0962_ (
    .A(rst),
    .Y(_0373_)
  );
  NOT _0963_ (
    .A(rst),
    .Y(_0375_)
  );
  NOT _0964_ (
    .A(rst),
    .Y(_0376_)
  );
  NOT _0965_ (
    .A(rst),
    .Y(_0378_)
  );
  NOT _0966_ (
    .A(rst),
    .Y(_0380_)
  );
  NOT _0967_ (
    .A(rst),
    .Y(_0381_)
  );
  NOT _0968_ (
    .A(rst),
    .Y(_0383_)
  );
  NOT _0969_ (
    .A(rst),
    .Y(_0385_)
  );
  NOT _0970_ (
    .A(rst),
    .Y(_0386_)
  );
  NOT _0971_ (
    .A(rst),
    .Y(_0388_)
  );
  NOT _0972_ (
    .A(rst),
    .Y(_0390_)
  );
  NOT _0973_ (
    .A(rst),
    .Y(_0391_)
  );
  NOT _0974_ (
    .A(rst),
    .Y(_0393_)
  );
  NOT _0975_ (
    .A(rst),
    .Y(_0395_)
  );
  NOT _0976_ (
    .A(rst),
    .Y(_0396_)
  );
  NOT _0977_ (
    .A(rst),
    .Y(_0398_)
  );
  NOT _0978_ (
    .A(rst),
    .Y(_0400_)
  );
  NOT _0979_ (
    .A(rst),
    .Y(_0402_)
  );
  NOT _0980_ (
    .A(rst),
    .Y(_0404_)
  );
  NOT _0981_ (
    .A(rst),
    .Y(_0405_)
  );
  NOT _0982_ (
    .A(rst),
    .Y(_0407_)
  );
  NOT _0983_ (
    .A(rst),
    .Y(_0409_)
  );
  NOT _0984_ (
    .A(rst),
    .Y(_0410_)
  );
  NOT _0985_ (
    .A(rst),
    .Y(_0412_)
  );
  NOT _0986_ (
    .A(rst),
    .Y(_0414_)
  );
  NOT _0987_ (
    .A(rst),
    .Y(_0415_)
  );
  NOT _0988_ (
    .A(rst),
    .Y(_0417_)
  );
  NOT _0989_ (
    .A(rst),
    .Y(_0419_)
  );
  NOT _0990_ (
    .A(rst),
    .Y(_0420_)
  );
  NOT _0991_ (
    .A(rst),
    .Y(_0422_)
  );
  NOT _0992_ (
    .A(rst),
    .Y(_0424_)
  );
  NOT _0993_ (
    .A(rst),
    .Y(_0425_)
  );
  NOT _0994_ (
    .A(rst),
    .Y(_0427_)
  );
  NOT _0995_ (
    .A(rst),
    .Y(_0429_)
  );
  NOT _0996_ (
    .A(rst),
    .Y(_0431_)
  );
  NOT _0997_ (
    .A(rst),
    .Y(_0433_)
  );
  NOT _0998_ (
    .A(rst),
    .Y(_0434_)
  );
  NOT _0999_ (
    .A(rst),
    .Y(_0436_)
  );
  NOT _1000_ (
    .A(rst),
    .Y(_0438_)
  );
  NOT _1001_ (
    .A(rst),
    .Y(_0439_)
  );
  NOT _1002_ (
    .A(rst),
    .Y(_0441_)
  );
  NOT _1003_ (
    .A(rst),
    .Y(_0443_)
  );
  NOT _1004_ (
    .A(rst),
    .Y(_0444_)
  );
  NOT _1005_ (
    .A(rst),
    .Y(_0446_)
  );
  NOT _1006_ (
    .A(rst),
    .Y(_0448_)
  );
  NOT _1007_ (
    .A(rst),
    .Y(_0449_)
  );
  NOT _1008_ (
    .A(rst),
    .Y(_0451_)
  );
  NOT _1009_ (
    .A(rst),
    .Y(_0453_)
  );
  NOT _1010_ (
    .A(rst),
    .Y(_0454_)
  );
  NOT _1011_ (
    .A(rst),
    .Y(_0455_)
  );
  NOT _1012_ (
    .A(rst),
    .Y(_0456_)
  );
  NOT _1013_ (
    .A(rst),
    .Y(_0457_)
  );
  NOT _1014_ (
    .A(rst),
    .Y(_0458_)
  );
  NOT _1015_ (
    .A(rst),
    .Y(_0459_)
  );
  NOT _1016_ (
    .A(rst),
    .Y(_0460_)
  );
  NOT _1017_ (
    .A(rst),
    .Y(_0461_)
  );
  NOT _1018_ (
    .A(rst),
    .Y(_0462_)
  );
  NOT _1019_ (
    .A(rst),
    .Y(_0463_)
  );
  NOT _1020_ (
    .A(rst),
    .Y(_0464_)
  );
  NOT _1021_ (
    .A(rst),
    .Y(_0465_)
  );
  NOT _1022_ (
    .A(rst),
    .Y(_0466_)
  );
  NOT _1023_ (
    .A(rst),
    .Y(_0467_)
  );
  NOT _1024_ (
    .A(rst),
    .Y(_0468_)
  );
  NOT _1025_ (
    .A(rst),
    .Y(_0469_)
  );
  NOT _1026_ (
    .A(rst),
    .Y(_0470_)
  );
  DFFSR _1027_ (
    .C(clk),
    .D(\synthory_ram_d[0] [0]),
    .Q(\synthory_ram_q[0] [0]),
    .R(_0349_),
    .S(1'b0)
  );
  DFFSR _1028_ (
    .C(clk),
    .D(\synthory_ram_d[0] [1]),
    .Q(\synthory_ram_q[0] [1]),
    .R(_0351_),
    .S(1'b0)
  );
  DFFSR _1029_ (
    .C(clk),
    .D(\synthory_ram_d[0] [2]),
    .Q(\synthory_ram_q[0] [2]),
    .R(_0352_),
    .S(1'b0)
  );
  DFFSR _1030_ (
    .C(clk),
    .D(\synthory_ram_d[0] [3]),
    .Q(\synthory_ram_q[0] [3]),
    .R(_0354_),
    .S(1'b0)
  );
  DFFSR _1031_ (
    .C(clk),
    .D(\synthory_ram_d[0] [4]),
    .Q(\synthory_ram_q[0] [4]),
    .R(_0356_),
    .S(1'b0)
  );
  DFFSR _1032_ (
    .C(clk),
    .D(\synthory_ram_d[1] [0]),
    .Q(\synthory_ram_q[1] [0]),
    .R(_0357_),
    .S(1'b0)
  );
  DFFSR _1033_ (
    .C(clk),
    .D(\synthory_ram_d[1] [1]),
    .Q(\synthory_ram_q[1] [1]),
    .R(_0359_),
    .S(1'b0)
  );
  DFFSR _1034_ (
    .C(clk),
    .D(\synthory_ram_d[1] [2]),
    .Q(\synthory_ram_q[1] [2]),
    .R(_0361_),
    .S(1'b0)
  );
  DFFSR _1035_ (
    .C(clk),
    .D(\synthory_ram_d[1] [3]),
    .Q(\synthory_ram_q[1] [3]),
    .R(_0362_),
    .S(1'b0)
  );
  DFFSR _1036_ (
    .C(clk),
    .D(\synthory_ram_d[1] [4]),
    .Q(\synthory_ram_q[1] [4]),
    .R(_0364_),
    .S(1'b0)
  );
  DFFSR _1037_ (
    .C(clk),
    .D(\synthory_ram_d[2] [0]),
    .Q(\synthory_ram_q[2] [0]),
    .R(_0366_),
    .S(1'b0)
  );
  DFFSR _1038_ (
    .C(clk),
    .D(\synthory_ram_d[2] [1]),
    .Q(\synthory_ram_q[2] [1]),
    .R(_0367_),
    .S(1'b0)
  );
  DFFSR _1039_ (
    .C(clk),
    .D(\synthory_ram_d[2] [2]),
    .Q(\synthory_ram_q[2] [2]),
    .R(_0369_),
    .S(1'b0)
  );
  DFFSR _1040_ (
    .C(clk),
    .D(\synthory_ram_d[2] [3]),
    .Q(\synthory_ram_q[2] [3]),
    .R(_0371_),
    .S(1'b0)
  );
  DFFSR _1041_ (
    .C(clk),
    .D(\synthory_ram_d[2] [4]),
    .Q(\synthory_ram_q[2] [4]),
    .R(_0373_),
    .S(1'b0)
  );
  DFFSR _1042_ (
    .C(clk),
    .D(\synthory_ram_d[3] [0]),
    .Q(\synthory_ram_q[3] [0]),
    .R(_0375_),
    .S(1'b0)
  );
  DFFSR _1043_ (
    .C(clk),
    .D(\synthory_ram_d[3] [1]),
    .Q(\synthory_ram_q[3] [1]),
    .R(_0376_),
    .S(1'b0)
  );
  DFFSR _1044_ (
    .C(clk),
    .D(\synthory_ram_d[3] [2]),
    .Q(\synthory_ram_q[3] [2]),
    .R(_0378_),
    .S(1'b0)
  );
  DFFSR _1045_ (
    .C(clk),
    .D(\synthory_ram_d[3] [3]),
    .Q(\synthory_ram_q[3] [3]),
    .R(_0380_),
    .S(1'b0)
  );
  DFFSR _1046_ (
    .C(clk),
    .D(\synthory_ram_d[3] [4]),
    .Q(\synthory_ram_q[3] [4]),
    .R(_0381_),
    .S(1'b0)
  );
  DFFSR _1047_ (
    .C(clk),
    .D(\synthory_ram_d[4] [0]),
    .Q(\synthory_ram_q[4] [0]),
    .R(_0383_),
    .S(1'b0)
  );
  DFFSR _1048_ (
    .C(clk),
    .D(\synthory_ram_d[4] [1]),
    .Q(\synthory_ram_q[4] [1]),
    .R(_0385_),
    .S(1'b0)
  );
  DFFSR _1049_ (
    .C(clk),
    .D(\synthory_ram_d[4] [2]),
    .Q(\synthory_ram_q[4] [2]),
    .R(_0386_),
    .S(1'b0)
  );
  DFFSR _1050_ (
    .C(clk),
    .D(\synthory_ram_d[4] [3]),
    .Q(\synthory_ram_q[4] [3]),
    .R(_0388_),
    .S(1'b0)
  );
  DFFSR _1051_ (
    .C(clk),
    .D(\synthory_ram_d[4] [4]),
    .Q(\synthory_ram_q[4] [4]),
    .R(_0390_),
    .S(1'b0)
  );
  DFFSR _1052_ (
    .C(clk),
    .D(\synthory_ram_d[5] [0]),
    .Q(\synthory_ram_q[5] [0]),
    .R(_0391_),
    .S(1'b0)
  );
  DFFSR _1053_ (
    .C(clk),
    .D(\synthory_ram_d[5] [1]),
    .Q(\synthory_ram_q[5] [1]),
    .R(_0393_),
    .S(1'b0)
  );
  DFFSR _1054_ (
    .C(clk),
    .D(\synthory_ram_d[5] [2]),
    .Q(\synthory_ram_q[5] [2]),
    .R(_0395_),
    .S(1'b0)
  );
  DFFSR _1055_ (
    .C(clk),
    .D(\synthory_ram_d[5] [3]),
    .Q(\synthory_ram_q[5] [3]),
    .R(_0396_),
    .S(1'b0)
  );
  DFFSR _1056_ (
    .C(clk),
    .D(\synthory_ram_d[5] [4]),
    .Q(\synthory_ram_q[5] [4]),
    .R(_0398_),
    .S(1'b0)
  );
  DFFSR _1057_ (
    .C(clk),
    .D(\synthory_ram_d[6] [0]),
    .Q(\synthory_ram_q[6] [0]),
    .R(_0400_),
    .S(1'b0)
  );
  DFFSR _1058_ (
    .C(clk),
    .D(\synthory_ram_d[6] [1]),
    .Q(\synthory_ram_q[6] [1]),
    .R(_0402_),
    .S(1'b0)
  );
  DFFSR _1059_ (
    .C(clk),
    .D(\synthory_ram_d[6] [2]),
    .Q(\synthory_ram_q[6] [2]),
    .R(_0404_),
    .S(1'b0)
  );
  DFFSR _1060_ (
    .C(clk),
    .D(\synthory_ram_d[6] [3]),
    .Q(\synthory_ram_q[6] [3]),
    .R(_0405_),
    .S(1'b0)
  );
  DFFSR _1061_ (
    .C(clk),
    .D(\synthory_ram_d[6] [4]),
    .Q(\synthory_ram_q[6] [4]),
    .R(_0407_),
    .S(1'b0)
  );
  DFFSR _1062_ (
    .C(clk),
    .D(\synthory_ram_d[7] [0]),
    .Q(\synthory_ram_q[7] [0]),
    .R(_0409_),
    .S(1'b0)
  );
  DFFSR _1063_ (
    .C(clk),
    .D(\synthory_ram_d[7] [1]),
    .Q(\synthory_ram_q[7] [1]),
    .R(_0410_),
    .S(1'b0)
  );
  DFFSR _1064_ (
    .C(clk),
    .D(\synthory_ram_d[7] [2]),
    .Q(\synthory_ram_q[7] [2]),
    .R(_0412_),
    .S(1'b0)
  );
  DFFSR _1065_ (
    .C(clk),
    .D(\synthory_ram_d[7] [3]),
    .Q(\synthory_ram_q[7] [3]),
    .R(_0414_),
    .S(1'b0)
  );
  DFFSR _1066_ (
    .C(clk),
    .D(\synthory_ram_d[7] [4]),
    .Q(\synthory_ram_q[7] [4]),
    .R(_0415_),
    .S(1'b0)
  );
  DFFSR _1067_ (
    .C(clk),
    .D(\synthory_ram_d[8] [0]),
    .Q(\synthory_ram_q[8] [0]),
    .R(_0417_),
    .S(1'b0)
  );
  DFFSR _1068_ (
    .C(clk),
    .D(\synthory_ram_d[8] [1]),
    .Q(\synthory_ram_q[8] [1]),
    .R(_0419_),
    .S(1'b0)
  );
  DFFSR _1069_ (
    .C(clk),
    .D(\synthory_ram_d[8] [2]),
    .Q(\synthory_ram_q[8] [2]),
    .R(_0420_),
    .S(1'b0)
  );
  DFFSR _1070_ (
    .C(clk),
    .D(\synthory_ram_d[8] [3]),
    .Q(\synthory_ram_q[8] [3]),
    .R(_0422_),
    .S(1'b0)
  );
  DFFSR _1071_ (
    .C(clk),
    .D(\synthory_ram_d[8] [4]),
    .Q(\synthory_ram_q[8] [4]),
    .R(_0424_),
    .S(1'b0)
  );
  DFFSR _1072_ (
    .C(clk),
    .D(\synthory_ram_d[9] [0]),
    .Q(\synthory_ram_q[9] [0]),
    .R(_0425_),
    .S(1'b0)
  );
  DFFSR _1073_ (
    .C(clk),
    .D(\synthory_ram_d[9] [1]),
    .Q(\synthory_ram_q[9] [1]),
    .R(_0427_),
    .S(1'b0)
  );
  DFFSR _1074_ (
    .C(clk),
    .D(\synthory_ram_d[9] [2]),
    .Q(\synthory_ram_q[9] [2]),
    .R(_0429_),
    .S(1'b0)
  );
  DFFSR _1075_ (
    .C(clk),
    .D(\synthory_ram_d[9] [3]),
    .Q(\synthory_ram_q[9] [3]),
    .R(_0431_),
    .S(1'b0)
  );
  DFFSR _1076_ (
    .C(clk),
    .D(\synthory_ram_d[9] [4]),
    .Q(\synthory_ram_q[9] [4]),
    .R(_0433_),
    .S(1'b0)
  );
  DFFSR _1077_ (
    .C(clk),
    .D(\synthory_ram_d[10] [0]),
    .Q(\synthory_ram_q[10] [0]),
    .R(_0434_),
    .S(1'b0)
  );
  DFFSR _1078_ (
    .C(clk),
    .D(\synthory_ram_d[10] [1]),
    .Q(\synthory_ram_q[10] [1]),
    .R(_0436_),
    .S(1'b0)
  );
  DFFSR _1079_ (
    .C(clk),
    .D(\synthory_ram_d[10] [2]),
    .Q(\synthory_ram_q[10] [2]),
    .R(_0438_),
    .S(1'b0)
  );
  DFFSR _1080_ (
    .C(clk),
    .D(\synthory_ram_d[10] [3]),
    .Q(\synthory_ram_q[10] [3]),
    .R(_0439_),
    .S(1'b0)
  );
  DFFSR _1081_ (
    .C(clk),
    .D(\synthory_ram_d[10] [4]),
    .Q(\synthory_ram_q[10] [4]),
    .R(_0441_),
    .S(1'b0)
  );
  DFFSR _1082_ (
    .C(clk),
    .D(\synthory_ram_d[11] [0]),
    .Q(\synthory_ram_q[11] [0]),
    .R(_0443_),
    .S(1'b0)
  );
  DFFSR _1083_ (
    .C(clk),
    .D(\synthory_ram_d[11] [1]),
    .Q(\synthory_ram_q[11] [1]),
    .R(_0444_),
    .S(1'b0)
  );
  DFFSR _1084_ (
    .C(clk),
    .D(\synthory_ram_d[11] [2]),
    .Q(\synthory_ram_q[11] [2]),
    .R(_0446_),
    .S(1'b0)
  );
  DFFSR _1085_ (
    .C(clk),
    .D(\synthory_ram_d[11] [3]),
    .Q(\synthory_ram_q[11] [3]),
    .R(_0448_),
    .S(1'b0)
  );
  DFFSR _1086_ (
    .C(clk),
    .D(\synthory_ram_d[11] [4]),
    .Q(\synthory_ram_q[11] [4]),
    .R(_0449_),
    .S(1'b0)
  );
  DFFSR _1087_ (
    .C(clk),
    .D(\synthory_ram_d[12] [0]),
    .Q(\synthory_ram_q[12] [0]),
    .R(_0451_),
    .S(1'b0)
  );
  DFFSR _1088_ (
    .C(clk),
    .D(\synthory_ram_d[12] [1]),
    .Q(\synthory_ram_q[12] [1]),
    .R(_0453_),
    .S(1'b0)
  );
  DFFSR _1089_ (
    .C(clk),
    .D(\synthory_ram_d[12] [2]),
    .Q(\synthory_ram_q[12] [2]),
    .R(_0454_),
    .S(1'b0)
  );
  DFFSR _1090_ (
    .C(clk),
    .D(\synthory_ram_d[12] [3]),
    .Q(\synthory_ram_q[12] [3]),
    .R(_0455_),
    .S(1'b0)
  );
  DFFSR _1091_ (
    .C(clk),
    .D(\synthory_ram_d[12] [4]),
    .Q(\synthory_ram_q[12] [4]),
    .R(_0456_),
    .S(1'b0)
  );
  DFFSR _1092_ (
    .C(clk),
    .D(\synthory_ram_d[13] [0]),
    .Q(\synthory_ram_q[13] [0]),
    .R(_0457_),
    .S(1'b0)
  );
  DFFSR _1093_ (
    .C(clk),
    .D(\synthory_ram_d[13] [1]),
    .Q(\synthory_ram_q[13] [1]),
    .R(_0458_),
    .S(1'b0)
  );
  DFFSR _1094_ (
    .C(clk),
    .D(\synthory_ram_d[13] [2]),
    .Q(\synthory_ram_q[13] [2]),
    .R(_0459_),
    .S(1'b0)
  );
  DFFSR _1095_ (
    .C(clk),
    .D(\synthory_ram_d[13] [3]),
    .Q(\synthory_ram_q[13] [3]),
    .R(_0460_),
    .S(1'b0)
  );
  DFFSR _1096_ (
    .C(clk),
    .D(\synthory_ram_d[13] [4]),
    .Q(\synthory_ram_q[13] [4]),
    .R(_0461_),
    .S(1'b0)
  );
  DFFSR _1097_ (
    .C(clk),
    .D(\synthory_ram_d[14] [0]),
    .Q(\synthory_ram_q[14] [0]),
    .R(_0462_),
    .S(1'b0)
  );
  DFFSR _1098_ (
    .C(clk),
    .D(\synthory_ram_d[14] [1]),
    .Q(\synthory_ram_q[14] [1]),
    .R(_0463_),
    .S(1'b0)
  );
  DFFSR _1099_ (
    .C(clk),
    .D(\synthory_ram_d[14] [2]),
    .Q(\synthory_ram_q[14] [2]),
    .R(_0464_),
    .S(1'b0)
  );
  DFFSR _1100_ (
    .C(clk),
    .D(\synthory_ram_d[14] [3]),
    .Q(\synthory_ram_q[14] [3]),
    .R(_0465_),
    .S(1'b0)
  );
  DFFSR _1101_ (
    .C(clk),
    .D(\synthory_ram_d[14] [4]),
    .Q(\synthory_ram_q[14] [4]),
    .R(_0466_),
    .S(1'b0)
  );
  DFFSR _1102_ (
    .C(clk),
    .D(\synthory_ram_d[15] [0]),
    .Q(\synthory_ram_q[15] [0]),
    .R(_0467_),
    .S(1'b0)
  );
  DFFSR _1103_ (
    .C(clk),
    .D(\synthory_ram_d[15] [1]),
    .Q(\synthory_ram_q[15] [1]),
    .R(_0468_),
    .S(1'b0)
  );
  DFFSR _1104_ (
    .C(clk),
    .D(\synthory_ram_d[15] [2]),
    .Q(\synthory_ram_q[15] [2]),
    .R(_0469_),
    .S(1'b0)
  );
  DFFSR _1105_ (
    .C(clk),
    .D(\synthory_ram_d[15] [3]),
    .Q(\synthory_ram_q[15] [3]),
    .R(_0470_),
    .S(1'b0)
  );
  DFFSR _1106_ (
    .C(clk),
    .D(\synthory_ram_d[15] [4]),
    .Q(\synthory_ram_q[15] [4]),
    .R(_0000_),
    .S(1'b0)
  );
endmodule
