/* Generated by Yosys 0.8+285 (git sha1 a7ac8393, clang 6.0.0-1ubuntu2 -fPIC -Os) */

(* top =  1  *)
(* src = "ParaleloSerie_Est.v:1" *)
module ParaleloSerie_Est(data_inP, reset, clk_8f, clk_f, valid_in, data2send_est, data_outS_est);
  (* src = "ParaleloSerie_Est.v:13" *)
  wire [2:0] _00_;
  (* src = "ParaleloSerie_Est.v:18" *)
  wire [7:0] _01_;
  (* src = "ParaleloSerie_Est.v:19|<techmap.v>:142" *)
  wire [7:0] _02_;
  (* src = "ParaleloSerie_Est.v:19|<techmap.v>:145" *)
  wire [7:0] _03_;
  (* src = "ParaleloSerie_Est.v:19|<techmap.v>:145" *)
  wire [7:0] _04_;
  (* src = "ParaleloSerie_Est.v:14|<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _05_;
  wire [31:0] _06_;
  (* src = "ParaleloSerie_Est.v:14|<techmap.v>:260|<techmap.v>:221" *)
  wire _07_;
  (* src = "ParaleloSerie_Est.v:4" *)
  input clk_8f;
  (* src = "ParaleloSerie_Est.v:5" *)
  input clk_f;
  (* src = "ParaleloSerie_Est.v:7" *)
  output [7:0] data2send_est;
  (* src = "ParaleloSerie_Est.v:11" *)
  reg [7:0] data2send_estF;
  (* src = "ParaleloSerie_Est.v:2" *)
  input [7:0] data_inP;
  (* src = "ParaleloSerie_Est.v:8" *)
  output data_outS_est;
  (* src = "ParaleloSerie_Est.v:10" *)
  wire [2:0] out44_est;
  (* src = "ParaleloSerie_Est.v:10" *)
  reg [2:0] out44_estF;
  (* src = "ParaleloSerie_Est.v:3" *)
  input reset;
  (* src = "ParaleloSerie_Est.v:6" *)
  input valid_in;
  assign _01_[0] = valid_in ? (* src = "ParaleloSerie_Est.v:22" *) data_inP[0] : 1'h0;
  assign _01_[1] = valid_in ? (* src = "ParaleloSerie_Est.v:22" *) data_inP[1] : 1'h0;
  assign _01_[2] = valid_in ? (* src = "ParaleloSerie_Est.v:22" *) data_inP[2] : 1'h1;
  assign _01_[3] = valid_in ? (* src = "ParaleloSerie_Est.v:22" *) data_inP[3] : 1'h1;
  assign _01_[4] = valid_in ? (* src = "ParaleloSerie_Est.v:22" *) data_inP[4] : 1'h1;
  assign _01_[5] = valid_in ? (* src = "ParaleloSerie_Est.v:22" *) data_inP[5] : 1'h1;
  assign _01_[6] = valid_in ? (* src = "ParaleloSerie_Est.v:22" *) data_inP[6] : 1'h0;
  assign _01_[7] = valid_in ? (* src = "ParaleloSerie_Est.v:22" *) data_inP[7] : 1'h1;
  assign data2send_est[0] = reset ? (* src = "ParaleloSerie_Est.v:21" *) _01_[0] : data2send_estF[0];
  assign data2send_est[1] = reset ? (* src = "ParaleloSerie_Est.v:21" *) _01_[1] : data2send_estF[1];
  assign data2send_est[2] = reset ? (* src = "ParaleloSerie_Est.v:21" *) _01_[2] : data2send_estF[2];
  assign data2send_est[3] = reset ? (* src = "ParaleloSerie_Est.v:21" *) _01_[3] : data2send_estF[3];
  assign data2send_est[4] = reset ? (* src = "ParaleloSerie_Est.v:21" *) _01_[4] : data2send_estF[4];
  assign data2send_est[5] = reset ? (* src = "ParaleloSerie_Est.v:21" *) _01_[5] : data2send_estF[5];
  assign data2send_est[6] = reset ? (* src = "ParaleloSerie_Est.v:21" *) _01_[6] : data2send_estF[6];
  assign data2send_est[7] = reset ? (* src = "ParaleloSerie_Est.v:21" *) _01_[7] : data2send_estF[7];
  assign data_outS_est = reset ? (* src = "ParaleloSerie_Est.v:21" *) _02_[0] : 1'h0;
  assign out44_est[0] = reset ? (* src = "ParaleloSerie_Est.v:21" *) out44_estF[0] : 1'h0;
  assign out44_est[1] = reset ? (* src = "ParaleloSerie_Est.v:21" *) out44_estF[1] : 1'h0;
  assign out44_est[2] = reset ? (* src = "ParaleloSerie_Est.v:21" *) out44_estF[2] : 1'h0;
  assign _04_[0] = out44_estF[1] ? (* src = "ParaleloSerie_Est.v:19|<techmap.v>:162" *) _03_[2] : _03_[0];
  assign _04_[1] = out44_estF[1] ? (* src = "ParaleloSerie_Est.v:19|<techmap.v>:162" *) _03_[3] : _03_[1];
  assign _02_[0] = out44_estF[0] ? (* src = "ParaleloSerie_Est.v:19|<techmap.v>:162" *) _04_[1] : _04_[0];
  assign _03_[0] = out44_estF[2] ? (* src = "ParaleloSerie_Est.v:19|<techmap.v>:162" *) data2send_est[4] : data2send_est[0];
  assign _03_[1] = out44_estF[2] ? (* src = "ParaleloSerie_Est.v:19|<techmap.v>:162" *) data2send_est[5] : data2send_est[1];
  assign _03_[2] = out44_estF[2] ? (* src = "ParaleloSerie_Est.v:19|<techmap.v>:162" *) data2send_est[6] : data2send_est[2];
  assign _03_[3] = out44_estF[2] ? (* src = "ParaleloSerie_Est.v:19|<techmap.v>:162" *) data2send_est[7] : data2send_est[3];
  (* src = "ParaleloSerie_Est.v:13" *)
  always @(posedge clk_8f)
      out44_estF[0] <= _00_[0];
  (* src = "ParaleloSerie_Est.v:13" *)
  always @(posedge clk_8f)
      out44_estF[1] <= _00_[1];
  (* src = "ParaleloSerie_Est.v:13" *)
  always @(posedge clk_8f)
      out44_estF[2] <= _00_[2];
  (* src = "ParaleloSerie_Est.v:13" *)
  always @(posedge clk_8f)
      data2send_estF[0] <= data2send_est[0];
  (* src = "ParaleloSerie_Est.v:13" *)
  always @(posedge clk_8f)
      data2send_estF[1] <= data2send_est[1];
  (* src = "ParaleloSerie_Est.v:13" *)
  always @(posedge clk_8f)
      data2send_estF[2] <= data2send_est[2];
  (* src = "ParaleloSerie_Est.v:13" *)
  always @(posedge clk_8f)
      data2send_estF[3] <= data2send_est[3];
  (* src = "ParaleloSerie_Est.v:13" *)
  always @(posedge clk_8f)
      data2send_estF[4] <= data2send_est[4];
  (* src = "ParaleloSerie_Est.v:13" *)
  always @(posedge clk_8f)
      data2send_estF[5] <= data2send_est[5];
  (* src = "ParaleloSerie_Est.v:13" *)
  always @(posedge clk_8f)
      data2send_estF[6] <= data2send_est[6];
  (* src = "ParaleloSerie_Est.v:13" *)
  always @(posedge clk_8f)
      data2send_estF[7] <= data2send_est[7];
  assign _00_[0] = out44_est[0] ^(* src = "ParaleloSerie_Est.v:14|<techmap.v>:263" *)  1'h1;
  assign _00_[1] = _06_[1] ^(* src = "ParaleloSerie_Est.v:14|<techmap.v>:263" *)  out44_est[0];
  assign _00_[2] = _06_[2] ^(* src = "ParaleloSerie_Est.v:14|<techmap.v>:263" *)  _05_[1];
  assign _06_[1] = out44_est[1] ^(* src = "ParaleloSerie_Est.v:14|<techmap.v>:262" *)  1'h1;
  assign _06_[2] = out44_est[2] ^(* src = "ParaleloSerie_Est.v:14|<techmap.v>:262" *)  1'h1;
  assign _07_ = _06_[1] &(* src = "ParaleloSerie_Est.v:14|<techmap.v>:260|<techmap.v>:221" *)  out44_est[0];
  assign _05_[1] = out44_est[1] |(* src = "ParaleloSerie_Est.v:14|<techmap.v>:260|<techmap.v>:221" *)  _07_;
endmodule
