/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 4.8.4-2ubuntu1~14.04.3 -O2 -fstack-protector -fPIC -Os) */

(* top =  1  *)
(* src = "ParaleloSerie_Est.v:1" *)
module ParaleloSerie_Est(data_inP, reset, clk_8f, clk_f, valid_in, data2send_est, data_outS_est);
  (* src = "ParaleloSerie_Est.v:13" *)
  wire [2:0] _000_;
  (* src = "ParaleloSerie_Est.v:18" *)
  wire [7:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  (* src = "ParaleloSerie_Est.v:19|<techmap.v>:142" *)
  wire [7:0] _102_;
  (* src = "ParaleloSerie_Est.v:19|<techmap.v>:145" *)
  wire [7:0] _103_;
  (* src = "ParaleloSerie_Est.v:19|<techmap.v>:145" *)
  wire [7:0] _104_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _105_;
  wire [31:0] _106_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _107_;
  (* src = "ParaleloSerie_Est.v:4" *)
  input clk_8f;
  (* src = "ParaleloSerie_Est.v:5" *)
  input clk_f;
  (* src = "ParaleloSerie_Est.v:7" *)
  output [7:0] data2send_est;
  (* src = "ParaleloSerie_Est.v:11" *)
  wire [7:0] data2send_estF;
  (* src = "ParaleloSerie_Est.v:2" *)
  input [7:0] data_inP;
  (* src = "ParaleloSerie_Est.v:8" *)
  output data_outS_est;
  (* src = "ParaleloSerie_Est.v:10" *)
  wire [2:0] out44_est;
  (* src = "ParaleloSerie_Est.v:10" *)
  wire [2:0] out44_estF;
  (* src = "ParaleloSerie_Est.v:3" *)
  input reset;
  (* src = "ParaleloSerie_Est.v:6" *)
  input valid_in;
  NOT _108_ (
    .A(_015_),
    .Y(_033_)
  );
  NOR _109_ (
    .A(_016_),
    .B(_033_),
    .Y(_035_)
  );
  NOT _110_ (
    .A(_050_),
    .Y(_036_)
  );
  NAND _111_ (
    .A(_016_),
    .B(_017_),
    .Y(_038_)
  );
  NOR _112_ (
    .A(_038_),
    .B(_036_),
    .Y(_039_)
  );
  NOR _113_ (
    .A(_039_),
    .B(_035_),
    .Y(_041_)
  );
  NOT _114_ (
    .A(_041_),
    .Y(_018_)
  );
  NOT _115_ (
    .A(_019_),
    .Y(_042_)
  );
  NOR _116_ (
    .A(_042_),
    .B(_016_),
    .Y(_044_)
  );
  NOT _117_ (
    .A(_002_),
    .Y(_045_)
  );
  NOR _118_ (
    .A(_038_),
    .B(_045_),
    .Y(_046_)
  );
  NOR _119_ (
    .A(_046_),
    .B(_044_),
    .Y(_047_)
  );
  NOT _120_ (
    .A(_047_),
    .Y(_020_)
  );
  NOR _121_ (
    .A(_038_),
    .B(_051_),
    .Y(_048_)
  );
  NOR _122_ (
    .A(_021_),
    .B(_016_),
    .Y(_049_)
  );
  NOR _123_ (
    .A(_049_),
    .B(_048_),
    .Y(_022_)
  );
  NOR _124_ (
    .A(_038_),
    .B(_072_),
    .Y(_053_)
  );
  NOR _125_ (
    .A(_023_),
    .B(_016_),
    .Y(_054_)
  );
  NOR _126_ (
    .A(_054_),
    .B(_053_),
    .Y(_024_)
  );
  NOT _127_ (
    .A(_091_),
    .Y(_056_)
  );
  NOT _128_ (
    .A(_017_),
    .Y(_057_)
  );
  NOT _129_ (
    .A(_016_),
    .Y(_059_)
  );
  NOR _130_ (
    .A(_059_),
    .B(_057_),
    .Y(_060_)
  );
  NAND _131_ (
    .A(_060_),
    .B(_056_),
    .Y(_061_)
  );
  NOT _132_ (
    .A(_025_),
    .Y(_062_)
  );
  NAND _133_ (
    .A(_062_),
    .B(_059_),
    .Y(_063_)
  );
  NAND _134_ (
    .A(_063_),
    .B(_061_),
    .Y(_064_)
  );
  NOT _135_ (
    .A(_064_),
    .Y(_026_)
  );
  NOT _136_ (
    .A(_010_),
    .Y(_065_)
  );
  NAND _137_ (
    .A(_060_),
    .B(_065_),
    .Y(_066_)
  );
  NOT _138_ (
    .A(_027_),
    .Y(_067_)
  );
  NAND _139_ (
    .A(_067_),
    .B(_059_),
    .Y(_068_)
  );
  NAND _140_ (
    .A(_068_),
    .B(_066_),
    .Y(_069_)
  );
  NOT _141_ (
    .A(_069_),
    .Y(_028_)
  );
  NOT _142_ (
    .A(_029_),
    .Y(_070_)
  );
  NOR _143_ (
    .A(_070_),
    .B(_016_),
    .Y(_071_)
  );
  NOT _144_ (
    .A(_013_),
    .Y(_073_)
  );
  NOR _145_ (
    .A(_038_),
    .B(_073_),
    .Y(_074_)
  );
  NOR _146_ (
    .A(_074_),
    .B(_071_),
    .Y(_075_)
  );
  NOT _147_ (
    .A(_075_),
    .Y(_030_)
  );
  NOR _148_ (
    .A(_038_),
    .B(_014_),
    .Y(_076_)
  );
  NOR _149_ (
    .A(_031_),
    .B(_016_),
    .Y(_077_)
  );
  NOR _150_ (
    .A(_077_),
    .B(_076_),
    .Y(_032_)
  );
  NOT _151_ (
    .A(_034_),
    .Y(_078_)
  );
  NOR _152_ (
    .A(_078_),
    .B(_059_),
    .Y(_079_)
  );
  NOT _153_ (
    .A(_040_),
    .Y(_080_)
  );
  NAND _154_ (
    .A(_024_),
    .B(_080_),
    .Y(_081_)
  );
  NAND _155_ (
    .A(_032_),
    .B(_040_),
    .Y(_082_)
  );
  NAND _156_ (
    .A(_082_),
    .B(_081_),
    .Y(_083_)
  );
  NAND _157_ (
    .A(_083_),
    .B(_037_),
    .Y(_084_)
  );
  NOT _158_ (
    .A(_037_),
    .Y(_085_)
  );
  NAND _159_ (
    .A(_040_),
    .B(_085_),
    .Y(_086_)
  );
  NOR _160_ (
    .A(_086_),
    .B(_069_),
    .Y(_087_)
  );
  NAND _161_ (
    .A(_080_),
    .B(_085_),
    .Y(_088_)
  );
  NOR _162_ (
    .A(_088_),
    .B(_047_),
    .Y(_089_)
  );
  NOR _163_ (
    .A(_089_),
    .B(_087_),
    .Y(_090_)
  );
  NAND _164_ (
    .A(_090_),
    .B(_084_),
    .Y(_092_)
  );
  NAND _165_ (
    .A(_092_),
    .B(_079_),
    .Y(_093_)
  );
  NAND _166_ (
    .A(_075_),
    .B(_040_),
    .Y(_094_)
  );
  NOR _167_ (
    .A(_022_),
    .B(_040_),
    .Y(_095_)
  );
  NOR _168_ (
    .A(_095_),
    .B(_085_),
    .Y(_096_)
  );
  NAND _169_ (
    .A(_096_),
    .B(_094_),
    .Y(_097_)
  );
  NOR _170_ (
    .A(_086_),
    .B(_064_),
    .Y(_098_)
  );
  NOR _171_ (
    .A(_088_),
    .B(_041_),
    .Y(_099_)
  );
  NOR _172_ (
    .A(_099_),
    .B(_098_),
    .Y(_100_)
  );
  NAND _173_ (
    .A(_100_),
    .B(_097_),
    .Y(_101_)
  );
  NOR _174_ (
    .A(_034_),
    .B(_059_),
    .Y(_003_)
  );
  NAND _175_ (
    .A(_003_),
    .B(_101_),
    .Y(_004_)
  );
  NAND _176_ (
    .A(_004_),
    .B(_093_),
    .Y(_043_)
  );
  NOT _177_ (
    .A(_079_),
    .Y(_052_)
  );
  NAND _178_ (
    .A(_037_),
    .B(_034_),
    .Y(_005_)
  );
  NOR _179_ (
    .A(_037_),
    .B(_034_),
    .Y(_006_)
  );
  NOR _180_ (
    .A(_006_),
    .B(_059_),
    .Y(_007_)
  );
  NAND _181_ (
    .A(_007_),
    .B(_005_),
    .Y(_055_)
  );
  NOT _182_ (
    .A(_007_),
    .Y(_008_)
  );
  NOR _183_ (
    .A(_008_),
    .B(_040_),
    .Y(_009_)
  );
  NOT _184_ (
    .A(_003_),
    .Y(_011_)
  );
  NOR _185_ (
    .A(_011_),
    .B(_086_),
    .Y(_012_)
  );
  NOR _186_ (
    .A(_012_),
    .B(_009_),
    .Y(_058_)
  );
  DFF _187_ (
    .C(clk_8f),
    .D(_000_[0]),
    .Q(out44_estF[0])
  );
  DFF _188_ (
    .C(clk_8f),
    .D(_000_[1]),
    .Q(out44_estF[1])
  );
  DFF _189_ (
    .C(clk_8f),
    .D(_000_[2]),
    .Q(out44_estF[2])
  );
  DFF _190_ (
    .C(clk_8f),
    .D(data2send_est[0]),
    .Q(data2send_estF[0])
  );
  DFF _191_ (
    .C(clk_8f),
    .D(data2send_est[1]),
    .Q(data2send_estF[1])
  );
  DFF _192_ (
    .C(clk_8f),
    .D(data2send_est[2]),
    .Q(data2send_estF[2])
  );
  DFF _193_ (
    .C(clk_8f),
    .D(data2send_est[3]),
    .Q(data2send_estF[3])
  );
  DFF _194_ (
    .C(clk_8f),
    .D(data2send_est[4]),
    .Q(data2send_estF[4])
  );
  DFF _195_ (
    .C(clk_8f),
    .D(data2send_est[5]),
    .Q(data2send_estF[5])
  );
  DFF _196_ (
    .C(clk_8f),
    .D(data2send_est[6]),
    .Q(data2send_estF[6])
  );
  DFF _197_ (
    .C(clk_8f),
    .D(data2send_est[7]),
    .Q(data2send_estF[7])
  );
  assign _002_ = data_inP[1];
  assign _017_ = valid_in;
  assign _051_ = data_inP[2];
  assign _072_ = data_inP[3];
  assign _091_ = data_inP[4];
  assign _010_ = data_inP[5];
  assign _013_ = data_inP[6];
  assign _014_ = data_inP[7];
  assign _015_ = data2send_estF[0];
  assign _016_ = reset;
  assign data2send_est[0] = _018_;
  assign _019_ = data2send_estF[1];
  assign data2send_est[1] = _020_;
  assign _021_ = data2send_estF[2];
  assign data2send_est[2] = _022_;
  assign _023_ = data2send_estF[3];
  assign data2send_est[3] = _024_;
  assign _025_ = data2send_estF[4];
  assign data2send_est[4] = _026_;
  assign _027_ = data2send_estF[5];
  assign data2send_est[5] = _028_;
  assign _029_ = data2send_estF[6];
  assign data2send_est[6] = _030_;
  assign _031_ = data2send_estF[7];
  assign data2send_est[7] = _032_;
  assign _034_ = out44_estF[0];
  assign _037_ = out44_estF[1];
  assign _040_ = out44_estF[2];
  assign data_outS_est = _043_;
  assign _050_ = data_inP[0];
  assign _000_[0] = _052_;
  assign _000_[1] = _055_;
  assign _000_[2] = _058_;
endmodule
