/* Generated by Yosys 0.8+463 (git sha1 5772732a, clang 6.0.0-1ubuntu2 -fPIC -Os) */

(* top =  1  *)
(* src = "synth.v:1" *)
module synth(clk_2f, reset, out_synth0, out_synth1, data_in, valid_in, valid_out0_synth, valid_out1_synth);
  (* src = "synth.v:12" *)
  wire [7:0] _000_;
  (* src = "synth.v:12" *)
  wire [7:0] _001_;
  (* src = "synth.v:12" *)
  wire _002_;
  (* src = "synth.v:12" *)
  wire _003_;
  (* src = "synth.v:12" *)
  wire _004_;
  (* src = "synth.v:12" *)
  wire _005_;
  (* src = "synth.v:12" *)
  wire _006_;
  (* src = "synth.v:12" *)
  wire _007_;
  (* src = "synth.v:12" *)
  wire _008_;
  (* src = "synth.v:12" *)
  wire _009_;
  (* src = "synth.v:12" *)
  wire _010_;
  (* src = "synth.v:12" *)
  wire _011_;
  (* src = "synth.v:12" *)
  wire _012_;
  (* src = "synth.v:12" *)
  wire _013_;
  (* src = "synth.v:12" *)
  wire _014_;
  (* src = "synth.v:12" *)
  wire _015_;
  (* src = "synth.v:12" *)
  wire _016_;
  (* src = "synth.v:12" *)
  wire _017_;
  (* src = "synth.v:12" *)
  wire _018_;
  (* src = "synth.v:12" *)
  wire _019_;
  (* src = "synth.v:12" *)
  wire _020_;
  (* src = "synth.v:12" *)
  wire _021_;
  (* src = "synth.v:12" *)
  wire _022_;
  (* src = "synth.v:12" *)
  wire _023_;
  (* src = "synth.v:12" *)
  wire _024_;
  (* src = "synth.v:12" *)
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  (* src = "synth.v:2" *)
  input clk_2f;
  (* src = "synth.v:6" *)
  input [7:0] data_in;
  (* src = "synth.v:4" *)
  output [7:0] out_synth0;
  (* src = "synth.v:5" *)
  output [7:0] out_synth1;
  (* src = "synth.v:11" *)
  wire flag;
  (* src = "synth.v:3" *)
  input reset;
  (* src = "synth.v:11" *)
  wire selector;
  (* src = "synth.v:7" *)
  input valid_in;
  (* src = "synth.v:8" *)
  output valid_out0_synth;
  (* src = "synth.v:9" *)
  output valid_out1_synth;
  NOT _121_ (
    .A(valid_in),
    .Y(_077_)
  );
  NOT _122_ (
    .A(reset),
    .Y(_078_)
  );
  NOT _123_ (
    .A(data_in[0]),
    .Y(_079_)
  );
  NOT _124_ (
    .A(out_synth1[0]),
    .Y(_080_)
  );
  NOT _125_ (
    .A(flag),
    .Y(_081_)
  );
  NOT _126_ (
    .A(data_in[1]),
    .Y(_082_)
  );
  NOT _127_ (
    .A(out_synth1[1]),
    .Y(_083_)
  );
  NOT _128_ (
    .A(data_in[2]),
    .Y(_084_)
  );
  NOT _129_ (
    .A(out_synth1[2]),
    .Y(_085_)
  );
  NOT _130_ (
    .A(data_in[3]),
    .Y(_086_)
  );
  NOT _131_ (
    .A(out_synth1[3]),
    .Y(_087_)
  );
  NOT _132_ (
    .A(data_in[4]),
    .Y(_088_)
  );
  NOT _133_ (
    .A(out_synth1[4]),
    .Y(_089_)
  );
  NOT _134_ (
    .A(data_in[5]),
    .Y(_090_)
  );
  NOT _135_ (
    .A(out_synth1[5]),
    .Y(_091_)
  );
  NOT _136_ (
    .A(data_in[6]),
    .Y(_092_)
  );
  NOT _137_ (
    .A(out_synth1[6]),
    .Y(_093_)
  );
  NOT _138_ (
    .A(data_in[7]),
    .Y(_094_)
  );
  NOT _139_ (
    .A(out_synth1[7]),
    .Y(_095_)
  );
  NOT _140_ (
    .A(selector),
    .Y(_096_)
  );
  NOT _141_ (
    .A(valid_out0_synth),
    .Y(_097_)
  );
  NAND _142_ (
    .A(valid_in),
    .B(reset),
    .Y(_098_)
  );
  NOT _143_ (
    .A(_098_),
    .Y(_002_)
  );
  NAND _144_ (
    .A(valid_in),
    .B(selector),
    .Y(_099_)
  );
  NOT _145_ (
    .A(_099_),
    .Y(_100_)
  );
  NAND _146_ (
    .A(valid_in),
    .B(_096_),
    .Y(_101_)
  );
  NOR _147_ (
    .A(_081_),
    .B(_101_),
    .Y(_102_)
  );
  NOR _148_ (
    .A(_100_),
    .B(_102_),
    .Y(_103_)
  );
  NOR _149_ (
    .A(_077_),
    .B(flag),
    .Y(_104_)
  );
  NOR _150_ (
    .A(flag),
    .B(_099_),
    .Y(_105_)
  );
  NOR _151_ (
    .A(_102_),
    .B(_105_),
    .Y(_106_)
  );
  NAND _152_ (
    .A(_080_),
    .B(_106_),
    .Y(_107_)
  );
  NOR _153_ (
    .A(data_in[0]),
    .B(_106_),
    .Y(_108_)
  );
  NAND _154_ (
    .A(reset),
    .B(_107_),
    .Y(_109_)
  );
  NOR _155_ (
    .A(_108_),
    .B(_109_),
    .Y(_001_[0])
  );
  NAND _156_ (
    .A(_083_),
    .B(_106_),
    .Y(_110_)
  );
  NOR _157_ (
    .A(data_in[1]),
    .B(_106_),
    .Y(_111_)
  );
  NAND _158_ (
    .A(reset),
    .B(_110_),
    .Y(_112_)
  );
  NOR _159_ (
    .A(_111_),
    .B(_112_),
    .Y(_001_[1])
  );
  NAND _160_ (
    .A(_085_),
    .B(_106_),
    .Y(_113_)
  );
  NOR _161_ (
    .A(data_in[2]),
    .B(_106_),
    .Y(_114_)
  );
  NAND _162_ (
    .A(reset),
    .B(_113_),
    .Y(_115_)
  );
  NOR _163_ (
    .A(_114_),
    .B(_115_),
    .Y(_001_[2])
  );
  NAND _164_ (
    .A(_087_),
    .B(_106_),
    .Y(_116_)
  );
  NOR _165_ (
    .A(data_in[3]),
    .B(_106_),
    .Y(_117_)
  );
  NAND _166_ (
    .A(reset),
    .B(_116_),
    .Y(_118_)
  );
  NOR _167_ (
    .A(_117_),
    .B(_118_),
    .Y(_001_[3])
  );
  NAND _168_ (
    .A(_089_),
    .B(_106_),
    .Y(_119_)
  );
  NOR _169_ (
    .A(data_in[4]),
    .B(_106_),
    .Y(_120_)
  );
  NAND _170_ (
    .A(reset),
    .B(_119_),
    .Y(_026_)
  );
  NOR _171_ (
    .A(_120_),
    .B(_026_),
    .Y(_001_[4])
  );
  NAND _172_ (
    .A(_091_),
    .B(_106_),
    .Y(_027_)
  );
  NOR _173_ (
    .A(data_in[5]),
    .B(_106_),
    .Y(_028_)
  );
  NAND _174_ (
    .A(reset),
    .B(_027_),
    .Y(_029_)
  );
  NOR _175_ (
    .A(_028_),
    .B(_029_),
    .Y(_001_[5])
  );
  NAND _176_ (
    .A(_093_),
    .B(_106_),
    .Y(_030_)
  );
  NOR _177_ (
    .A(data_in[6]),
    .B(_106_),
    .Y(_031_)
  );
  NAND _178_ (
    .A(reset),
    .B(_030_),
    .Y(_032_)
  );
  NOR _179_ (
    .A(_031_),
    .B(_032_),
    .Y(_001_[6])
  );
  NOR _180_ (
    .A(_095_),
    .B(_102_),
    .Y(_033_)
  );
  NOR _181_ (
    .A(data_in[7]),
    .B(_100_),
    .Y(_034_)
  );
  NOR _182_ (
    .A(_103_),
    .B(_034_),
    .Y(_035_)
  );
  NOR _183_ (
    .A(_033_),
    .B(_035_),
    .Y(_036_)
  );
  NOR _184_ (
    .A(flag),
    .B(_094_),
    .Y(_037_)
  );
  NAND _185_ (
    .A(flag),
    .B(out_synth1[7]),
    .Y(_038_)
  );
  NOT _186_ (
    .A(_038_),
    .Y(_039_)
  );
  NOR _187_ (
    .A(_037_),
    .B(_039_),
    .Y(_040_)
  );
  NAND _188_ (
    .A(_100_),
    .B(_040_),
    .Y(_041_)
  );
  NAND _189_ (
    .A(reset),
    .B(_041_),
    .Y(_042_)
  );
  NOR _190_ (
    .A(_036_),
    .B(_042_),
    .Y(_001_[7])
  );
  NOR _191_ (
    .A(flag),
    .B(_101_),
    .Y(_043_)
  );
  NOR _192_ (
    .A(_100_),
    .B(_104_),
    .Y(_044_)
  );
  NOR _193_ (
    .A(_105_),
    .B(_044_),
    .Y(_045_)
  );
  NAND _194_ (
    .A(_079_),
    .B(_045_),
    .Y(_046_)
  );
  NOR _195_ (
    .A(out_synth0[0]),
    .B(_045_),
    .Y(_047_)
  );
  NAND _196_ (
    .A(reset),
    .B(_046_),
    .Y(_048_)
  );
  NOR _197_ (
    .A(_047_),
    .B(_048_),
    .Y(_000_[0])
  );
  NAND _198_ (
    .A(_082_),
    .B(_045_),
    .Y(_049_)
  );
  NOR _199_ (
    .A(out_synth0[1]),
    .B(_045_),
    .Y(_050_)
  );
  NAND _200_ (
    .A(reset),
    .B(_049_),
    .Y(_051_)
  );
  NOR _201_ (
    .A(_050_),
    .B(_051_),
    .Y(_000_[1])
  );
  NAND _202_ (
    .A(_084_),
    .B(_045_),
    .Y(_052_)
  );
  NOR _203_ (
    .A(out_synth0[2]),
    .B(_045_),
    .Y(_053_)
  );
  NAND _204_ (
    .A(reset),
    .B(_052_),
    .Y(_054_)
  );
  NOR _205_ (
    .A(_053_),
    .B(_054_),
    .Y(_000_[2])
  );
  NAND _206_ (
    .A(_086_),
    .B(_045_),
    .Y(_055_)
  );
  NOR _207_ (
    .A(out_synth0[3]),
    .B(_045_),
    .Y(_056_)
  );
  NAND _208_ (
    .A(reset),
    .B(_055_),
    .Y(_057_)
  );
  NOR _209_ (
    .A(_056_),
    .B(_057_),
    .Y(_000_[3])
  );
  NAND _210_ (
    .A(_088_),
    .B(_045_),
    .Y(_058_)
  );
  NOR _211_ (
    .A(out_synth0[4]),
    .B(_045_),
    .Y(_059_)
  );
  NAND _212_ (
    .A(reset),
    .B(_058_),
    .Y(_060_)
  );
  NOR _213_ (
    .A(_059_),
    .B(_060_),
    .Y(_000_[4])
  );
  NAND _214_ (
    .A(_090_),
    .B(_045_),
    .Y(_061_)
  );
  NOR _215_ (
    .A(out_synth0[5]),
    .B(_045_),
    .Y(_062_)
  );
  NAND _216_ (
    .A(reset),
    .B(_061_),
    .Y(_063_)
  );
  NOR _217_ (
    .A(_062_),
    .B(_063_),
    .Y(_000_[5])
  );
  NAND _218_ (
    .A(_092_),
    .B(_045_),
    .Y(_064_)
  );
  NOR _219_ (
    .A(out_synth0[6]),
    .B(_045_),
    .Y(_065_)
  );
  NAND _220_ (
    .A(reset),
    .B(_064_),
    .Y(_066_)
  );
  NOR _221_ (
    .A(_065_),
    .B(_066_),
    .Y(_000_[6])
  );
  NAND _222_ (
    .A(_094_),
    .B(_045_),
    .Y(_067_)
  );
  NOR _223_ (
    .A(out_synth0[7]),
    .B(_045_),
    .Y(_068_)
  );
  NAND _224_ (
    .A(reset),
    .B(_067_),
    .Y(_069_)
  );
  NOR _225_ (
    .A(_068_),
    .B(_069_),
    .Y(_000_[7])
  );
  NOR _226_ (
    .A(_096_),
    .B(_104_),
    .Y(_070_)
  );
  NOR _227_ (
    .A(_043_),
    .B(_070_),
    .Y(_071_)
  );
  NOR _228_ (
    .A(_078_),
    .B(_071_),
    .Y(_003_)
  );
  NOR _229_ (
    .A(_081_),
    .B(valid_out1_synth),
    .Y(_072_)
  );
  NOR _230_ (
    .A(_099_),
    .B(_072_),
    .Y(_073_)
  );
  NOR _231_ (
    .A(_102_),
    .B(_073_),
    .Y(_074_)
  );
  NOR _232_ (
    .A(_078_),
    .B(_074_),
    .Y(_005_)
  );
  NOR _233_ (
    .A(_097_),
    .B(_101_),
    .Y(_075_)
  );
  NOR _234_ (
    .A(_045_),
    .B(_075_),
    .Y(_076_)
  );
  NOR _235_ (
    .A(_078_),
    .B(_076_),
    .Y(_004_)
  );
  (* src = "synth.v:12" *)
  DFF _236_ (
    .C(clk_2f),
    .D(_004_),
    .Q(valid_out0_synth)
  );
  (* src = "synth.v:12" *)
  DFF _237_ (
    .C(clk_2f),
    .D(_005_),
    .Q(valid_out1_synth)
  );
  (* src = "synth.v:12" *)
  DFF _238_ (
    .C(clk_2f),
    .D(_003_),
    .Q(selector)
  );
  (* src = "synth.v:12" *)
  DFF _239_ (
    .C(clk_2f),
    .D(_000_[0]),
    .Q(out_synth0[0])
  );
  (* src = "synth.v:12" *)
  DFF _240_ (
    .C(clk_2f),
    .D(_000_[1]),
    .Q(out_synth0[1])
  );
  (* src = "synth.v:12" *)
  DFF _241_ (
    .C(clk_2f),
    .D(_000_[2]),
    .Q(out_synth0[2])
  );
  (* src = "synth.v:12" *)
  DFF _242_ (
    .C(clk_2f),
    .D(_000_[3]),
    .Q(out_synth0[3])
  );
  (* src = "synth.v:12" *)
  DFF _243_ (
    .C(clk_2f),
    .D(_000_[4]),
    .Q(out_synth0[4])
  );
  (* src = "synth.v:12" *)
  DFF _244_ (
    .C(clk_2f),
    .D(_000_[5]),
    .Q(out_synth0[5])
  );
  (* src = "synth.v:12" *)
  DFF _245_ (
    .C(clk_2f),
    .D(_000_[6]),
    .Q(out_synth0[6])
  );
  (* src = "synth.v:12" *)
  DFF _246_ (
    .C(clk_2f),
    .D(_000_[7]),
    .Q(out_synth0[7])
  );
  (* src = "synth.v:12" *)
  DFF _247_ (
    .C(clk_2f),
    .D(_001_[0]),
    .Q(out_synth1[0])
  );
  (* src = "synth.v:12" *)
  DFF _248_ (
    .C(clk_2f),
    .D(_001_[1]),
    .Q(out_synth1[1])
  );
  (* src = "synth.v:12" *)
  DFF _249_ (
    .C(clk_2f),
    .D(_001_[2]),
    .Q(out_synth1[2])
  );
  (* src = "synth.v:12" *)
  DFF _250_ (
    .C(clk_2f),
    .D(_001_[3]),
    .Q(out_synth1[3])
  );
  (* src = "synth.v:12" *)
  DFF _251_ (
    .C(clk_2f),
    .D(_001_[4]),
    .Q(out_synth1[4])
  );
  (* src = "synth.v:12" *)
  DFF _252_ (
    .C(clk_2f),
    .D(_001_[5]),
    .Q(out_synth1[5])
  );
  (* src = "synth.v:12" *)
  DFF _253_ (
    .C(clk_2f),
    .D(_001_[6]),
    .Q(out_synth1[6])
  );
  (* src = "synth.v:12" *)
  DFF _254_ (
    .C(clk_2f),
    .D(_001_[7]),
    .Q(out_synth1[7])
  );
  (* src = "synth.v:12" *)
  DFF _255_ (
    .C(clk_2f),
    .D(_002_),
    .Q(flag)
  );
  assign _022_ = _002_;
  assign _014_ = _001_[0];
  assign _015_ = _001_[1];
  assign _016_ = _001_[2];
  assign _017_ = _001_[3];
  assign _018_ = _001_[4];
  assign _019_ = _001_[5];
  assign _020_ = _001_[6];
  assign _021_ = _001_[7];
  assign _006_ = _000_[0];
  assign _007_ = _000_[1];
  assign _008_ = _000_[2];
  assign _009_ = _000_[3];
  assign _010_ = _000_[4];
  assign _011_ = _000_[5];
  assign _012_ = _000_[6];
  assign _013_ = _000_[7];
  assign _023_ = _003_;
  assign _025_ = _005_;
  assign _024_ = _004_;
endmodule
